In [68]:
from options.test_options import TestOptions
from data import DataLoader
from models import create_model
from util.writer import Writer
import numpy as np
import random
import torch.nn as nn
import torch

In [69]:
def test_attacked_model(model, dataset, writer):
    writer.reset_counter()
    attacked_model_outputs = []
    
    for i, data in enumerate(dataset):
        model.set_input(data)
        output, ncorrect, nexamples = model.test() 
        attacked_model_outputs.append(output)
        writer.update_counter(ncorrect, nexamples)
        
    writer.print_acc(-1, writer.acc)
    return attacked_model_outputs 
    
def find_new_vertex_index(vertices_edges, edge_index, old_vertex_index):
    for new_vertex_index, new_vertex_edges in enumerate(vertices_edges):
            for new_edge_index in new_vertex_edges:
                if(new_edge_index == edge_index and new_vertex_index != old_vertex_index):
                    return new_vertex_index
                
def get_random_walk(mesh, random_walk_size):
    walk_steps = 0
    random_walk_vertices = []
    random_walk_indices = []
    vertex_index = random.randint(0, len(mesh.vs)-1)
    
    while walk_steps < random_walk_size: 
        random_walk_vertices.append(mesh.vs[vertex_index])
        random_walk_indices.append(vertex_index)        
        walk_steps += 1  
        
        vertex_edges = mesh.ve[vertex_index]
        random_edge_index = random.randint(0, len(vertex_edges)-1)  
        new_edge_index = vertex_edges[random_edge_index]
        vertex_index = find_new_vertex_index(mesh.ve, new_edge_index, random_walk_indices[-1])
        
        #Prevents random walk from crossing over itself
        count_of_vertex_edge_attempts = 0
        walk_steps_backwards = 0
        while(vertex_index in random_walk_indices):
            if(count_of_vertex_edge_attempts >= len(vertex_edges)-1):
                walk_steps_backwards += 1
                go_back_to_index = walk_steps-walk_steps_backwards
                
                if(go_back_to_index == 0):
                    # Trying again, mesh seems to be broken?
                    return get_random_walk(mesh, random_walk_size)
                
                vertex_edges = mesh.ve[random_walk_indices[go_back_to_index]]
                count_of_vertex_edge_attempts = 0
                
            random_edge_index = (random_edge_index + 1) % len(vertex_edges)
            new_edge_index = vertex_edges[random_edge_index]
            vertex_index = find_new_vertex_index(mesh.ve, new_edge_index, random_walk_indices[-1])
            count_of_vertex_edge_attempts += 1        
    
    return torch.FloatTensor(random_walk_vertices), random_walk_indices

In [121]:
def train_imitating_network(imitating_nn, criterion, optimizer, random_walk_vertices, attacked_nn_output):

    output = imitating_nn(random_walk_vertices)
    loss = criterion(output, attacked_nn_output)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step() 

    return output, loss.item()

In [122]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size
        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        self.i2o = nn.Linear(input_size + hidden_size, output_size)

    def forward(self, input, hidden):
        
        combined = torch.cat((input, hidden), -1)
        hidden = self.i2h(combined)
        output = self.i2o(combined)
        
        return output, hidden

    def initHidden(self):
        return torch.zeros(1, self.hidden_size)

class Imitating_NN(nn.Module):
    def __init__(self, input_size, output_size):
        super(Imitating_NN, self).__init__()
        
        self.num_vertices = 3
        self.scaling_factor = 10
        
        self.first_linear = nn.Linear(input_size, input_size*self.scaling_factor)
        self.second_linear = nn.Linear(input_size*self.scaling_factor, input_size*self.scaling_factor)
        self.rnn = RNN(self.scaling_factor*input_size, input_size, self.scaling_factor*input_size)
        self.third_linear = nn.Linear(self.scaling_factor*input_size, output_size)
        
    def forward(self, random_walk_vertices):
        
        transformed_random_walk = self.first_linear(random_walk_vertices)
        transformed_random_walk = self.second_linear(transformed_random_walk)
        
        hidden = self.rnn.initHidden()
        for step in transformed_random_walk:
            output, hidden = self.rnn(torch.reshape(step, (1, self.num_vertices*self.scaling_factor)), hidden)
            
        output = self.second_linear(output)
            
        return output
        

# Orchestration

In [123]:
#TODO: test accuracy impact from random movement of vertices

testing_opt = TestOptions().parse()

testing_opt.serial_batches = True
dataloader = DataLoader(testing_opt)
mesh_cnn = create_model(testing_opt)
opt_writer = Writer(testing_opt)

random_walk_size = 50
num_categories = 30
num_vertice_coordinates = 3
imitating_nn = Imitating_NN(num_vertice_coordinates, num_categories)
criterion = nn.KLDivLoss(reduction="batchmean")
optimizer = torch.optim.Adam(imitating_nn.parameters(), lr = 0.0001)

loaded mean / std from cache
loading the model from ./checkpoints/shrec16/latest_net.pth


In [119]:
# Record testing accuracy before attack
attacked_model_outputs = test_attacked_model(mesh_cnn, dataloader, opt_writer)

epoch: -1, TEST ACC: [99.167 %]



In [124]:
# Stage attack
for epoch in range(10):
    epoch_loss = 0
    
    for i, data in enumerate(dataloader):
        print("i: " + str(i))
        print("Mesh labels: " + str(data["label"]))
    
        mesh = data["mesh"][0]
        random_walk_vertices, random_walk_indices = get_random_walk(mesh, random_walk_size)
    
        imitating_nn_output, loss = train_imitating_network(imitating_nn, criterion, optimizer, random_walk_vertices, attacked_model_outputs[i])
        epoch_loss += loss
    
        print(attacked_model_outputs[i])
        print(imitating_nn_output)
    
    print("epoch: " + str(epoch) + ", loss: " + str(epoch_loss))
    

i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[-0.1210, -0.0674,  0.0266, -0.0531, -0.1874, -0.0510,  0.0306,  0.1524,
         -0.0869,  0.1351,  0.0221,  0.0087, -0.0008, -0.0260,  0.1878, -0.1341,
         -0.0091,  0.1530,  0.3260, -0.2276, -0.0435, -0.1196,  0.3247,  0.0136,
         -0.0144, -0.0782,  0.2042, -0.1304, -0.0685, -0.0576]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.7529,
         -21.3954, -25.2309,  -

tensor([[-11.5600, -12.2807,  -8.4907,   4.3490,  -3.9629,  -6.6956,  -5.1210,
         -17.6667, -16.9735,  -6.5677, -17.3407, -22.6724, -22.5112, -12.0273,
          -9.3018,  -2.4722, -22.2240,  -8.2088,   0.6924, -21.5803, -12.2139,
          -6.7683, -23.1302,  -5.0496, -22.1565, -13.7152, -21.1941, -12.2661,
         -10.6854, -24.5271]])
tensor([[-0.0807, -0.0968,  0.0579, -0.0031, -0.2299, -0.0425,  0.0369,  0.1746,
         -0.0537,  0.0506,  0.1215, -0.0639,  0.0195,  0.0141,  0.1374, -0.1052,
          0.0374,  0.1472,  0.3343, -0.2354, -0.0790, -0.0903,  0.3866,  0.0048,
         -0.0126, -0.1334,  0.2438, -0.0851, -0.0726, -0.0877]],
       grad_fn=<AddmmBackward0>)
i: 13
Mesh labels: [3]
tensor([[-12.6880, -12.8750, -10.0355,   5.0915,  -2.9794,  -7.6716,  -4.5700,
         -18.3993, -15.3633,  -5.6254, -17.1177, -22.0048, -21.5706, -11.0255,
          -8.2964,  -3.0174, -23.5324, -10.5834,  -1.8890, -19.7286, -11.2272,
          -7.6164, -20.7858,  -7.4569, -21.0455, -11

tensor([[-14.5027, -13.2319, -21.4615, -12.8570, -17.1793, -11.6074,  -2.7180,
         -12.7763, -23.4383, -11.8774, -11.1201, -11.7537, -21.2265, -19.1802,
         -10.7729,  -9.0745, -16.8068, -27.7212, -18.5842, -12.0273, -22.8469,
         -23.7130, -26.2228, -11.3570, -20.5803, -15.3374, -26.3384, -21.8032,
         -11.9231, -15.5972]])
tensor([[-0.0823, -0.0682,  0.0615, -0.0186, -0.1913, -0.0440,  0.0316,  0.1631,
         -0.0832,  0.0981,  0.0652, -0.0247,  0.0170, -0.0045,  0.1654, -0.1319,
          0.0034,  0.1495,  0.3352, -0.2402, -0.0577, -0.1049,  0.3432,  0.0088,
          0.0013, -0.1058,  0.2326, -0.1185, -0.0671, -0.0776]],
       grad_fn=<AddmmBackward0>)
i: 26
Mesh labels: [6]
tensor([[-14.8296, -18.9902, -28.8402, -15.5756, -15.2484, -11.4294,  -2.6644,
         -13.2581, -24.5787, -13.1838, -15.5056,  -8.6107, -15.0708, -15.5415,
         -12.3020, -13.9708, -18.9744, -28.3200, -21.5157,  -9.3443, -19.8563,
         -25.5049, -21.4479, -16.4845, -22.2518, -11

tensor([[-26.9754,  -9.1055, -11.6346,  -6.0669, -11.5090, -14.4946,  -6.7320,
         -20.5614,  -9.8262,   2.1387, -16.3481, -24.1510, -28.9189, -11.5371,
          -5.3347,  -2.8517, -28.9497, -20.0269, -15.0855,  -8.7562, -25.8955,
         -10.0486, -12.0381, -17.0934, -13.8759, -14.2032,  -9.0038, -14.6300,
         -19.3966, -19.1076]])
tensor([[-0.0861, -0.0670,  0.0524,  0.0148, -0.1788, -0.0490,  0.0312,  0.1377,
         -0.1061,  0.0919,  0.0408, -0.0255, -0.0352, -0.0020,  0.1687, -0.1534,
         -0.0083,  0.1601,  0.3382, -0.2432, -0.0598, -0.0959,  0.3168, -0.0225,
          0.0276, -0.1065,  0.2369, -0.1137, -0.0348, -0.0877]],
       grad_fn=<AddmmBackward0>)
i: 39
Mesh labels: [9]
tensor([[-28.4242,  -8.2474, -13.6672,  -8.3598, -13.4178, -15.0705,  -6.6848,
         -19.5868,  -9.2745,   2.4944, -16.3123, -23.3888, -29.2222, -11.4324,
          -6.3626,  -4.3604, -29.0648, -22.5601, -18.4032,  -6.6493, -27.5186,
         -11.1720, -10.5156, -19.5232, -12.9198, -14

tensor([[-12.7686, -17.5714, -30.0671, -10.8246,  -6.6834,  -4.9487,  -5.6762,
          -8.2139, -19.3342,  -7.7499, -27.4529, -14.2749,  -6.1452,   5.8931,
         -16.9944, -13.9010, -22.8718, -15.9904, -17.8295,  -8.2325,  -8.0531,
          -7.1127, -12.5369, -20.3526, -26.0155,  -5.7977,  -4.3818,  -9.9493,
         -18.2877, -12.6711]])
tensor([[-0.0680, -0.0653,  0.0750, -0.0305, -0.1958, -0.0344,  0.0425,  0.2021,
         -0.0407,  0.1004,  0.1047, -0.0084,  0.0566,  0.0180,  0.1627, -0.1252,
          0.0203,  0.1510,  0.3335, -0.2337, -0.0650, -0.0924,  0.3580,  0.0233,
          0.0004, -0.1230,  0.2383, -0.1192, -0.0737, -0.0588]],
       grad_fn=<AddmmBackward0>)
i: 54
Mesh labels: [13]
tensor([[-13.8156, -12.8400, -23.8924,  -9.2676,  -7.2072,  -5.5136,  -4.7157,
          -7.4916, -14.0714,  -3.9144, -22.4206, -13.1019,  -8.7493,   5.0935,
         -12.8874, -10.2377, -20.8854, -15.0960, -16.5194,  -4.8228, -10.2136,
          -5.1903,  -9.4925, -18.2005, -20.1399,  -

i: 80
Mesh labels: [20]
tensor([[ -0.9398, -22.5821, -21.4887,  -6.3153,  -1.1521,  -5.7509,  -5.5441,
         -14.0662, -13.7762, -13.5974, -19.4549, -10.3509,  -1.6610,  -4.9267,
         -12.9887, -17.4118, -15.5724,  -6.1549,  -5.9195, -14.7092,   7.1912,
         -16.9145,  -9.2198, -13.0749, -19.5612,  -0.7572, -15.3230, -21.6191,
          -6.6983,  -9.1885]])
tensor([[-0.1218, -0.0473,  0.0317, -0.0113, -0.1570, -0.0198,  0.0444,  0.1426,
         -0.0924,  0.1806,  0.0301,  0.0592, -0.0102, -0.0188,  0.2104, -0.1368,
          0.0007,  0.1662,  0.3365, -0.2045, -0.0659, -0.1150,  0.2956, -0.0157,
          0.0171, -0.0674,  0.1858, -0.1210, -0.0319, -0.0460]],
       grad_fn=<AddmmBackward0>)
i: 81
Mesh labels: [20]
tensor([[ -0.6630, -25.3520, -25.4249,  -7.2448,  -1.0887,  -5.9956,  -5.7658,
         -14.7797, -15.9355, -15.4019, -21.8196, -10.4475,  -0.5207,  -4.7572,
         -14.8713, -19.8283, -16.9259,  -7.4369,  -7.5848, -15.6882,   8.5823,
         -18.7633,  -9.7143

tensor([[ -3.2772,  -6.2410,   0.3263,  -7.4497, -13.8696,  -6.0244,  -4.8933,
          -9.8932, -18.1966, -11.0320,  -5.3384, -14.0673, -22.4068, -21.0753,
          -8.9343,  -0.1367,  -4.9854, -10.0466,   0.3823, -19.8930, -18.8714,
         -14.1659, -30.1337,   8.0064, -17.8213, -18.3005, -27.0589, -11.5212,
          -1.8469, -21.2664]])
tensor([[-0.0501, -0.0688,  0.0858, -0.0175, -0.2387, -0.0289,  0.0510,  0.2308,
         -0.0063,  0.0527,  0.1506, -0.0202,  0.0681,  0.0684,  0.1434, -0.1190,
          0.0668,  0.1791,  0.3582, -0.2532, -0.0749, -0.0595,  0.3858,  0.0218,
          0.0048, -0.1623,  0.2659, -0.1021, -0.0608, -0.0496]],
       grad_fn=<AddmmBackward0>)
i: 93
Mesh labels: [23]
tensor([[ -3.6909,  -5.9709,   1.0664,  -8.3934, -15.2631,  -6.8052,  -5.2215,
         -10.0951, -18.2684, -11.5242,  -4.3991, -14.3283, -23.7509, -22.8639,
          -8.7133,  -0.1991,  -4.4016, -11.2588,  -0.1566, -20.0863, -20.3451,
         -15.7986, -31.4044,   8.3715, -17.4516, -1

tensor([[-21.1276, -13.8278, -17.8025,  -9.8308,  -6.5154, -12.9167,  -5.6215,
         -15.2185,  -5.4175,  -0.1052, -18.7047, -14.6672, -13.5262,   0.5832,
          -4.0985,  -8.7271, -24.9130, -17.5451, -15.6229,  -0.9495, -14.1109,
         -10.3972,  -2.3298, -19.7104, -11.7172,  -2.0794,   8.0094, -14.7358,
         -15.0662,  -6.3268]])
tensor([[-0.1120, -0.0530,  0.0512, -0.0793, -0.1789,  0.0220,  0.0486,  0.2183,
         -0.0129,  0.2132,  0.1026,  0.0852,  0.1008, -0.0161,  0.2196, -0.0754,
          0.0411,  0.1426,  0.3277, -0.1752, -0.0563, -0.1004,  0.3539,  0.0523,
         -0.0164, -0.0538,  0.1588, -0.1216, -0.0862, -0.0038]],
       grad_fn=<AddmmBackward0>)
i: 106
Mesh labels: [26]
tensor([[-22.2103, -14.2283, -17.4416, -10.3296,  -7.0518, -14.0602,  -6.0426,
         -16.4692,  -4.8842,  -0.1681, -18.6683, -15.5927, -14.7723,  -0.5350,
          -3.7112,  -9.0139, -25.7566, -18.5038, -15.9934,  -1.2614, -14.9617,
         -11.6368,  -2.3345, -20.2120, -11.3346,  

tensor([[-0.0871, -0.0755,  0.0720, -0.0040, -0.2247,  0.0092,  0.0460,  0.2097,
         -0.0061,  0.0835,  0.1826, -0.0034,  0.0562,  0.0532,  0.1624, -0.0756,
          0.0741,  0.1464,  0.3349, -0.2105, -0.0881, -0.0443,  0.3979,  0.0187,
          0.0215, -0.1204,  0.2345, -0.0433, -0.0507, -0.0245]],
       grad_fn=<AddmmBackward0>)
i: 119
Mesh labels: [29]
tensor([[-18.8807, -12.3198, -21.9328, -17.8029, -16.0201, -14.3143,  -4.0312,
         -10.8912, -11.3684,  -6.8313,  -7.8095,  -4.8690, -11.8939, -12.9485,
          -2.8966, -13.0286, -15.8504, -27.3249, -22.9779,   3.0996, -19.1669,
         -25.8141,  -6.5076, -19.8380,  -5.8325,  -7.0266,  -8.9947, -23.0040,
          -9.8068,   1.2095]])
tensor([[-0.0769, -0.0557,  0.0657, -0.0286, -0.2140, -0.0084,  0.0339,  0.2157,
         -0.0212,  0.1239,  0.1362,  0.0218,  0.0561,  0.0442,  0.1870, -0.1048,
          0.0576,  0.1611,  0.3431, -0.2250, -0.0603, -0.0659,  0.3672,  0.0373,
          0.0206, -0.1051,  0.2374, -0.0851,

tensor([[-10.9553,  -3.3222,   9.1418,  -4.5795,  -8.6886,  -9.1763,  -5.9624,
         -14.7096,  -0.7934,  -1.9389,  -2.6520, -17.6002, -22.9457, -17.7792,
          -2.4661,  -0.5740,  -9.7566,  -7.7380,  -1.4543, -12.5074, -16.5481,
          -9.8429, -14.6048,   0.6288,  -5.3444, -12.3493, -15.1318, -11.3754,
          -5.3098, -16.0334]])
tensor([[-0.0891, -0.0443,  0.0607, -0.0479, -0.1958,  0.0049,  0.0318,  0.2161,
         -0.0211,  0.1639,  0.1235,  0.0523,  0.0711,  0.0299,  0.2037, -0.0954,
          0.0499,  0.1479,  0.3344, -0.2033, -0.0572, -0.0717,  0.3574,  0.0419,
          0.0188, -0.0785,  0.2145, -0.0847, -0.0441, -0.0035]],
       grad_fn=<AddmmBackward0>)
i: 11
Mesh labels: [2]
tensor([[-1.1452e+01, -3.2160e+00,  9.4250e+00, -5.3613e+00, -9.1504e+00,
         -9.9146e+00, -6.1322e+00, -1.5043e+01,  5.1049e-01, -1.6524e+00,
         -2.1122e+00, -1.7273e+01, -2.3024e+01, -1.8343e+01, -2.1103e+00,
         -1.0108e+00, -9.7606e+00, -8.3661e+00, -1.9964e+00, -1.171

i: 34
Mesh labels: [8]
tensor([[-19.5553,  -9.0141,   0.4047,  -7.3339,  -8.1700, -16.3926,  -7.2686,
         -21.7274,   6.5232,  -0.0488,  -5.9658, -17.7499, -21.4305, -16.0496,
          -0.1440,  -8.5923, -19.3170, -15.4958,  -9.0545,  -6.1904, -15.2726,
         -17.1233,  -1.7141, -13.4231,   0.0432,  -5.3454,  -7.0391, -20.7602,
         -10.1149,  -8.9351]])
tensor([[-0.0726, -0.0294,  0.0766, -0.0250, -0.1807, -0.0035,  0.0243,  0.2075,
         -0.0483,  0.1589,  0.1018,  0.0482,  0.0498,  0.0383,  0.2068, -0.1241,
          0.0349,  0.1596,  0.3411, -0.2222, -0.0479, -0.0725,  0.3336,  0.0329,
          0.0401, -0.0817,  0.2368, -0.0949, -0.0207, -0.0158]],
       grad_fn=<AddmmBackward0>)
i: 35
Mesh labels: [8]
tensor([[-1.7106e+01, -7.9029e+00,  3.0505e+00, -7.1686e+00, -8.2045e+00,
         -1.4928e+01, -7.2167e+00, -2.0442e+01,  5.7832e+00, -1.0524e+00,
         -4.4620e+00, -1.7031e+01, -2.0959e+01, -1.7326e+01, -3.3341e-01,
         -7.6827e+00, -1.6255e+01, -1.3194e+

tensor([[-20.3809, -13.3521, -10.1346, -11.6553, -13.3656, -19.2275,  -5.9840,
         -20.2482,  -6.5062,  -6.6484,  -4.9090, -11.8888, -19.6884, -20.8907,
           3.5689,  -8.4722, -19.5445, -23.8601, -13.2722,  -4.5353, -19.6709,
         -27.9231, -10.0866, -14.3799,  -2.6616,  -7.7665, -12.2356, -28.6508,
          -4.5376,  -3.2128]])
tensor([[-0.0722, -0.0285,  0.0780, -0.0068, -0.1848, -0.0057,  0.0312,  0.2080,
         -0.0362,  0.1432,  0.1237,  0.0517,  0.0400,  0.0651,  0.1971, -0.1319,
          0.0418,  0.1652,  0.3420, -0.2258, -0.0584, -0.0566,  0.3366,  0.0185,
          0.0554, -0.1033,  0.2484, -0.0747, -0.0053, -0.0078]],
       grad_fn=<AddmmBackward0>)
i: 59
Mesh labels: [14]
tensor([[-20.5121, -10.8599,  -7.5975, -11.9631, -13.1542, -18.6488,  -6.4280,
         -20.0937,  -4.2401,  -6.0960,  -2.7362, -11.5782, -19.2985, -22.1444,
           4.0644,  -8.5918, -17.2663, -21.8911, -12.9144,  -3.9298, -19.6721,
         -27.1996,  -7.6258, -14.0386,   0.8437,  -

tensor([[-12.2687, -12.3794, -11.0054,  -6.8599,  -1.9677,   1.5837,  -9.4217,
         -18.1577, -15.6965,  -8.2384, -22.2376, -20.2821, -11.4909,  -9.1650,
         -15.4076, -11.0496, -14.1956,   9.7812,  -1.0248, -20.0553,  -9.9837,
          -1.1009, -12.3787,  -8.4523, -18.8392, -18.1488, -17.0252, -10.6071,
         -10.4759, -21.2388]])
tensor([[-0.0895, -0.0017,  0.0550, -0.0428, -0.1487, -0.0148,  0.0237,  0.1961,
         -0.0637,  0.2289,  0.0461,  0.1180,  0.0310,  0.0344,  0.2445, -0.1585,
          0.0153,  0.1764,  0.3447, -0.2187, -0.0291, -0.0887,  0.2846,  0.0251,
          0.0548, -0.0569,  0.2204, -0.1301,  0.0046,  0.0027]],
       grad_fn=<AddmmBackward0>)
i: 71
Mesh labels: [17]
tensor([[-11.8748, -12.4198, -10.1863,  -7.0423,  -2.3060,   0.9893,  -9.2045,
         -18.1749, -14.9915,  -8.3809, -21.1256, -19.9540, -11.8130,  -9.8971,
         -14.5896, -10.9697, -13.8232,   9.1062,  -0.7848, -19.7840,  -9.8210,
          -2.3611, -12.4612,  -7.9398, -18.0150, -1

tensor([[ -3.2772,  -6.2410,   0.3263,  -7.4497, -13.8696,  -6.0244,  -4.8933,
          -9.8932, -18.1966, -11.0320,  -5.3384, -14.0673, -22.4068, -21.0753,
          -8.9343,  -0.1367,  -4.9854, -10.0466,   0.3823, -19.8930, -18.8714,
         -14.1659, -30.1337,   8.0064, -17.8213, -18.3005, -27.0589, -11.5212,
          -1.8469, -21.2664]])
tensor([[-8.5582e-02, -2.9989e-02,  6.9903e-02, -1.4043e-02, -1.9642e-01,
          1.8017e-02,  3.5156e-02,  2.1849e-01, -2.3930e-02,  1.7666e-01,
          1.2886e-01,  8.1753e-02,  5.1872e-02,  5.5494e-02,  2.1638e-01,
         -1.1227e-01,  6.8873e-02,  1.8166e-01,  3.5356e-01, -2.1061e-01,
         -5.0601e-02, -6.1015e-02,  3.4014e-01,  2.4493e-02,  3.9741e-02,
         -8.4377e-02,  2.2597e-01, -7.7704e-02, -5.5305e-03, -1.4829e-04]],
       grad_fn=<AddmmBackward0>)
i: 93
Mesh labels: [23]
tensor([[ -3.6909,  -5.9709,   1.0664,  -8.3934, -15.2631,  -6.8052,  -5.2215,
         -10.0951, -18.2684, -11.5242,  -4.3991, -14.3283, -23.7509, -2

tensor([[-14.9681, -21.4830, -27.5907, -20.2782, -12.7485, -15.4414,  -4.5263,
         -14.4074, -14.7664, -13.7452,  -9.4865,  -0.9243,  -3.6304, -15.9467,
          -3.5095, -19.6070, -15.4743, -26.7960, -21.8208,   0.1929, -12.7745,
         -33.8928,  -6.2963, -21.3034,  -7.6566,  -2.9492, -13.2439, -34.3099,
          -4.4751,   5.7164]])
tensor([[-5.4987e-02, -1.8668e-02,  8.8386e-02, -3.7095e-02, -2.1555e-01,
          1.7416e-02,  2.2499e-02,  2.6140e-01,  1.4569e-02,  1.5237e-01,
          1.7616e-01,  7.1552e-02,  8.3844e-02,  1.0291e-01,  2.1276e-01,
         -1.0469e-01,  9.0082e-02,  1.7756e-01,  3.5768e-01, -2.3246e-01,
         -4.2431e-02, -2.4300e-02,  3.7051e-01,  6.3037e-02,  6.3482e-02,
         -1.0077e-01,  2.6066e-01, -6.1276e-02, -1.6325e-04,  2.2396e-02]],
       grad_fn=<AddmmBackward0>)
i: 117
Mesh labels: [29]
tensor([[-13.3109, -17.6586, -22.6130, -18.1277, -13.3338, -13.9144,  -5.0583,
         -12.6665, -15.2249, -13.3974,  -7.8443,  -2.6484,  -5.6877, -

tensor([[-1.1452e+01, -3.2160e+00,  9.4250e+00, -5.3613e+00, -9.1504e+00,
         -9.9146e+00, -6.1322e+00, -1.5043e+01,  5.1049e-01, -1.6524e+00,
         -2.1122e+00, -1.7273e+01, -2.3024e+01, -1.8343e+01, -2.1103e+00,
         -1.0108e+00, -9.7606e+00, -8.3661e+00, -1.9964e+00, -1.1714e+01,
         -1.6921e+01, -1.0647e+01, -1.3422e+01, -1.6649e-02, -4.1966e+00,
         -1.1970e+01, -1.4479e+01, -1.1983e+01, -5.3938e+00, -1.5116e+01]])
tensor([[-0.0339, -0.0062,  0.1097, -0.0662, -0.2265,  0.0328,  0.0195,  0.3022,
          0.0546,  0.1440,  0.2180,  0.0760,  0.1401,  0.1315,  0.2071, -0.0831,
          0.1084,  0.1629,  0.3562, -0.2318, -0.0458, -0.0029,  0.3964,  0.0919,
          0.0658, -0.1100,  0.2706, -0.0418, -0.0076,  0.0621]],
       grad_fn=<AddmmBackward0>)
i: 12
Mesh labels: [3]
tensor([[-11.5600, -12.2807,  -8.4907,   4.3490,  -3.9629,  -6.6956,  -5.1210,
         -17.6667, -16.9735,  -6.5677, -17.3407, -22.6724, -22.5112, -12.0273,
          -9.3018,  -2.4722, -22

tensor([[-18.9369, -10.2751,  -1.0090,  -7.7069,  -8.1557, -16.9523,  -7.0503,
         -21.4820,   6.7166,  -0.1982,  -6.7011, -16.8088, -19.9197, -14.5262,
          -0.3561,  -9.2874, -19.6914, -16.5241,  -9.4351,  -5.6170, -14.0726,
         -17.6426,  -1.5084, -14.1979,  -0.5341,  -3.2817,  -5.2917, -21.1926,
         -10.2757,  -7.6201]])
tensor([[-0.0519, -0.0226,  0.1289, -0.0054, -0.2141,  0.0672,  0.0281,  0.2749,
          0.0380,  0.1205,  0.2582,  0.0543,  0.1236,  0.1251,  0.1932, -0.0533,
          0.1128,  0.1409,  0.3400, -0.2055, -0.0747,  0.0058,  0.4102,  0.0570,
          0.0759, -0.1060,  0.2639,  0.0144, -0.0029,  0.0537]],
       grad_fn=<AddmmBackward0>)
i: 33
Mesh labels: [8]
tensor([[-19.2015,  -7.6961,   1.6663,  -8.8975, -10.2675, -17.7330,  -7.1715,
         -21.1468,   8.0029,  -0.9143,  -2.3878, -15.6646, -21.4830, -19.1768,
           1.4798,  -8.8586, -16.8805, -17.7200,  -9.9703,  -4.9373, -16.2723,
         -20.4854,  -1.9121, -13.1078,   3.5726,  -5

tensor([[ -2.6931, -18.4670, -30.7381, -21.3479, -15.9281,  -7.0441,  -2.5440,
          -2.5455, -25.0249, -19.4351,  -8.5030,   5.6621,   1.6988, -13.7873,
         -12.1763, -18.8024,  -3.8106, -25.8824, -22.2376,  -4.2626, -11.1032,
         -30.0106, -17.9421, -12.6658, -16.8919,  -6.9994, -23.4696, -24.8537,
          -3.5843,   0.6504]])
tensor([[-0.0298,  0.0062,  0.1187, -0.0272, -0.1976,  0.0270,  0.0131,  0.2800,
          0.0183,  0.1602,  0.1880,  0.0797,  0.0943,  0.1297,  0.2186, -0.1157,
          0.0862,  0.1764,  0.3589, -0.2413, -0.0380, -0.0100,  0.3603,  0.0675,
          0.0911, -0.1024,  0.2823, -0.0507,  0.0254,  0.0430]],
       grad_fn=<AddmmBackward0>)
i: 46
Mesh labels: [11]
tensor([[ -5.1981, -17.0249, -31.0923, -21.8705, -19.3145,  -8.5461,  -1.3353,
          -2.6037, -25.6356, -18.1405,  -7.1999,   5.3960,  -3.4527, -15.7456,
         -12.1256, -17.2593,  -4.6006, -30.4048, -24.7604,  -3.2078, -15.8416,
         -31.4539, -20.3277, -13.1523, -17.3869,  -

tensor([[-20.3809, -13.3521, -10.1346, -11.6553, -13.3656, -19.2275,  -5.9840,
         -20.2482,  -6.5062,  -6.6484,  -4.9090, -11.8888, -19.6884, -20.8907,
           3.5689,  -8.4722, -19.5445, -23.8601, -13.2722,  -4.5353, -19.6709,
         -27.9231, -10.0866, -14.3799,  -2.6616,  -7.7665, -12.2356, -28.6508,
          -4.5376,  -3.2128]])
tensor([[-0.1025,  0.0047,  0.0915, -0.0547, -0.1616,  0.0690,  0.0373,  0.2569,
          0.0204,  0.2519,  0.1753,  0.1611,  0.1248,  0.0690,  0.2478, -0.0786,
          0.0793,  0.1473,  0.3335, -0.1653, -0.0520, -0.0411,  0.3534,  0.0556,
          0.0586, -0.0409,  0.2012, -0.0447, -0.0081,  0.0832]],
       grad_fn=<AddmmBackward0>)
i: 59
Mesh labels: [14]
tensor([[-20.5121, -10.8599,  -7.5975, -11.9631, -13.1542, -18.6488,  -6.4280,
         -20.0937,  -4.2401,  -6.0960,  -2.7362, -11.5782, -19.2985, -22.1444,
           4.0644,  -8.5918, -17.2663, -21.8911, -12.9144,  -3.9298, -19.6721,
         -27.1996,  -7.6258, -14.0386,   0.8437,  -

tensor([[-12.2687, -12.3794, -11.0054,  -6.8599,  -1.9677,   1.5837,  -9.4217,
         -18.1577, -15.6965,  -8.2384, -22.2376, -20.2821, -11.4909,  -9.1650,
         -15.4076, -11.0496, -14.1956,   9.7812,  -1.0248, -20.0553,  -9.9837,
          -1.1009, -12.3787,  -8.4523, -18.8392, -18.1488, -17.0252, -10.6071,
         -10.4759, -21.2388]])
tensor([[-0.1056, -0.0197,  0.1057, -0.0169, -0.1889,  0.1020,  0.0482,  0.2648,
          0.0501,  0.2017,  0.2594,  0.1315,  0.1435,  0.0938,  0.2254, -0.0254,
          0.1193,  0.1250,  0.3239, -0.1511, -0.0859, -0.0150,  0.4012,  0.0459,
          0.0601, -0.0643,  0.2065,  0.0272, -0.0164,  0.0888]],
       grad_fn=<AddmmBackward0>)
i: 71
Mesh labels: [17]
tensor([[-11.8748, -12.4198, -10.1863,  -7.0423,  -2.3060,   0.9893,  -9.2045,
         -18.1749, -14.9915,  -8.3809, -21.1256, -19.9540, -11.8130,  -9.8971,
         -14.5896, -10.9697, -13.8232,   9.1062,  -0.7848, -19.7840,  -9.8210,
          -2.3611, -12.4612,  -7.9398, -18.0150, -1

tensor([[ -3.6909,  -5.9709,   1.0664,  -8.3934, -15.2631,  -6.8052,  -5.2215,
         -10.0951, -18.2684, -11.5242,  -4.3991, -14.3283, -23.7509, -22.8639,
          -8.7133,  -0.1991,  -4.4016, -11.2588,  -0.1566, -20.0863, -20.3451,
         -15.7986, -31.4044,   8.3715, -17.4516, -19.1758, -28.3254, -12.3074,
          -1.5262, -21.3404]])
tensor([[-0.0898,  0.0281,  0.0764, -0.0675, -0.1716,  0.0488,  0.0230,  0.2601,
         -0.0009,  0.2963,  0.1176,  0.1942,  0.1010,  0.0675,  0.2831, -0.1202,
          0.0891,  0.1978,  0.3722, -0.1955, -0.0124, -0.0585,  0.3177,  0.0673,
          0.0611, -0.0253,  0.2114, -0.0982,  0.0234,  0.0665]],
       grad_fn=<AddmmBackward0>)
i: 94
Mesh labels: [23]
tensor([[ -2.9784,  -4.4604,  -1.8961,  -9.3151, -17.1384,  -6.3612,  -4.1701,
          -7.2187, -20.3217, -11.6831,  -3.7824, -12.5407, -23.2622, -21.8246,
         -10.2428,  -0.1535,  -3.3852, -14.7988,  -3.6948, -18.7315, -21.2843,
         -15.8201, -33.0464,   7.7941, -18.8109, -1

tensor([[-22.2103, -14.2283, -17.4416, -10.3296,  -7.0518, -14.0602,  -6.0426,
         -16.4692,  -4.8842,  -0.1681, -18.6683, -15.5927, -14.7723,  -0.5350,
          -3.7112,  -9.0139, -25.7566, -18.5038, -15.9934,  -1.2614, -14.9617,
         -11.6368,  -2.3345, -20.2120, -11.3346,  -2.3263,   7.8108, -16.1265,
         -15.1493,  -6.5757]])
tensor([[-0.0248,  0.0484,  0.1119, -0.1172, -0.2012,  0.0378,  0.0092,  0.3408,
          0.0572,  0.2747,  0.1575,  0.1884,  0.1644,  0.1291,  0.2812, -0.1256,
          0.1132,  0.2200,  0.3925, -0.2427,  0.0143, -0.0272,  0.3464,  0.1388,
          0.0715, -0.0605,  0.2561, -0.1305,  0.0207,  0.0808]],
       grad_fn=<AddmmBackward0>)
i: 107
Mesh labels: [26]
tensor([[-20.4858, -14.5195, -17.9894,  -9.6578,  -5.7690, -12.8269,  -5.4880,
         -15.2435,  -5.2535,  -0.3668, -18.8117, -14.1828, -12.4093,   0.9912,
          -3.8652,  -9.0219, -24.8032, -17.0661, -15.1116,  -0.9258, -12.9558,
         -10.5589,  -1.9612, -19.6294, -11.6979,  

tensor([[-18.8807, -12.3198, -21.9328, -17.8029, -16.0201, -14.3143,  -4.0312,
         -10.8912, -11.3684,  -6.8313,  -7.8095,  -4.8690, -11.8939, -12.9485,
          -2.8966, -13.0286, -15.8504, -27.3249, -22.9779,   3.0996, -19.1669,
         -25.8141,  -6.5076, -19.8380,  -5.8325,  -7.0266,  -8.9947, -23.0040,
          -9.8068,   1.2095]])
tensor([[-0.0874,  0.0174,  0.1005, -0.0615, -0.1986,  0.0932,  0.0209,  0.2965,
          0.0519,  0.2631,  0.2258,  0.1766,  0.1471,  0.1055,  0.2706, -0.0577,
          0.1333,  0.1671,  0.3581, -0.1807, -0.0311, -0.0132,  0.3827,  0.0932,
          0.0753, -0.0305,  0.2247, -0.0155,  0.0164,  0.1000]],
       grad_fn=<AddmmBackward0>)
epoch: 2, loss: 1387.727934844792
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, 

tensor([[ -9.1728, -12.1504, -21.6671, -10.1149,  -6.2599,   3.3546,  -5.6768,
          -8.6273, -23.1617, -10.5796, -21.3516, -12.7094,  -6.6412,  -4.6775,
         -18.9983, -12.1906, -11.0990,  -3.2922, -11.6404, -14.7161, -11.6030,
          -3.6861, -17.5273, -10.8596, -23.8591, -16.8262, -18.6928,  -8.1418,
         -13.5632, -18.4154]])
tensor([[-0.0245,  0.0393,  0.1413, -0.0126, -0.2043,  0.0651,  0.0022,  0.2988,
          0.0384,  0.1787,  0.2459,  0.1246,  0.1086,  0.1838,  0.2421, -0.1009,
          0.1256,  0.1912,  0.3689, -0.2419, -0.0297,  0.0312,  0.3788,  0.0797,
          0.1385, -0.0943,  0.3024,  0.0096,  0.0741,  0.0923]],
       grad_fn=<AddmmBackward0>)
i: 23
Mesh labels: [5]
tensor([[-10.1052, -14.2137, -22.5353, -10.7191,  -5.8350,   2.6554,  -5.7042,
         -10.5656, -23.5730, -11.4148, -21.4100, -12.5334,  -6.3684,  -6.3531,
         -18.2538, -13.3801, -12.0193,  -3.4056, -11.6031, -14.8968, -11.6538,
          -5.9565, -17.2136, -11.8770, -23.4945, -16

tensor([[ -1.8415, -14.3549, -27.4199, -21.6404, -19.2456,  -6.6965,  -1.7176,
          -0.5529, -24.7352, -18.7934,  -4.2435,   6.6159,  -1.9919, -16.5774,
         -12.2038, -16.6825,   0.7559, -27.3295, -22.7109,  -4.0940, -14.1427,
         -30.2774, -20.9690,  -9.5340, -15.8455,  -9.3676, -26.3514, -22.0967,
          -3.8169,  -0.8077]])
tensor([[-0.0762,  0.0347,  0.1223, -0.0261, -0.1745,  0.1013,  0.0173,  0.2891,
          0.0426,  0.2516,  0.2335,  0.1730,  0.1223,  0.1316,  0.2657, -0.0698,
          0.1224,  0.1646,  0.3540, -0.1828, -0.0401,  0.0103,  0.3711,  0.0691,
          0.1132, -0.0390,  0.2399,  0.0121,  0.0510,  0.1162]],
       grad_fn=<AddmmBackward0>)
i: 45
Mesh labels: [11]
tensor([[ -2.6931, -18.4670, -30.7381, -21.3479, -15.9281,  -7.0441,  -2.5440,
          -2.5455, -25.0249, -19.4351,  -8.5030,   5.6621,   1.6988, -13.7873,
         -12.1763, -18.8024,  -3.8106, -25.8824, -22.2376,  -4.2626, -11.1032,
         -30.0106, -17.9421, -12.6658, -16.8919,  -

tensor([[-12.6438, -13.2250, -12.0964,  -7.2383,  -1.8626,   1.8031,  -9.3824,
         -18.5628, -16.4985,  -8.6381, -22.9652, -20.3323, -11.1498,  -9.1867,
         -15.8007, -11.6935, -14.6234,   9.7318,  -1.4018, -20.2794, -10.1510,
          -1.4459, -12.6446,  -9.0394, -19.4796, -18.3401, -17.4143, -11.3812,
         -10.8086, -21.3691]])
tensor([[-0.0510,  0.0760,  0.1313, -0.0838, -0.1711,  0.0751,  0.0096,  0.3334,
          0.0558,  0.3013,  0.1985,  0.2358,  0.1718,  0.1580,  0.2964, -0.1074,
          0.1225,  0.1912,  0.3769, -0.2127, -0.0058, -0.0060,  0.3452,  0.1117,
          0.1109, -0.0351,  0.2621, -0.0520,  0.0560,  0.1350]],
       grad_fn=<AddmmBackward0>)
i: 70
Mesh labels: [17]
tensor([[-12.2687, -12.3794, -11.0054,  -6.8599,  -1.9677,   1.5837,  -9.4217,
         -18.1577, -15.6965,  -8.2384, -22.2376, -20.2821, -11.4909,  -9.1650,
         -15.4076, -11.0496, -14.1956,   9.7812,  -1.0248, -20.0553,  -9.9837,
          -1.1009, -12.3787,  -8.4523, -18.8392, -1

tensor([[ -0.6630, -25.3520, -25.4249,  -7.2448,  -1.0887,  -5.9956,  -5.7658,
         -14.7797, -15.9355, -15.4019, -21.8196, -10.4475,  -0.5207,  -4.7572,
         -14.8713, -19.8283, -16.9259,  -7.4369,  -7.5848, -15.6882,   8.5823,
         -18.7633,  -9.7143, -15.1403, -22.0597,  -0.4845, -16.9781, -23.9592,
          -7.6400,  -9.5435]])
tensor([[-0.0653,  0.0600,  0.1334, -0.0615, -0.1910,  0.1087,  0.0234,  0.3324,
          0.0743,  0.2877,  0.2465,  0.2291,  0.1794,  0.1566,  0.2880, -0.0718,
          0.1577,  0.1965,  0.3835, -0.1955, -0.0277, -0.0016,  0.3748,  0.1036,
          0.1010, -0.0395,  0.2475, -0.0120,  0.0495,  0.1390]],
       grad_fn=<AddmmBackward0>)
i: 82
Mesh labels: [20]
tensor([[ -0.2029, -23.4657, -22.2695,  -7.0967,  -1.5486,  -5.3400,  -5.9871,
         -14.4164, -14.9560, -14.8427, -20.2788, -10.3520,  -1.3128,  -5.5571,
         -14.0156, -18.2934, -15.3243,  -5.0469,  -5.5837, -15.7396,   7.5348,
         -17.5353,  -9.8413, -12.8938, -20.4306,  -

tensor([[ -2.9784,  -4.4604,  -1.8961,  -9.3151, -17.1384,  -6.3612,  -4.1701,
          -7.2187, -20.3217, -11.6831,  -3.7824, -12.5407, -23.2622, -21.8246,
         -10.2428,  -0.1535,  -3.3852, -14.7988,  -3.6948, -18.7315, -21.2843,
         -15.8201, -33.0464,   7.7941, -18.8109, -19.5735, -29.5446, -10.3507,
          -2.9813, -21.2939]])
tensor([[-0.0586,  0.0276,  0.1510, -0.0013, -0.2228,  0.1483,  0.0329,  0.3361,
          0.1080,  0.2041,  0.3477,  0.1774,  0.1661,  0.2008,  0.2467, -0.0254,
          0.1977,  0.1902,  0.3736, -0.1911, -0.0558,  0.0581,  0.4345,  0.0781,
          0.1229, -0.0886,  0.2588,  0.0771,  0.0584,  0.1416]],
       grad_fn=<AddmmBackward0>)
i: 95
Mesh labels: [23]
tensor([[ -2.1636,  -5.2587,  -0.9725,  -8.3864, -15.1310,  -5.6785,  -4.3806,
          -7.5165, -18.6564, -11.3702,  -4.0861, -11.9357, -21.2485, -20.6205,
          -9.2940,  -0.4356,  -3.2191, -11.8320,  -1.3545, -18.3466, -18.7689,
         -14.9522, -30.3434,   7.8995, -17.5406, -1

tensor([[-20.4858, -14.5195, -17.9894,  -9.6578,  -5.7690, -12.8269,  -5.4880,
         -15.2435,  -5.2535,  -0.3668, -18.8117, -14.1828, -12.4093,   0.9912,
          -3.8652,  -9.0219, -24.8032, -17.0661, -15.1116,  -0.9258, -12.9558,
         -10.5589,  -1.9612, -19.6294, -11.6979,  -1.1449,   8.4558, -15.2649,
         -14.4261,  -5.6530]])
tensor([[-0.0633,  0.0552,  0.1291, -0.0338, -0.1993,  0.1275,  0.0121,  0.3169,
          0.0687,  0.2825,  0.2722,  0.2209,  0.1479,  0.1639,  0.3020, -0.0656,
          0.1707,  0.1996,  0.3845, -0.2005, -0.0131,  0.0275,  0.3882,  0.1038,
          0.1374, -0.0332,  0.2530,  0.0218,  0.0723,  0.1320]],
       grad_fn=<AddmmBackward0>)
i: 108
Mesh labels: [27]
tensor([[-1.3613e+01,  4.2414e+00, -1.5571e+01, -8.6816e+00, -1.8457e+01,
         -2.1858e+00, -4.5799e+00, -1.5762e-02, -2.0048e+01, -3.5250e+00,
         -1.3950e+01, -1.5606e+01, -2.1535e+01, -5.3531e+00, -1.5352e+01,
         -1.9129e+00, -1.2371e+01, -1.6341e+01, -1.7650e+01, -8.9

epoch: 3, loss: 1357.4270770549774
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[-0.0482,  0.0895,  0.1174, -0.0453, -0.1757,  0.0701, -0.0143,  0.3007,
          0.0238,  0.2963,  0.1862,  0.2321,  0.0879,  0.1881,  0.3173, -0.1434,
          0.1292,  0.2275,  0.3996, -0.2421,  0.0195,  0.0308,  0.3296,  0.0930,
          0.1776, -0.0288,  0.2947, -0.0220,  0.1306,  0.1308]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.75

tensor([[-14.8296, -18.9902, -28.8402, -15.5756, -15.2484, -11.4294,  -2.6644,
         -13.2581, -24.5787, -13.1838, -15.5056,  -8.6107, -15.0708, -15.5415,
         -12.3020, -13.9708, -18.9744, -28.3200, -21.5157,  -9.3443, -19.8563,
         -25.5049, -21.4479, -16.4845, -22.2518, -11.6252, -22.7750, -25.7483,
         -13.4401, -11.7617]])
tensor([[-0.0276,  0.1016,  0.1916, -0.0595, -0.1988,  0.1563,  0.0005,  0.3808,
          0.1109,  0.2774,  0.3342,  0.2427,  0.2266,  0.2230,  0.3025, -0.0497,
          0.1964,  0.1931,  0.3911, -0.2121, -0.0073,  0.0612,  0.4179,  0.1464,
          0.1601, -0.0354,  0.2952,  0.0584,  0.0851,  0.1951]],
       grad_fn=<AddmmBackward0>)
i: 27
Mesh labels: [6]
tensor([[-13.9090, -10.3987, -20.2173, -14.5899, -18.8993, -11.2420,  -2.4455,
          -9.3584, -21.5918, -10.7604,  -7.8127,  -8.2261, -19.0516, -18.0673,
          -8.9307,  -8.0612, -13.4881, -28.0867, -19.7504,  -7.6784, -23.4785,
         -23.5480, -23.4252, -10.9774, -16.5897, -14

tensor([[-28.4242,  -8.2474, -13.6672,  -8.3598, -13.4178, -15.0705,  -6.6848,
         -19.5868,  -9.2745,   2.4944, -16.3123, -23.3888, -29.2222, -11.4324,
          -6.3626,  -4.3604, -29.0648, -22.5601, -18.4032,  -6.6493, -27.5186,
         -11.1720, -10.5156, -19.5232, -12.9198, -14.4201,  -8.5507, -14.5739,
         -21.4568, -18.2314]])
tensor([[ 0.0145,  0.1224,  0.2096, -0.0577, -0.1943,  0.1334, -0.0087,  0.4006,
          0.1136,  0.2524,  0.3171,  0.2337,  0.2114,  0.2621,  0.3021, -0.0925,
          0.1879,  0.2217,  0.4086, -0.2595,  0.0073,  0.0785,  0.4014,  0.1509,
          0.1955, -0.0674,  0.3381,  0.0344,  0.1151,  0.1889]],
       grad_fn=<AddmmBackward0>)
i: 40
Mesh labels: [10]
tensor([[ -9.8054,  -3.0362,  -7.7672, -16.0421, -22.0341, -12.0270,  -2.7380,
          -6.8935, -11.8634, -10.3999,   5.5222,  -3.5391, -19.0065, -24.9962,
          -3.9015,  -6.5952,  -1.8166, -26.7677, -17.2053,  -4.8793, -22.5182,
         -27.6809, -20.6622,  -4.9033,  -3.8696, -1

tensor([[ -2.0639, -21.0047, -26.3009, -14.3487,  -3.9949,  -3.9108,  -4.9434,
          -8.5752, -18.5038, -16.3379, -15.8188,  -1.3279,   7.9913,  -5.9573,
         -11.9771, -19.0526,  -8.7847, -10.9553, -12.6672,  -8.5991,   0.3197,
         -19.4793,  -9.0652, -13.5403, -15.8815,  -2.6406, -14.9818, -22.8584,
          -2.1996,  -1.0117]])
tensor([[-0.0342,  0.0966,  0.1681,  0.0019, -0.1708,  0.1365, -0.0014,  0.3260,
          0.0701,  0.2689,  0.3035,  0.2324,  0.1284,  0.2266,  0.3019, -0.0913,
          0.1670,  0.2025,  0.3855, -0.2219, -0.0165,  0.0697,  0.3792,  0.0879,
          0.2083, -0.0509,  0.3019,  0.0713,  0.1354,  0.1704]],
       grad_fn=<AddmmBackward0>)
i: 52
Mesh labels: [13]
tensor([[-15.8641, -16.7311, -30.2572, -11.1232,  -7.8833,  -6.1485,  -5.6824,
          -9.0799, -18.5692,  -5.9895, -27.9221, -15.6250,  -9.1639,   6.2900,
         -16.3776, -13.1409, -25.0122, -17.8039, -19.6985,  -6.8510, -11.1158,
          -6.7717, -12.2290, -21.9364, -25.7201,  -

tensor([[-6.2986e+00, -1.4855e+01, -3.5309e+00, -8.1529e-01, -4.1161e+00,
         -6.1413e+00, -6.8259e+00, -1.7979e+01, -1.5671e+01, -1.0479e+01,
         -1.5762e+01, -2.0051e+01, -1.9114e+01, -1.5945e+01, -8.6165e+00,
         -4.9670e+00, -1.6503e+01,  1.3988e-02,  8.8768e+00, -2.3821e+01,
         -9.2150e+00, -1.0617e+01, -2.1571e+01,  8.9185e-01, -1.9702e+01,
         -1.3353e+01, -2.1542e+01, -1.5760e+01, -3.3180e+00, -2.1598e+01]])
tensor([[-0.0337,  0.1095,  0.1834, -0.0295, -0.1871,  0.1577,  0.0053,  0.3739,
          0.1096,  0.2978,  0.3384,  0.2776,  0.1993,  0.2507,  0.3174, -0.0635,
          0.2036,  0.2096,  0.3939, -0.2147, -0.0125,  0.0646,  0.3995,  0.1221,
          0.1865, -0.0455,  0.2992,  0.0712,  0.1204,  0.1983]],
       grad_fn=<AddmmBackward0>)
i: 73
Mesh labels: [18]
tensor([[ -6.4295, -14.6801,  -4.1200,  -0.1680,  -4.3292,  -6.5845,  -6.2795,
         -17.6786, -15.8085, -10.2893, -15.0795, -19.4315, -19.0610, -15.7840,
          -7.7838,  -4.5055, -1

i: 86
Mesh labels: [21]
tensor([[-16.7548,  -8.9297, -16.2944,  -1.9696,  -1.4119,   2.3184,  -6.9051,
         -14.3801, -21.2906,  -4.0274, -27.1826, -23.5177, -15.4157,  -1.2381,
         -18.4288,  -5.0259, -21.6452,   0.9273,  -6.7008, -19.1735, -15.5576,
           9.5294, -18.1917, -11.5982, -26.3427, -19.3207, -13.6973,  -2.3553,
         -19.2417, -27.7300]])
tensor([[-0.0344,  0.1094,  0.1864, -0.0196, -0.2017,  0.1737,  0.0105,  0.3768,
          0.1201,  0.2868,  0.3577,  0.2773,  0.1968,  0.2623,  0.3150, -0.0561,
          0.2273,  0.2302,  0.4156, -0.2185, -0.0122,  0.0748,  0.4102,  0.1185,
          0.1907, -0.0523,  0.2991,  0.0863,  0.1289,  0.2042]],
       grad_fn=<AddmmBackward0>)
i: 87
Mesh labels: [21]
tensor([[-17.1850,  -7.1073, -14.7938,  -1.7395,  -2.3789,   1.4221,  -6.6295,
         -13.9747, -20.0892,  -2.9650, -25.4700, -23.6302, -17.1402,  -1.8111,
         -17.4176,  -3.7117, -21.3280,  -0.1791,  -7.0395, -18.3350, -16.8462,
           9.6003, -18.4236

tensor([[-12.4871,   3.5003, -15.7322,  -7.8045, -17.2077,  -1.7667,  -4.4863,
           0.1399, -20.3842,  -4.1573, -14.3297, -15.1766, -19.9680,  -4.5139,
         -15.0436,  -1.9137, -12.2881, -15.4717, -16.3506,  -9.3267, -23.3840,
           0.3507, -23.5111,  -8.2575, -19.5659, -21.0511, -16.3006,   8.0806,
         -16.4551, -20.3073]])
tensor([[-0.0413,  0.1287,  0.1835, -0.0718, -0.1996,  0.1842, -0.0041,  0.4066,
          0.1314,  0.3663,  0.3401,  0.3323,  0.2291,  0.2440,  0.3634, -0.0546,
          0.2342,  0.2337,  0.4245, -0.2049,  0.0332,  0.0742,  0.4102,  0.1689,
          0.1885,  0.0076,  0.2879,  0.0500,  0.1239,  0.2206]],
       grad_fn=<AddmmBackward0>)
i: 111
Mesh labels: [27]
tensor([[-12.4931,   3.9019, -17.1043,  -8.3018, -17.7913,  -0.7667,  -4.3427,
           1.1484, -21.5301,  -4.0517, -15.5068, -15.2972, -20.0714,  -3.6038,
         -16.9691,  -2.2881, -12.2526, -15.4475, -17.6544,  -9.3804, -24.2639,
           1.8071, -24.0353,  -8.7565, -20.9167, -

tensor([[-1.1452e+01, -3.2160e+00,  9.4250e+00, -5.3613e+00, -9.1504e+00,
         -9.9146e+00, -6.1322e+00, -1.5043e+01,  5.1049e-01, -1.6524e+00,
         -2.1122e+00, -1.7273e+01, -2.3024e+01, -1.8343e+01, -2.1103e+00,
         -1.0108e+00, -9.7606e+00, -8.3661e+00, -1.9964e+00, -1.1714e+01,
         -1.6921e+01, -1.0647e+01, -1.3422e+01, -1.6649e-02, -4.1966e+00,
         -1.1970e+01, -1.4479e+01, -1.1983e+01, -5.3938e+00, -1.5116e+01]])
tensor([[ 0.0213,  0.1757,  0.1961, -0.0223, -0.1828,  0.1316, -0.0354,  0.3679,
          0.0836,  0.2880,  0.3079,  0.2901,  0.1317,  0.3249,  0.3537, -0.1408,
          0.2039,  0.2704,  0.4459, -0.2941,  0.0384,  0.1224,  0.3732,  0.1316,
          0.2980, -0.0529,  0.3806,  0.0780,  0.2291,  0.2185]],
       grad_fn=<AddmmBackward0>)
i: 12
Mesh labels: [3]
tensor([[-11.5600, -12.2807,  -8.4907,   4.3490,  -3.9629,  -6.6956,  -5.1210,
         -17.6667, -16.9735,  -6.5677, -17.3407, -22.6724, -22.5112, -12.0273,
          -9.3018,  -2.4722, -22

tensor([[-10.1052, -14.2137, -22.5353, -10.7191,  -5.8350,   2.6554,  -5.7042,
         -10.5656, -23.5730, -11.4148, -21.4100, -12.5334,  -6.3684,  -6.3531,
         -18.2538, -13.3801, -12.0193,  -3.4056, -11.6031, -14.8968, -11.6538,
          -5.9565, -17.2136, -11.8770, -23.4945, -16.5658, -19.6874, -11.6641,
         -12.9660, -17.5064]])
tensor([[ 0.0475,  0.1776,  0.2834, -0.0321, -0.2304,  0.2444, -0.0166,  0.4843,
          0.2132,  0.2545,  0.5177,  0.2996,  0.2949,  0.3844,  0.3312, -0.0118,
          0.3083,  0.2476,  0.4407, -0.2640,  0.0095,  0.1679,  0.4987,  0.2084,
          0.2693, -0.0750,  0.3793,  0.1802,  0.1777,  0.2894]],
       grad_fn=<AddmmBackward0>)
i: 24
Mesh labels: [6]
tensor([[-14.3651, -14.8762, -22.9706, -12.7757, -14.7615, -10.2669,  -2.8232,
         -13.2798, -22.8725, -11.4790, -13.6824, -11.5731, -18.6450, -16.5624,
         -12.0000, -10.6746, -17.3770, -25.1404, -18.2897, -11.7565, -20.6592,
         -21.6479, -23.4197, -12.6670, -21.4061, -13

tensor([[-28.2933,  -6.9372, -13.3747,  -8.7327, -14.9363, -14.7372,  -6.1365,
         -18.7543, -10.6964,   2.4259, -15.2139, -23.4355, -30.9123, -12.7658,
          -7.0781,  -3.3580, -28.0868, -23.9294, -19.2813,  -7.0621, -29.3227,
         -11.2821, -13.1027, -18.4917, -13.6305, -16.1520, -10.9182, -13.8807,
         -21.9799, -19.6408]])
tensor([[ 0.0154,  0.1619,  0.2555,  0.0131, -0.1984,  0.2404, -0.0144,  0.4275,
          0.1620,  0.2653,  0.4693,  0.2900,  0.2245,  0.3475,  0.3340, -0.0268,
          0.2734,  0.2330,  0.4241, -0.2418, -0.0027,  0.1540,  0.4628,  0.1560,
          0.2789, -0.0563,  0.3554,  0.1858,  0.1935,  0.2634]],
       grad_fn=<AddmmBackward0>)
i: 37
Mesh labels: [9]
tensor([[-29.1347,  -9.4924, -16.0189,  -9.4573, -13.4579, -15.4269,  -6.5397,
         -19.6941,  -8.3137,   2.6010, -17.7947, -23.4021, -28.5215,  -9.8967,
          -7.0387,  -6.5830, -30.2071, -23.8775, -20.4006,  -5.4568, -26.5881,
         -12.0794,  -9.2626, -22.0024, -13.3017, -12

tensor([[ -3.2944, -21.3041, -26.1382, -13.8697,  -3.2115,  -3.7217,  -5.3201,
          -9.9961, -18.0025, -15.4822, -17.2332,  -2.9626,   7.4967,  -5.2281,
         -12.2308, -19.1271, -10.1265,  -9.5373, -12.3120,  -9.0514,   0.3120,
         -18.1385,  -8.3750, -14.4281, -16.2261,  -2.9153, -13.8856, -22.6859,
          -3.1677,  -1.9360]])
tensor([[ 0.0297,  0.1983,  0.2530, -0.0487, -0.1769,  0.1911, -0.0257,  0.4543,
          0.1539,  0.3488,  0.3846,  0.3495,  0.2349,  0.3383,  0.3715, -0.0953,
          0.2450,  0.2638,  0.4500, -0.2629,  0.0459,  0.1230,  0.4078,  0.1828,
          0.2736, -0.0273,  0.3706,  0.0847,  0.2019,  0.2637]],
       grad_fn=<AddmmBackward0>)
i: 50
Mesh labels: [12]
tensor([[ -2.8249, -21.0237, -26.2058, -14.5356,  -3.7369,  -3.6951,  -5.4744,
          -9.4119, -18.0851, -15.9133, -16.7078,  -2.3254,   7.9845,  -5.5532,
         -12.3345, -19.4005,  -9.1648,  -9.8226, -12.6477,  -8.8802,   0.1954,
         -18.7192,  -8.4656, -14.1634, -15.8359,  -

tensor([[-13.5558,  -5.7115,  -8.9670,  -4.8370, -14.3079, -10.1167,  -3.0017,
         -10.8677, -17.7850,  -5.0375,  -7.2967, -14.0767, -23.6237, -15.2642,
          -5.4349,   2.0814, -15.8247, -20.4009, -10.2259, -11.5918, -22.9732,
         -12.6988, -24.7677,  -4.2275, -16.1622, -15.1901, -19.3203, -11.2651,
          -9.5939, -17.0225]])
tensor([[-0.0012,  0.1996,  0.2477, -0.0543, -0.1706,  0.2091, -0.0151,  0.4495,
          0.1566,  0.3830,  0.3941,  0.3886,  0.2692,  0.3313,  0.3852, -0.0779,
          0.2477,  0.2438,  0.4399, -0.2317,  0.0392,  0.1110,  0.4102,  0.1793,
          0.2606, -0.0041,  0.3468,  0.1035,  0.1868,  0.2844]],
       grad_fn=<AddmmBackward0>)
i: 63
Mesh labels: [15]
tensor([[-12.0241,  -3.0130,  -5.0491,  -3.4126, -15.0483,  -9.0908,  -2.9785,
          -9.7593, -18.4441,  -4.5903,  -6.3532, -15.9996, -26.5992, -16.1671,
          -6.4976,   5.0000, -14.4507, -19.2171,  -7.9984, -14.2017, -24.5600,
         -10.1221, -28.6235,  -0.1991, -17.6270, -1

tensor([[-24.1717, -11.1630, -23.9647, -18.4104, -16.9953, -15.0570,  -4.8745,
         -12.1350, -11.8412,  -4.0405, -11.2920,  -9.0411, -16.1607, -11.2677,
          -4.5028, -12.6259, -20.6682, -29.0327, -26.2487,   4.0097, -23.4977,
         -23.0184,  -5.2591, -23.6639,  -7.2481,  -9.6458,  -6.8159, -21.0551,
         -14.9547,  -2.0474]])
tensor([[ 0.0423,  0.2069,  0.2752, -0.0143, -0.2004,  0.2321, -0.0146,  0.4734,
          0.1933,  0.3096,  0.4749,  0.3646,  0.2621,  0.4104,  0.3689, -0.0615,
          0.3047,  0.2868,  0.4655, -0.2826,  0.0204,  0.1568,  0.4491,  0.1801,
          0.3052, -0.0702,  0.3901,  0.1550,  0.2259,  0.2926]],
       grad_fn=<AddmmBackward0>)
i: 77
Mesh labels: [19]
tensor([[-19.6895, -13.3330, -21.7469, -16.5643, -14.4257, -14.2412,  -3.9656,
         -13.1249, -11.6196,  -6.5693,  -9.4384,  -7.3154, -13.9094, -13.4050,
          -4.3209, -13.2439, -17.6287, -26.4731, -22.2221,   0.7675, -19.1140,
         -24.7464,  -7.0097, -19.9355,  -7.7924,  -

tensor([[-21.2384, -18.9784, -18.9435, -14.0430,  -5.6121, -15.6072,  -7.5156,
         -21.7006,  -2.0901,  -3.5385, -15.3556, -11.6082,  -9.1916,  -8.4153,
          -3.5637, -17.0077, -23.0643, -17.1053, -17.4319,  -1.0247, -10.6441,
         -21.1512,   7.3846, -24.3821,  -5.0300,  -1.0686,  -1.1796, -28.0118,
         -12.1593,  -1.7483]])
tensor([[ 0.0115,  0.2007,  0.2663, -0.0272, -0.2083,  0.2636, -0.0081,  0.4787,
          0.2025,  0.3455,  0.4797,  0.3918,  0.2796,  0.3875,  0.3814, -0.0332,
          0.3226,  0.2846,  0.4739, -0.2457,  0.0351,  0.1607,  0.4552,  0.1823,
          0.2825, -0.0344,  0.3551,  0.1629,  0.2115,  0.3092]],
       grad_fn=<AddmmBackward0>)
i: 91
Mesh labels: [22]
tensor([[-19.7221, -15.5854, -17.9892, -14.3624,  -6.0767, -12.6194,  -6.9817,
         -18.7134,  -2.9708,  -3.5812, -12.9662,  -9.7586,  -8.1016,  -8.9465,
          -4.0923, -16.1150, -18.6699, -14.5984, -17.4491,  -0.1482, -11.0058,
         -19.1694,   7.2803, -22.4665,  -3.3822,  -

tensor([[-11.3650, -25.5086, -23.8257,  -9.8779,  -2.8680, -14.9700,  -4.6951,
         -18.6867,  -7.7704,  -8.8725, -18.9919,  -9.7815,  -5.2168,  -4.0773,
          -7.1178, -16.8865, -23.2980, -19.4247, -13.4267,  -7.0261,  -1.6310,
         -22.3703,  -4.7941, -19.6495, -16.0471,   7.0702,  -4.1602, -28.6626,
         -10.3997,  -2.9798]])
tensor([[ 0.0640,  0.2335,  0.2963, -0.0523, -0.2243,  0.2680, -0.0233,  0.5281,
          0.2386,  0.3416,  0.5120,  0.4073,  0.3099,  0.4393,  0.4029, -0.0496,
          0.3505,  0.3234,  0.5041, -0.2957,  0.0693,  0.1925,  0.4837,  0.2410,
          0.3211, -0.0579,  0.3974,  0.1484,  0.2341,  0.3215]],
       grad_fn=<AddmmBackward0>)
i: 103
Mesh labels: [25]
tensor([[-14.3204, -22.8477, -19.3216,  -8.9437,  -4.2516, -16.6635,  -5.2487,
         -20.2665,  -4.2940,  -5.9561, -17.7130, -13.0189, -10.2812,  -5.3670,
          -5.5154, -14.8676, -24.8720, -20.1338, -12.8372,  -6.9348,  -4.8901,
         -21.1873,  -4.6956, -19.3544, -13.7973,  

epoch: 5, loss: 1273.1993638565764
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[ 0.0054,  0.2440,  0.2417, -0.0474, -0.1723,  0.2064, -0.0439,  0.4387,
          0.1316,  0.4197,  0.3682,  0.4283,  0.2129,  0.3691,  0.4418, -0.1188,
          0.2716,  0.3002,  0.4893, -0.2681,  0.0916,  0.1459,  0.3928,  0.1916,
          0.3371,  0.0298,  0.3911,  0.1130,  0.2714,  0.2958]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.75

tensor([[ -8.0546, -12.1559, -23.1261, -12.1339,  -8.8520,   2.9655,  -5.1956,
          -6.8945, -25.2035, -12.2482, -19.4478, -10.3294,  -6.5645,  -6.8545,
         -19.3177, -12.8218,  -8.9400,  -6.4201, -13.6256, -14.1283, -13.2635,
          -7.0109, -19.9829, -10.3481, -24.0905, -17.6628, -21.7641,  -9.2595,
         -12.8801, -17.3745]])
tensor([[ 0.0963,  0.3062,  0.3596, -0.0485, -0.2139,  0.3031, -0.0532,  0.5661,
          0.2557,  0.3666,  0.5720,  0.4474,  0.3525,  0.4974,  0.4383, -0.0403,
          0.3786,  0.3209,  0.5171, -0.3046,  0.0888,  0.2256,  0.5029,  0.2795,
          0.3823, -0.0202,  0.4572,  0.2218,  0.2931,  0.3879]],
       grad_fn=<AddmmBackward0>)
i: 22
Mesh labels: [5]
tensor([[ -9.1728, -12.1504, -21.6671, -10.1149,  -6.2599,   3.3546,  -5.6768,
          -8.6273, -23.1617, -10.5796, -21.3516, -12.7094,  -6.6412,  -4.6775,
         -18.9983, -12.1906, -11.0990,  -3.2922, -11.6404, -14.7161, -11.6030,
          -3.6861, -17.5273, -10.8596, -23.8591, -16

tensor([[-19.5553,  -9.0141,   0.4047,  -7.3339,  -8.1700, -16.3926,  -7.2686,
         -21.7274,   6.5232,  -0.0488,  -5.9658, -17.7499, -21.4305, -16.0496,
          -0.1440,  -8.5923, -19.3170, -15.4958,  -9.0545,  -6.1904, -15.2726,
         -17.1233,  -1.7141, -13.4231,   0.0432,  -5.3454,  -7.0391, -20.7602,
         -10.1149,  -8.9351]])
tensor([[ 6.5443e-02,  2.9087e-01,  3.6177e-01, -3.6725e-02, -2.0108e-01,
          3.4585e-01, -4.1654e-02,  5.7271e-01,  2.6032e-01,  3.9222e-01,
          5.9162e-01,  4.5904e-01,  3.7201e-01,  4.6748e-01,  4.3877e-01,
          3.9501e-04,  3.8415e-01,  2.9628e-01,  4.9845e-01, -2.5813e-01,
          7.5909e-02,  2.1514e-01,  5.1288e-01,  2.7477e-01,  3.5271e-01,
          8.8995e-03,  4.1951e-01,  2.4049e-01,  2.6889e-01,  3.9356e-01]],
       grad_fn=<AddmmBackward0>)
i: 35
Mesh labels: [8]
tensor([[-1.7106e+01, -7.9029e+00,  3.0505e+00, -7.1686e+00, -8.2045e+00,
         -1.4928e+01, -7.2167e+00, -2.0442e+01,  5.7832e+00, -1.0524e+00,
   

tensor([[ -2.6931, -18.4670, -30.7381, -21.3479, -15.9281,  -7.0441,  -2.5440,
          -2.5455, -25.0249, -19.4351,  -8.5030,   5.6621,   1.6988, -13.7873,
         -12.1763, -18.8024,  -3.8106, -25.8824, -22.2376,  -4.2626, -11.1032,
         -30.0106, -17.9421, -12.6658, -16.8919,  -6.9994, -23.4696, -24.8537,
          -3.5843,   0.6504]])
tensor([[ 0.0982,  0.3043,  0.3709,  0.0029, -0.1881,  0.3396, -0.0474,  0.5629,
          0.2718,  0.3546,  0.6160,  0.4385,  0.3196,  0.5189,  0.4332, -0.0292,
          0.3832,  0.3137,  0.5090, -0.3004,  0.0653,  0.2539,  0.5097,  0.2480,
          0.4228, -0.0381,  0.4545,  0.2711,  0.3188,  0.3964]],
       grad_fn=<AddmmBackward0>)
i: 46
Mesh labels: [11]
tensor([[ -5.1981, -17.0249, -31.0923, -21.8705, -19.3145,  -8.5461,  -1.3353,
          -2.6037, -25.6356, -18.1405,  -7.1999,   5.3960,  -3.4527, -15.7456,
         -12.1256, -17.2593,  -4.6006, -30.4048, -24.7604,  -3.2078, -15.8416,
         -31.4539, -20.3277, -13.1523, -17.3869,  -

i: 58
Mesh labels: [14]
tensor([[-20.3809, -13.3521, -10.1346, -11.6553, -13.3656, -19.2275,  -5.9840,
         -20.2482,  -6.5062,  -6.6484,  -4.9090, -11.8888, -19.6884, -20.8907,
           3.5689,  -8.4722, -19.5445, -23.8601, -13.2722,  -4.5353, -19.6709,
         -27.9231, -10.0866, -14.3799,  -2.6616,  -7.7665, -12.2356, -28.6508,
          -4.5376,  -3.2128]])
tensor([[ 0.0095,  0.2895,  0.3386, -0.0543, -0.1717,  0.3400, -0.0225,  0.5545,
          0.2513,  0.4812,  0.5543,  0.5282,  0.3868,  0.4246,  0.4602, -0.0116,
          0.3597,  0.2738,  0.4870, -0.2068,  0.0760,  0.1792,  0.4811,  0.2523,
          0.3282,  0.0595,  0.3763,  0.2162,  0.2463,  0.4076]],
       grad_fn=<AddmmBackward0>)
i: 59
Mesh labels: [14]
tensor([[-20.5121, -10.8599,  -7.5975, -11.9631, -13.1542, -18.6488,  -6.4280,
         -20.0937,  -4.2401,  -6.0960,  -2.7362, -11.5782, -19.2985, -22.1444,
           4.0644,  -8.5918, -17.2663, -21.8911, -12.9144,  -3.9298, -19.6721,
         -27.1996,  -7.6258

tensor([[-12.2687, -12.3794, -11.0054,  -6.8599,  -1.9677,   1.5837,  -9.4217,
         -18.1577, -15.6965,  -8.2384, -22.2376, -20.2821, -11.4909,  -9.1650,
         -15.4076, -11.0496, -14.1956,   9.7812,  -1.0248, -20.0553,  -9.9837,
          -1.1009, -12.3787,  -8.4523, -18.8392, -18.1488, -17.0252, -10.6071,
         -10.4759, -21.2388]])
tensor([[ 0.0992,  0.3414,  0.3737, -0.0324, -0.1763,  0.3086, -0.0483,  0.5817,
          0.2651,  0.4201,  0.5685,  0.5232,  0.3588,  0.5440,  0.4742, -0.0698,
          0.3828,  0.3378,  0.5323, -0.3136,  0.0936,  0.2288,  0.4727,  0.2625,
          0.4257, -0.0199,  0.4730,  0.2167,  0.3332,  0.4114]],
       grad_fn=<AddmmBackward0>)
i: 71
Mesh labels: [17]
tensor([[-11.8748, -12.4198, -10.1863,  -7.0423,  -2.3060,   0.9893,  -9.2045,
         -18.1749, -14.9915,  -8.3809, -21.1256, -19.9540, -11.8130,  -9.8971,
         -14.5896, -10.9697, -13.8232,   9.1062,  -0.7848, -19.7840,  -9.8210,
          -2.3611, -12.4612,  -7.9398, -18.0150, -1

tensor([[ -1.4082, -28.8877, -28.5914,  -8.7979,  -0.5778,  -6.2760,  -6.5575,
         -17.1247, -18.6616, -17.6456, -24.6916, -11.3942,   0.3745,  -5.6796,
         -16.3208, -22.4247, -18.7492,  -7.5498,  -8.1130, -17.7063,   8.6472,
         -20.7969, -10.7878, -16.7375, -24.6021,  -1.1031, -18.7841, -27.7896,
          -7.6476, -10.3044]])
tensor([[ 0.0286,  0.3325,  0.3611, -0.0974, -0.1902,  0.3449, -0.0244,  0.6062,
          0.2737,  0.5308,  0.5424,  0.5942,  0.4414,  0.4596,  0.5067, -0.0228,
          0.4121,  0.3373,  0.5521, -0.2339,  0.1126,  0.1690,  0.4736,  0.2952,
          0.3286,  0.0788,  0.4024,  0.1716,  0.2632,  0.4323]],
       grad_fn=<AddmmBackward0>)
i: 84
Mesh labels: [21]
tensor([[-16.9386,  -6.8993, -13.9714,  -2.1039,  -2.3359,   1.2923,  -6.6079,
         -13.9512, -18.7974,  -2.7846, -24.4515, -23.0021, -16.5929,  -2.0839,
         -16.8218,  -4.0640, -20.5056,   0.1491,  -6.9824, -17.5369, -16.2591,
           8.9416, -17.2292, -10.9651, -23.5076, -1

i: 95
Mesh labels: [23]
tensor([[ -2.1636,  -5.2587,  -0.9725,  -8.3864, -15.1310,  -5.6785,  -4.3806,
          -7.5165, -18.6564, -11.3702,  -4.0861, -11.9357, -21.2485, -20.6205,
          -9.2940,  -0.4356,  -3.2191, -11.8320,  -1.3545, -18.3466, -18.7689,
         -14.9522, -30.3434,   7.8995, -17.5406, -17.9177, -27.2242, -10.5234,
          -1.8716, -19.8468]])
tensor([[ 0.0548,  0.3260,  0.3690, -0.0183, -0.2037,  0.3912, -0.0347,  0.5842,
          0.2898,  0.4422,  0.6325,  0.5499,  0.3768,  0.5304,  0.4860,  0.0012,
          0.4422,  0.3530,  0.5516, -0.2678,  0.1003,  0.2575,  0.5216,  0.2639,
          0.4062,  0.0133,  0.4234,  0.2793,  0.3213,  0.4385]],
       grad_fn=<AddmmBackward0>)
i: 96
Mesh labels: [24]
tensor([[-18.2338,  -4.1690,  -1.2760, -13.5267, -14.3659, -16.9434,  -6.1945,
         -16.4325,   4.5690,  -3.8176,   3.4355,  -8.8179, -18.3510, -23.0060,
           3.0834,  -9.7005, -10.0162, -20.3767, -13.8767,  -0.7932, -18.5388,
         -25.3163,  -2.1837

tensor([[-13.3109, -17.6586, -22.6130, -18.1277, -13.3338, -13.9144,  -5.0583,
         -12.6665, -15.2249, -13.3974,  -7.8443,  -2.6484,  -5.6877, -16.2637,
          -2.4342, -15.8707, -13.2478, -23.3710, -17.6797,  -1.9487, -13.5214,
         -30.4678,  -9.6489, -16.5979,  -7.3042,  -5.9155, -14.2448, -29.4232,
          -1.7010,   3.4217]])
tensor([[ 0.1218,  0.3975,  0.4407, -0.0357, -0.2347,  0.4589, -0.0670,  0.6849,
          0.3850,  0.4381,  0.7856,  0.5970,  0.4544,  0.6505,  0.5376,  0.0354,
          0.5318,  0.3949,  0.5912, -0.3241,  0.1402,  0.3318,  0.6026,  0.3720,
          0.5002,  0.0090,  0.5135,  0.3698,  0.3830,  0.5053]],
       grad_fn=<AddmmBackward0>)
i: 118
Mesh labels: [29]
tensor([[-17.6607, -15.2465, -24.5638, -20.3559, -15.6175, -14.5888,  -4.1492,
         -11.7338, -12.3722,  -9.7181,  -6.7731,  -1.8053,  -8.1024, -15.5580,
          -3.1293, -16.6138, -14.1054, -27.8091, -24.2799,   3.3553, -17.3860,
         -30.3973,  -4.9050, -21.1453,  -4.7528,  

tensor([[-11.9561,  -3.6169,   9.8330,  -5.1245,  -9.3670, -10.3876,  -6.3704,
         -15.9329,   0.0346,  -1.7833,  -2.4940, -18.4598, -24.3406, -19.0501,
          -2.1623,  -0.7345, -10.5178,  -8.6913,  -1.6925, -12.7091, -17.6588,
         -10.9144, -14.6821,   0.2514,  -4.9962, -12.5126, -15.2978, -12.5168,
          -5.6111, -16.2461]])
tensor([[ 8.3660e-02,  3.8914e-01,  3.8979e-01, -1.5060e-02, -1.9893e-01,
          4.1713e-01, -6.9846e-02,  6.0102e-01,  3.0331e-01,  4.7083e-01,
          6.8330e-01,  5.8709e-01,  3.7434e-01,  5.8598e-01,  5.4038e-01,
          2.9165e-04,  4.6640e-01,  3.6050e-01,  5.6582e-01, -2.8131e-01,
          1.2946e-01,  2.9854e-01,  5.3981e-01,  3.1058e-01,  4.9521e-01,
          5.0322e-02,  4.8127e-01,  3.5894e-01,  4.0155e-01,  4.9223e-01]],
       grad_fn=<AddmmBackward0>)
i: 10
Mesh labels: [2]
tensor([[-10.9553,  -3.3222,   9.1418,  -4.5795,  -8.6886,  -9.1763,  -5.9624,
         -14.7096,  -0.7934,  -1.9389,  -2.6520, -17.6002, -22.9457, -17

tensor([[-10.1052, -14.2137, -22.5353, -10.7191,  -5.8350,   2.6554,  -5.7042,
         -10.5656, -23.5730, -11.4148, -21.4100, -12.5334,  -6.3684,  -6.3531,
         -18.2538, -13.3801, -12.0193,  -3.4056, -11.6031, -14.8968, -11.6538,
          -5.9565, -17.2136, -11.8770, -23.4945, -16.5658, -19.6874, -11.6641,
         -12.9660, -17.5064]])
tensor([[ 0.0961,  0.4288,  0.4472, -0.0305, -0.1791,  0.4324, -0.0708,  0.6369,
          0.3112,  0.5175,  0.6846,  0.6280,  0.4363,  0.5842,  0.5611,  0.0022,
          0.4737,  0.3631,  0.5809, -0.2707,  0.1488,  0.2883,  0.5388,  0.3432,
          0.4848,  0.0873,  0.4901,  0.3339,  0.3915,  0.5171]],
       grad_fn=<AddmmBackward0>)
i: 24
Mesh labels: [6]
tensor([[-14.3651, -14.8762, -22.9706, -12.7757, -14.7615, -10.2669,  -2.8232,
         -13.2798, -22.8725, -11.4790, -13.6824, -11.5731, -18.6450, -16.5624,
         -12.0000, -10.6746, -17.3770, -25.1404, -18.2897, -11.7565, -20.6592,
         -21.6479, -23.4197, -12.6670, -21.4061, -13

tensor([[-11.6718,  -2.5958,  -7.4301, -17.4365, -22.3056, -12.8318,  -3.5272,
          -7.7282,  -8.9709,  -9.8538,   6.2881,  -3.5478, -18.7555, -25.7640,
          -2.9329,  -8.6665,  -1.8150, -26.8913, -18.5183,  -3.0664, -22.5987,
         -29.0522, -17.2185,  -7.3923,  -0.4747, -14.0919, -24.0024, -20.0172,
          -3.5677,  -3.6322]])
tensor([[ 0.1319,  0.4712,  0.4878, -0.0556, -0.1607,  0.4465, -0.0768,  0.7057,
          0.3500,  0.5585,  0.6814,  0.6705,  0.4781,  0.6160,  0.5897, -0.0235,
          0.4862,  0.3909,  0.6097, -0.2948,  0.1785,  0.2992,  0.5309,  0.3771,
          0.5086,  0.0947,  0.5217,  0.3004,  0.4103,  0.5433]],
       grad_fn=<AddmmBackward0>)
i: 43
Mesh labels: [10]
tensor([[-10.7335,  -0.9883,  -5.9118, -16.8425, -23.7691, -12.3235,  -3.3852,
          -6.6129, -10.4517,  -9.9265,   6.6998,  -4.5129, -20.9599, -26.4770,
          -3.8285,  -6.6393,  -0.8745, -27.1926, -17.8756,  -4.7551, -24.2907,
         -27.9905, -21.0365,  -4.9740,  -2.2693, -1

tensor([[-13.8156, -12.8400, -23.8924,  -9.2676,  -7.2072,  -5.5136,  -4.7157,
          -7.4916, -14.0714,  -3.9144, -22.4206, -13.1019,  -8.7493,   5.0935,
         -12.8874, -10.2377, -20.8854, -15.0960, -16.5194,  -4.8228, -10.2136,
          -5.1903,  -9.4925, -18.2005, -20.1399,  -5.3534,  -0.6626,  -6.9383,
         -17.4111, -10.8901]])
tensor([[ 0.2036,  0.5138,  0.5548,  0.0157, -0.1732,  0.5137, -0.0894,  0.7493,
          0.4300,  0.4739,  0.8711,  0.6820,  0.4971,  0.7614,  0.5790,  0.0039,
          0.5566,  0.4280,  0.6256, -0.3651,  0.1537,  0.3865,  0.6059,  0.3883,
          0.6176, -0.0068,  0.5959,  0.4433,  0.4866,  0.5952]],
       grad_fn=<AddmmBackward0>)
i: 55
Mesh labels: [13]
tensor([[-14.7091, -18.4965, -29.1599, -10.0573,  -4.9917,  -5.9170,  -5.3289,
         -10.4114, -17.2106,  -6.2029, -27.3137, -14.5589,  -6.6187,   6.1483,
         -15.1838, -13.4674, -24.3929, -15.6845, -17.5054,  -7.2159,  -8.2009,
          -7.0815, -10.0279, -21.1741, -24.5894,  -

tensor([[-19.6895, -13.3330, -21.7469, -16.5643, -14.4257, -14.2412,  -3.9656,
         -13.1249, -11.6196,  -6.5693,  -9.4384,  -7.3154, -13.9094, -13.4050,
          -4.3209, -13.2439, -17.6287, -26.4731, -22.2221,   0.7675, -19.1140,
         -24.7464,  -7.0097, -19.9355,  -7.7924,  -7.4343, -10.4261, -23.9919,
         -11.5682,  -2.0952]])
tensor([[ 0.1841,  0.5300,  0.5669,  0.0065, -0.1965,  0.5681, -0.0780,  0.7861,
          0.4666,  0.5256,  0.9223,  0.7559,  0.5668,  0.7987,  0.6239,  0.0606,
          0.6317,  0.4617,  0.6595, -0.3457,  0.1558,  0.3789,  0.6287,  0.4158,
          0.5997,  0.0202,  0.5797,  0.4694,  0.4867,  0.6300]],
       grad_fn=<AddmmBackward0>)
i: 78
Mesh labels: [19]
tensor([[-21.2945,  -7.2062, -17.4864, -14.4381, -18.3967, -14.2245,  -4.0122,
         -11.4920, -13.2905,  -4.4765,  -6.9536, -10.5047, -21.0116, -15.6383,
          -3.6983,  -7.3272, -17.5250, -28.0222, -21.8283,  -0.7592, -25.3609,
         -21.6698, -13.2082, -16.6473,  -8.0752, -1

tensor([[-21.8248, -15.1292, -15.4215, -13.5570,  -6.3741, -14.9675,  -7.6623,
         -21.0492,  -0.1989,  -2.2009, -12.4088, -11.9550, -11.2910, -10.2320,
          -2.9593, -15.5360, -20.9877, -16.1200, -17.2124,  -0.5606, -12.3409,
         -19.7366,   8.4618, -23.1250,  -2.1550,  -3.5720,  -2.3702, -25.6527,
         -12.1592,  -2.6778]])
tensor([[ 0.0949,  0.4962,  0.4873, -0.0667, -0.1717,  0.4836, -0.0607,  0.7262,
          0.3636,  0.6604,  0.6940,  0.7916,  0.5273,  0.6394,  0.6511, -0.0096,
          0.5481,  0.4444,  0.6721, -0.2645,  0.2165,  0.2925,  0.5158,  0.3818,
          0.5027,  0.1470,  0.5035,  0.2908,  0.4270,  0.5778]],
       grad_fn=<AddmmBackward0>)
i: 90
Mesh labels: [22]
tensor([[-21.2384, -18.9784, -18.9435, -14.0430,  -5.6121, -15.6072,  -7.5156,
         -21.7006,  -2.0901,  -3.5385, -15.3556, -11.6082,  -9.1916,  -8.4153,
          -3.5637, -17.0077, -23.0643, -17.1053, -17.4319,  -1.0247, -10.6441,
         -21.1512,   7.3846, -24.3821,  -5.0300,  -

i: 101
Mesh labels: [25]
tensor([[-12.8098, -23.2901, -20.9864,  -9.1904,  -3.2161, -15.2389,  -4.7031,
         -18.8213,  -5.7028,  -6.9229, -17.6228, -10.7221,  -7.1677,  -4.3441,
          -5.7731, -15.3477, -23.2659, -19.0057, -12.8664,  -6.1625,  -3.2857,
         -20.8899,  -3.9397, -19.1224, -13.9923,   6.3211,  -2.6422, -26.9842,
         -10.7021,  -3.2771]])
tensor([[ 0.2349,  0.5876,  0.6155, -0.0014, -0.2236,  0.6439, -0.1005,  0.8533,
          0.5358,  0.5348,  1.0177,  0.8099,  0.6076,  0.8881,  0.6770,  0.0814,
          0.7119,  0.5360,  0.7298, -0.3890,  0.2264,  0.4684,  0.6977,  0.4985,
          0.6739,  0.0081,  0.6178,  0.5161,  0.5428,  0.6800]],
       grad_fn=<AddmmBackward0>)
i: 102
Mesh labels: [25]
tensor([[-11.3650, -25.5086, -23.8257,  -9.8779,  -2.8680, -14.9700,  -4.6951,
         -18.6867,  -7.7704,  -8.8725, -18.9919,  -9.7815,  -5.2168,  -4.0773,
          -7.1178, -16.8865, -23.2980, -19.4247, -13.4267,  -7.0261,  -1.6310,
         -22.3703,  -4.79

epoch: 7, loss: 1094.695028834045
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[ 0.1568,  0.5880,  0.5450, -0.0244, -0.1666,  0.5417, -0.1153,  0.7512,
          0.4007,  0.6313,  0.8159,  0.8230,  0.5033,  0.7781,  0.7188, -0.0191,
          0.6024,  0.4895,  0.7111, -0.3455,  0.2597,  0.4075,  0.5820,  0.4398,
          0.6863,  0.1406,  0.6219,  0.4380,  0.5646,  0.6461]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.752

tensor([[-14.3651, -14.8762, -22.9706, -12.7757, -14.7615, -10.2669,  -2.8232,
         -13.2798, -22.8725, -11.4790, -13.6824, -11.5731, -18.6450, -16.5624,
         -12.0000, -10.6746, -17.3770, -25.1404, -18.2897, -11.7565, -20.6592,
         -21.6479, -23.4197, -12.6670, -21.4061, -13.9554, -23.9975, -21.7086,
         -13.0442, -15.4077]])
tensor([[ 0.2467,  0.7072,  0.6968, -0.0221, -0.1707,  0.6733, -0.1325,  0.8880,
          0.5165,  0.6728,  1.0019,  0.9188,  0.6764,  0.8866,  0.7736,  0.0645,
          0.7164,  0.5237,  0.7594, -0.3456,  0.2889,  0.4629,  0.6740,  0.5600,
          0.7275,  0.1636,  0.6819,  0.5395,  0.6050,  0.7709]],
       grad_fn=<AddmmBackward0>)
i: 25
Mesh labels: [6]
tensor([[-14.5027, -13.2319, -21.4615, -12.8570, -17.1793, -11.6074,  -2.7180,
         -12.7763, -23.4383, -11.8774, -11.1201, -11.7537, -21.2265, -19.1802,
         -10.7729,  -9.0745, -16.8068, -27.7212, -18.5842, -12.0273, -22.8469,
         -23.7130, -26.2228, -11.3570, -20.5803, -15

tensor([[-29.1347,  -9.4924, -16.0189,  -9.4573, -13.4579, -15.4269,  -6.5397,
         -19.6941,  -8.3137,   2.6010, -17.7947, -23.4021, -28.5215,  -9.8967,
          -7.0387,  -6.5830, -30.2071, -23.8775, -20.4006,  -5.4568, -26.5881,
         -12.0794,  -9.2626, -22.0024, -13.3017, -12.8041,  -6.7129, -15.4340,
         -22.9944, -17.2665]])
tensor([[ 0.2913,  0.7362,  0.7344,  0.0335, -0.1437,  0.7141, -0.1471,  0.9089,
          0.5399,  0.6233,  1.0521,  0.9066,  0.6476,  0.9540,  0.7779,  0.0590,
          0.7277,  0.5452,  0.7673, -0.3910,  0.2803,  0.5106,  0.6850,  0.5487,
          0.8045,  0.1173,  0.7223,  0.6006,  0.6646,  0.7835]],
       grad_fn=<AddmmBackward0>)
i: 38
Mesh labels: [9]
tensor([[-26.9754,  -9.1055, -11.6346,  -6.0669, -11.5090, -14.4946,  -6.7320,
         -20.5614,  -9.8262,   2.1387, -16.3481, -24.1510, -28.9189, -11.5371,
          -5.3347,  -2.8517, -28.9497, -20.0269, -15.0855,  -8.7562, -25.8955,
         -10.0486, -12.0381, -17.0934, -13.8759, -14

tensor([[ -2.0639, -21.0047, -26.3009, -14.3487,  -3.9949,  -3.9108,  -4.9434,
          -8.5752, -18.5038, -16.3379, -15.8188,  -1.3279,   7.9913,  -5.9573,
         -11.9771, -19.0526,  -8.7847, -10.9553, -12.6672,  -8.5991,   0.3197,
         -19.4793,  -9.0652, -13.5403, -15.8815,  -2.6406, -14.9818, -22.8584,
          -2.1996,  -1.0117]])
tensor([[ 0.2853,  0.7637,  0.7678, -0.0125, -0.1454,  0.7515, -0.1303,  0.9896,
          0.6204,  0.7267,  1.1185,  1.0086,  0.7459,  0.9627,  0.8101,  0.0805,
          0.7741,  0.5534,  0.7912, -0.3583,  0.3010,  0.5080,  0.7101,  0.5969,
          0.7865,  0.1566,  0.7163,  0.5843,  0.6423,  0.8403]],
       grad_fn=<AddmmBackward0>)
i: 52
Mesh labels: [13]
tensor([[-15.8641, -16.7311, -30.2572, -11.1232,  -7.8833,  -6.1485,  -5.6824,
          -9.0799, -18.5692,  -5.9895, -27.9221, -15.6250,  -9.1639,   6.2900,
         -16.3776, -13.1409, -25.0122, -17.8039, -19.6985,  -6.8510, -11.1158,
          -6.7717, -12.2290, -21.9364, -25.7201,  -

tensor([[ -0.2305,  -4.0184, -12.6503, -17.4685, -18.1176,  -1.9605,  -3.2601,
           0.5776, -18.5150, -13.8281,  -0.5558,   1.2179,  -6.9904, -16.3835,
         -12.3024,  -9.7511,   8.5948, -15.4526, -15.1367,  -7.6790, -15.3562,
         -19.0931, -22.1748,  -0.4873, -11.9505, -14.5855, -25.1167,  -9.8437,
          -2.8356,  -6.9270]])
tensor([[ 0.2068,  0.7385,  0.7141, -0.0244, -0.1184,  0.6987, -0.1097,  0.9218,
          0.5426,  0.8014,  1.0054,  1.0464,  0.7371,  0.9049,  0.8285,  0.0508,
          0.7073,  0.5093,  0.7693, -0.3003,  0.2971,  0.4485,  0.6428,  0.5426,
          0.7431,  0.2183,  0.6634,  0.5289,  0.6093,  0.8177]],
       grad_fn=<AddmmBackward0>)
i: 65
Mesh labels: [16]
tensor([[ -0.6301,  -3.0935, -14.3209, -18.2206, -19.0372,  -1.2869,  -3.4087,
           2.1668, -19.6392, -13.7200,  -0.9969,   1.3437,  -6.4698, -15.2497,
         -13.4620, -10.3176,   8.8543, -16.4211, -17.0402,  -6.8362, -16.0685,
         -18.2201, -22.2330,  -1.6641, -12.3931, -1

tensor([[-17.0619,  -6.1322, -14.4201,  -2.2379,  -3.1992,   1.1163,  -6.3601,
         -13.0705, -19.2036,  -2.5457, -24.2670, -22.8753, -17.2121,  -1.7657,
         -16.9953,  -3.6071, -20.4923,  -0.9556,  -7.7561, -17.0529, -17.0617,
           9.1876, -17.7948, -11.0359, -23.7143, -19.0768, -12.6307,  -0.7818,
         -19.1150, -26.6659]])
tensor([[ 0.3219,  0.8523,  0.8227, -0.0200, -0.1690,  0.8030, -0.1396,  1.0613,
          0.6701,  0.7945,  1.1685,  1.1434,  0.8411,  1.0928,  0.9045,  0.0854,
          0.8924,  0.6766,  0.9187, -0.4016,  0.3605,  0.5251,  0.7178,  0.6496,
          0.8425,  0.1690,  0.7762,  0.5994,  0.7172,  0.9031]],
       grad_fn=<AddmmBackward0>)
i: 86
Mesh labels: [21]
tensor([[-16.7548,  -8.9297, -16.2944,  -1.9696,  -1.4119,   2.3184,  -6.9051,
         -14.3801, -21.2906,  -4.0274, -27.1826, -23.5177, -15.4157,  -1.2381,
         -18.4288,  -5.0259, -21.6452,   0.9273,  -6.7008, -19.1735, -15.5576,
           9.5294, -18.1917, -11.5982, -26.3427, -1

i: 98
Mesh labels: [24]
tensor([[-2.1703e+01, -6.9458e+00, -6.1780e+00, -1.5551e+01, -1.3367e+01,
         -1.7661e+01, -7.2359e+00, -1.9213e+01,  2.0067e+00, -4.7008e+00,
          3.9498e-01, -9.2940e+00, -1.6540e+01, -2.2835e+01,  3.2599e+00,
         -1.2083e+01, -1.3022e+01, -2.0089e+01, -1.6099e+01,  2.3315e-02,
         -1.9040e+01, -2.6934e+01,  1.0648e+00, -1.7035e+01,  8.4717e+00,
         -9.2541e+00, -1.0951e+01, -2.6872e+01, -4.4268e+00,  1.0220e+00]])
tensor([[ 0.2637,  0.8216,  0.7789, -0.0077, -0.1634,  0.8183, -0.1398,  1.0062,
          0.6221,  0.8254,  1.1246,  1.1417,  0.7825,  1.0353,  0.9131,  0.0972,
          0.8633,  0.6520,  0.8996, -0.3556,  0.3866,  0.5562,  0.7212,  0.6319,
          0.8314,  0.2156,  0.7185,  0.6035,  0.7077,  0.8842]],
       grad_fn=<AddmmBackward0>)
i: 99
Mesh labels: [24]
tensor([[-18.4914,  -2.5141,  -3.0341, -16.2558, -16.3363, -15.5074,  -6.1396,
         -14.6389,   2.9598,  -4.3091,   4.1932,  -7.2936, -17.5361, -23.7909,
       

epoch: 8, loss: 926.9484078735113
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[ 0.3662,  0.9709,  0.8822,  0.0085, -0.1557,  0.8968, -0.2106,  1.0933,
          0.7077,  0.8197,  1.2884,  1.2188,  0.8224,  1.2199,  1.0270,  0.0901,
          0.9538,  0.7296,  0.9737, -0.4598,  0.4564,  0.6732,  0.7905,  0.7431,
          1.0497,  0.2331,  0.8975,  0.7624,  0.8754,  0.9923]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.752

tensor([[-14.3651, -14.8762, -22.9706, -12.7757, -14.7615, -10.2669,  -2.8232,
         -13.2798, -22.8725, -11.4790, -13.6824, -11.5731, -18.6450, -16.5624,
         -12.0000, -10.6746, -17.3770, -25.1404, -18.2897, -11.7565, -20.6592,
         -21.6479, -23.4197, -12.6670, -21.4061, -13.9554, -23.9975, -21.7086,
         -13.0442, -15.4077]])
tensor([[ 0.4340,  1.0958,  1.0012,  0.0342, -0.1003,  0.9491, -0.2276,  1.1387,
          0.7192,  0.8910,  1.3209,  1.2979,  0.8995,  1.2580,  1.0801,  0.0936,
          0.9753,  0.7421,  1.0084, -0.4387,  0.4853,  0.6904,  0.7932,  0.7923,
          1.0952,  0.2910,  0.9423,  0.7970,  0.9309,  1.0834]],
       grad_fn=<AddmmBackward0>)
i: 25
Mesh labels: [6]
tensor([[-14.5027, -13.2319, -21.4615, -12.8570, -17.1793, -11.6074,  -2.7180,
         -12.7763, -23.4383, -11.8774, -11.1201, -11.7537, -21.2265, -19.1802,
         -10.7729,  -9.0745, -16.8068, -27.7212, -18.5842, -12.0273, -22.8469,
         -23.7130, -26.2228, -11.3570, -20.5803, -15

tensor([[ -4.4743, -16.6764, -28.8617, -20.4170, -17.7206,  -8.2828,  -1.4638,
          -3.3905, -24.2498, -17.8774,  -6.6131,   5.0031,  -3.0654, -15.8612,
         -11.2393, -16.5554,  -4.1831, -28.1277, -22.4059,  -4.0396, -14.3031,
         -30.4099, -19.6010, -11.8734, -16.3253,  -8.2380, -24.1908, -24.4493,
          -5.0211,  -0.9363]])
tensor([[ 0.5364,  1.2068,  1.1507,  0.1066, -0.0788,  1.1487, -0.2532,  1.3106,
          0.9156,  0.9030,  1.6146,  1.3925,  1.0004,  1.4465,  1.1470,  0.1855,
          1.1192,  0.8131,  1.0675, -0.4907,  0.4957,  0.8081,  0.9093,  0.8796,
          1.2316,  0.2448,  1.0233,  0.9849,  1.0342,  1.2007]],
       grad_fn=<AddmmBackward0>)
i: 48
Mesh labels: [12]
tensor([[ -2.5661, -21.2394, -26.3129, -14.7674,  -3.7861,  -3.7560,  -5.4643,
          -9.4294, -18.3040, -16.3390, -16.4038,  -1.9755,   8.2599,  -6.0303,
         -12.2086, -19.6346,  -8.9211,  -9.9889, -12.6845,  -8.9282,   0.3199,
         -19.3350,  -8.5402, -14.0364, -15.6637,  -

tensor([[-20.5121, -10.8599,  -7.5975, -11.9631, -13.1542, -18.6488,  -6.4280,
         -20.0937,  -4.2401,  -6.0960,  -2.7362, -11.5782, -19.2985, -22.1444,
           4.0644,  -8.5918, -17.2663, -21.8911, -12.9144,  -3.9298, -19.6721,
         -27.1996,  -7.6258, -14.0386,   0.8437,  -8.9811, -12.5892, -27.7664,
          -3.5568,  -2.5695]])
tensor([[ 0.4469,  1.1848,  1.0964,  0.0398, -0.0560,  1.0621, -0.2128,  1.2777,
          0.8472,  1.0485,  1.4631,  1.4952,  1.0593,  1.3540,  1.1611,  0.1123,
          1.0517,  0.7642,  1.0611, -0.4105,  0.5172,  0.7190,  0.8274,  0.8459,
          1.1529,  0.3429,  0.9726,  0.8497,  0.9649,  1.1967]],
       grad_fn=<AddmmBackward0>)
i: 60
Mesh labels: [15]
tensor([[-13.5967,  -2.3520,  -6.0668,  -3.6582, -14.0064,  -8.8274,  -3.0108,
          -9.4713, -15.9220,  -2.6821,  -7.0240, -15.6165, -25.0987, -13.4810,
          -5.9365,   4.0143, -15.2033, -18.3239,  -9.3359, -11.3389, -23.5738,
          -8.4257, -23.9934,  -2.9656, -15.4251, -1

tensor([[ -6.4295, -14.6801,  -4.1200,  -0.1680,  -4.3292,  -6.5845,  -6.2795,
         -17.6786, -15.8085, -10.2893, -15.0795, -19.4315, -19.0610, -15.7840,
          -7.7838,  -4.5055, -16.7387,  -1.5443,   8.1127, -22.9785,  -9.2824,
         -11.0889, -21.8150,   0.4739, -19.2742, -12.8191, -21.3896, -15.9492,
          -3.1681, -20.7893]])
tensor([[ 0.4845,  1.2184,  1.1023,  0.0570, -0.0554,  1.0443, -0.2338,  1.2779,
          0.8276,  1.0485,  1.4326,  1.5231,  1.0349,  1.4156,  1.2169,  0.1007,
          1.0853,  0.8374,  1.0945, -0.4705,  0.5388,  0.7196,  0.7947,  0.8473,
          1.1980,  0.3215,  1.0170,  0.8285,  1.0268,  1.1782]],
       grad_fn=<AddmmBackward0>)
i: 74
Mesh labels: [18]
tensor([[ -6.8667, -15.2529,  -4.2042,   0.6357,  -4.3796,  -7.5659,  -6.3964,
         -18.6289, -16.0172, -10.4212, -15.2902, -20.4248, -20.2556, -16.4315,
          -7.5203,  -4.4047, -18.0207,  -2.8373,   7.9993, -23.6170,  -9.4781,
         -11.8062, -22.7356,   0.1718, -19.7938, -1

tensor([[-17.1850,  -7.1073, -14.7938,  -1.7395,  -2.3789,   1.4221,  -6.6295,
         -13.9747, -20.0892,  -2.9650, -25.4700, -23.6302, -17.1402,  -1.8111,
         -17.4176,  -3.7117, -21.3280,  -0.1791,  -7.0395, -18.3350, -16.8462,
           9.6003, -18.4236, -11.0242, -24.9167, -19.4055, -13.2250,  -1.3964,
         -19.1988, -27.6331]])
tensor([[ 0.5098,  1.3045,  1.2048,  0.0881, -0.0967,  1.2593, -0.2383,  1.3944,
          0.9812,  1.0767,  1.6902,  1.6473,  1.1666,  1.5645,  1.2944,  0.2425,
          1.2816,  0.9328,  1.2223, -0.4549,  0.5852,  0.8309,  0.9160,  0.9368,
          1.2733,  0.3398,  1.0393,  1.0215,  1.0931,  1.3182]],
       grad_fn=<AddmmBackward0>)
i: 88
Mesh labels: [22]
tensor([[-24.1869, -16.2579, -18.5360, -14.4957,  -6.7891, -15.6602,  -7.5203,
         -21.3831,  -1.1955,  -1.4690, -14.5474, -12.5893, -12.0231,  -8.8962,
          -3.5067, -15.8422, -23.6550, -18.1094, -19.6146,   0.5762, -14.0230,
         -19.8573,   9.2143, -25.6817,  -3.6654,  -

tensor([[ -7.4048, -22.1733, -15.2929,  -6.4625,  -5.3935, -12.9865,  -5.0201,
         -18.1305, -11.8294, -10.7239, -16.0824, -12.8918, -12.5425, -11.4209,
          -7.5349, -11.3807, -20.0058, -15.6435,  -5.4711, -14.6736,  -5.6768,
         -20.9887, -15.0176,  -9.4945, -18.9987,  -0.6859, -14.4005, -25.4367,
          -7.3166, -11.3289]])
tensor([[ 0.5136,  1.3622,  1.2430,  0.0311, -0.1121,  1.3427, -0.2451,  1.4771,
          1.0490,  1.1936,  1.7429,  1.7623,  1.2658,  1.5850,  1.3845,  0.2761,
          1.3520,  0.9726,  1.2844, -0.4271,  0.6830,  0.9029,  0.9976,  1.0687,
          1.2975,  0.4189,  1.0361,  1.0119,  1.0980,  1.3878]],
       grad_fn=<AddmmBackward0>)
i: 101
Mesh labels: [25]
tensor([[-12.8098, -23.2901, -20.9864,  -9.1904,  -3.2161, -15.2389,  -4.7031,
         -18.8213,  -5.7028,  -6.9229, -17.6228, -10.7221,  -7.1677,  -4.3441,
          -5.7731, -15.3477, -23.2659, -19.0057, -12.8664,  -6.1625,  -3.2857,
         -20.8899,  -3.9397, -19.1224, -13.9923,  

tensor([[ -5.6747, -16.5607, -13.8552, -12.4289,  -9.0309,  -9.1177,  -7.3269,
         -13.4645, -19.0084, -16.3229,  -9.7802,  -8.4972,  -6.0034, -17.5821,
          -5.2400, -11.8945,  -9.7701, -10.7945,  -4.4544, -13.8432,  -9.6555,
         -23.1260, -17.5195,  -5.1675, -12.6809, -11.0318, -20.5066, -24.0512,
           4.7974,  -6.1301]])
tensor([[ 0.5661,  1.4662,  1.3178,  0.0593, -0.1055,  1.4247, -0.2955,  1.5350,
          1.1177,  1.2165,  1.8881,  1.8321,  1.2974,  1.6981,  1.4894,  0.3009,
          1.4307,  1.0161,  1.3361, -0.4675,  0.7388,  0.9840,  1.0629,  1.1601,
          1.4592,  0.4900,  1.1667,  1.1513,  1.1988,  1.4536]],
       grad_fn=<AddmmBackward0>)
i: 115
Mesh labels: [28]
tensor([[ -5.5571, -16.3994, -14.1083, -13.3570, -10.1724,  -9.5266,  -7.1264,
         -13.0232, -19.3412, -16.8826,  -8.5119,  -7.4851,  -6.3209, -18.7097,
          -4.8544, -12.0904,  -8.6519, -12.1154,  -5.3973, -13.2534, -10.3211,
         -24.7786, -18.1657,  -5.0330, -12.2443, -

In [57]:
# Record testing accuracy after attack
attacked_model_outputs = test_attacked_model(mesh_cnn, dataloader, opt_writer)

epoch: -1, TEST ACC: [99.167 %]

