In [1]:
from options.test_options import TestOptions
from data import DataLoader
from models import create_model
from models.layers.mesh_prepare import extract_features
from util.writer import Writer
from data.base_dataset import collate_fn
import numpy as np
import random
import torch.nn as nn
import torch
import torch.utils.data

In [2]:
def test_attacked_model(model, dataset, writer):
    writer.reset_counter()
    attacked_model_outputs = []
    
    for i, data in enumerate(dataset):
        model.set_input(data)
        output, ncorrect, nexamples = model.test() 
        attacked_model_outputs.append(output)
        writer.update_counter(ncorrect, nexamples)
        
    writer.print_acc(-1, writer.acc)
    return attacked_model_outputs 
    
def find_new_vertex_index(vertices_edges, edge_index, old_vertex_index):
    for new_vertex_index, new_vertex_edges in enumerate(vertices_edges):
            for new_edge_index in new_vertex_edges:
                if(new_edge_index == edge_index and new_vertex_index != old_vertex_index):
                    return new_vertex_index
                
def get_random_walk(mesh, random_walk_size):
    walk_steps = 0
    random_walk_vertices = []
    random_walk_indices = []
    vertex_index = random.randint(0, len(mesh.vs)-1)
    
    while walk_steps < random_walk_size: 
        random_walk_vertices.append(mesh.vs[vertex_index])
        random_walk_indices.append(vertex_index)        
        walk_steps += 1  
        
        vertex_edges = mesh.ve[vertex_index]
        random_edge_index = random.randint(0, len(vertex_edges)-1)  
        new_edge_index = vertex_edges[random_edge_index]
        vertex_index = find_new_vertex_index(mesh.ve, new_edge_index, random_walk_indices[-1])
        
        #Prevents random walk from crossing over itself
        count_of_vertex_edge_attempts = 0
        walk_steps_backwards = 0
        while(vertex_index in random_walk_indices):
            if(count_of_vertex_edge_attempts >= len(vertex_edges)-1):
                walk_steps_backwards += 1
                go_back_to_index = walk_steps-walk_steps_backwards
                
                if(go_back_to_index == 0):
                    # Trying again, mesh seems to be broken?
                    return get_random_walk(mesh, random_walk_size)
                
                vertex_edges = mesh.ve[random_walk_indices[go_back_to_index]]
                count_of_vertex_edge_attempts = 0
                
            random_edge_index = (random_edge_index + 1) % len(vertex_edges)
            new_edge_index = vertex_edges[random_edge_index]
            vertex_index = find_new_vertex_index(mesh.ve, new_edge_index, random_walk_indices[-1])
            count_of_vertex_edge_attempts += 1        
    
    return torch.FloatTensor(random_walk_vertices), random_walk_indices

In [3]:
def train_imitating_network(imitating_nn, criterion, optimizer, random_walk_vertices, attacked_nn_output):

    output = imitating_nn(random_walk_vertices)
    loss = criterion(output, attacked_nn_output)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step() 

    return output, loss.item()

In [4]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size
        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        self.i2o = nn.Linear(input_size + hidden_size, output_size)

    def forward(self, input, hidden):
        
        combined = torch.cat((input, hidden), -1)
        hidden = self.i2h(combined)
        output = self.i2o(combined)
        
        return output, hidden

    def initHidden(self):
        return torch.zeros(1, self.hidden_size)

class Imitating_NN(nn.Module):
    def __init__(self, input_size, output_size):
        super(Imitating_NN, self).__init__()
        
        self.num_vertices = 3
        self.scaling_factor = 10
        
        self.first_linear = nn.Linear(input_size, input_size*self.scaling_factor)
        self.second_linear = nn.Linear(input_size*self.scaling_factor, input_size*self.scaling_factor)
        self.rnn = RNN(self.scaling_factor*input_size, input_size, self.scaling_factor*input_size)
        self.third_linear = nn.Linear(self.scaling_factor*input_size, output_size)
        
    def forward(self, random_walk_vertices):
        
        transformed_random_walk = self.first_linear(random_walk_vertices)
        transformed_random_walk = self.second_linear(transformed_random_walk)
        
        hidden = self.rnn.initHidden()
        for step in transformed_random_walk:
            output, hidden = self.rnn(torch.reshape(step, (1, self.num_vertices*self.scaling_factor)), hidden)
            
        output = self.second_linear(output)
            
        return output
        

# Orchestration

In [5]:
testing_opt = TestOptions().parse()

testing_opt.serial_batches = True
dataloader = DataLoader(testing_opt)
mesh_cnn = create_model(testing_opt)
opt_writer = Writer(testing_opt)

random_walk_size = 50
num_categories = 30
num_vertice_coordinates = 3
imitating_nn = Imitating_NN(num_vertice_coordinates, num_categories)
criterion = nn.KLDivLoss(reduction="batchmean")
optimizer = torch.optim.Adam(imitating_nn.parameters(), lr = 0.0001)

loaded mean / std from cache
loading the model from ./checkpoints/shrec16/latest_net.pth


In [6]:
# Record testing accuracy before attack
attacked_model_outputs = test_attacked_model(mesh_cnn, dataloader, opt_writer)

epoch: -1, TEST ACC: [99.167 %]



In [7]:
# Random Walk Attack
for epoch in range(10):
    epoch_loss = 0
    
    for i, data in enumerate(dataloader):
        print("i: " + str(i))
        print("Mesh labels: " + str(data["label"]))
    
        mesh = data["mesh"][0]
        random_walk_vertices, random_walk_indices = get_random_walk(mesh, random_walk_size)
    
        imitating_nn_output, loss = train_imitating_network(imitating_nn, criterion, optimizer, random_walk_vertices, attacked_model_outputs[i])
        epoch_loss += loss
    
        print(attacked_model_outputs[i])
        print(imitating_nn_output)
    
    print("epoch: " + str(epoch) + ", loss: " + str(epoch_loss))
    

i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[ 0.1982, -0.0295,  0.0188,  0.0736,  0.0445,  0.0668, -0.0656, -0.0698,
          0.0070,  0.1290, -0.0998,  0.0623,  0.0270,  0.0138, -0.2009, -0.0837,
          0.0525,  0.1806, -0.0441, -0.1633, -0.1165,  0.1817, -0.0232,  0.0348,
          0.0736, -0.0719,  0.1241,  0.1242, -0.0642,  0.2423]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.7529,
         -21.3954, -25.2309,  -

/var/folders/ts/sy6vbbcs1vdbgtnds0713g6w0000gq/T/ipykernel_10221/1098266402.py:56: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:204.)
  return torch.FloatTensor(random_walk_vertices), random_walk_indices


i: 14
Mesh labels: [3]
tensor([[-13.9660, -12.2713, -12.0443,   5.6351,  -3.6740,  -6.9553,  -4.5959,
         -17.9461, -17.6826,  -5.2133, -19.0052, -23.7066, -23.1402,  -9.8901,
         -10.1013,  -2.3390, -25.3224, -11.6810,  -3.6288, -20.4719, -12.9614,
          -5.8187, -22.8622,  -8.5795, -23.6955, -13.3311, -20.4259, -11.6520,
         -14.3199, -25.3500]])
tensor([[ 0.2968, -0.0773,  0.0299,  0.0698,  0.0230,  0.0045, -0.0818, -0.0227,
          0.0665,  0.0972, -0.0511,  0.0038,  0.0812,  0.0617, -0.1931, -0.1628,
          0.0725,  0.2657, -0.0692, -0.2055, -0.1342,  0.1725, -0.0159,  0.0047,
          0.1616, -0.0826,  0.1403,  0.1419, -0.0291,  0.2535]],
       grad_fn=<AddmmBackward0>)
i: 15
Mesh labels: [3]
tensor([[-14.2403, -12.7981, -11.2377,   5.2370,  -3.5653,  -7.9844,  -4.7698,
         -18.8413, -16.3065,  -5.1471, -18.1189, -23.2033, -22.8174, -10.6906,
          -8.7109,  -2.6504, -25.2361, -11.8052,  -3.2504, -19.7953, -12.6823,
          -7.1463, -21.5870, 

tensor([[ -9.8054,  -3.0362,  -7.7672, -16.0421, -22.0341, -12.0270,  -2.7380,
          -6.8935, -11.8634, -10.3999,   5.5222,  -3.5391, -19.0065, -24.9962,
          -3.9015,  -6.5952,  -1.8166, -26.7677, -17.2053,  -4.8793, -22.5182,
         -27.6809, -20.6622,  -4.9033,  -3.8696, -14.3837, -25.3255, -18.7351,
          -3.4505,  -5.7859]])
tensor([[ 0.2675, -0.0421,  0.0488,  0.0796,  0.0361,  0.0249, -0.0872, -0.0417,
          0.0557,  0.1098, -0.0800,  0.0358,  0.0596,  0.0449, -0.2242, -0.1418,
          0.0629,  0.2482, -0.0370, -0.1995, -0.1167,  0.1754, -0.0257,  0.0304,
          0.1314, -0.0587,  0.1321,  0.1506, -0.0372,  0.2499]],
       grad_fn=<AddmmBackward0>)
i: 41
Mesh labels: [10]
tensor([[-11.2173,  -6.1620, -11.1898, -17.2096, -22.5225, -13.7300,  -3.1268,
          -8.5890, -14.1684, -11.9777,   3.7165,  -3.9115, -19.1191, -25.7827,
          -3.5140,  -8.1554,  -4.8522, -29.2217, -18.6284,  -5.1977, -23.2068,
         -30.7806, -21.5459,  -7.0243,  -5.5154, -1

tensor([[-15.8641, -16.7311, -30.2572, -11.1232,  -7.8833,  -6.1485,  -5.6824,
          -9.0799, -18.5692,  -5.9895, -27.9221, -15.6250,  -9.1639,   6.2900,
         -16.3776, -13.1409, -25.0122, -17.8039, -19.6985,  -6.8510, -11.1158,
          -6.7717, -12.2290, -21.9364, -25.7201,  -6.3351,  -2.2219,  -9.3106,
         -20.5732, -13.2399]])
tensor([[ 0.2910, -0.0547,  0.0431,  0.0878,  0.0240,  0.0217, -0.0808, -0.0311,
          0.0694,  0.1189, -0.0352,  0.0290,  0.0769,  0.0513, -0.1855, -0.1440,
          0.0724,  0.2470, -0.0813, -0.2085, -0.1243,  0.1756, -0.0155,  0.0147,
          0.1549, -0.0927,  0.1337,  0.1235, -0.0300,  0.2485]],
       grad_fn=<AddmmBackward0>)
i: 53
Mesh labels: [13]
tensor([[-12.7686, -17.5714, -30.0671, -10.8246,  -6.6834,  -4.9487,  -5.6762,
          -8.2139, -19.3342,  -7.7499, -27.4529, -14.2749,  -6.1452,   5.8931,
         -16.9944, -13.9010, -22.8718, -15.9904, -17.8295,  -8.2325,  -8.0531,
          -7.1127, -12.5369, -20.3526, -26.0155,  -

tensor([[-11.6825, -12.2505, -10.7722,  -6.7096,  -1.4883,   1.7088,  -9.1169,
         -17.5816, -15.0029,  -7.9571, -21.6429, -19.3534, -10.4706,  -8.5471,
         -15.0151, -10.9823, -13.5001,   9.7328,  -1.0644, -19.2081,  -9.1805,
          -1.0184, -11.4677,  -8.2623, -18.2102, -17.2054, -16.1504, -10.4670,
         -10.1067, -20.2782]])
tensor([[ 0.3071, -0.0601,  0.0535,  0.0791,  0.0426,  0.0050, -0.0720, -0.0156,
          0.0682,  0.1021, -0.0631,  0.0343,  0.0897,  0.0752, -0.1887, -0.1528,
          0.0672,  0.2764, -0.0195, -0.2212, -0.1254,  0.1833, -0.0382,  0.0045,
          0.1653, -0.0756,  0.1503,  0.1736, -0.0197,  0.2658]],
       grad_fn=<AddmmBackward0>)
i: 69
Mesh labels: [17]
tensor([[-12.6438, -13.2250, -12.0964,  -7.2383,  -1.8626,   1.8031,  -9.3824,
         -18.5628, -16.4985,  -8.6381, -22.9652, -20.3323, -11.1498,  -9.1867,
         -15.8007, -11.6935, -14.6234,   9.7318,  -1.4018, -20.2794, -10.1510,
          -1.4459, -12.6446,  -9.0394, -19.4796, -1

tensor([[-16.9386,  -6.8993, -13.9714,  -2.1039,  -2.3359,   1.2923,  -6.6079,
         -13.9512, -18.7974,  -2.7846, -24.4515, -23.0021, -16.5929,  -2.0839,
         -16.8218,  -4.0640, -20.5056,   0.1491,  -6.9824, -17.5369, -16.2591,
           8.9416, -17.2292, -10.9651, -23.5076, -18.8022, -12.7433,  -1.8087,
         -18.5947, -26.5262]])
tensor([[ 0.2648, -0.0273,  0.0602,  0.0905,  0.0428,  0.0398, -0.0821, -0.0562,
          0.0469,  0.1242, -0.0733,  0.0680,  0.0743,  0.0458, -0.2108, -0.1175,
          0.0786,  0.2674,  0.0130, -0.2072, -0.1087,  0.1886, -0.0352,  0.0277,
          0.1297, -0.0614,  0.1349,  0.1624, -0.0405,  0.2518]],
       grad_fn=<AddmmBackward0>)
i: 85
Mesh labels: [21]
tensor([[-17.0619,  -6.1322, -14.4201,  -2.2379,  -3.1992,   1.1163,  -6.3601,
         -13.0705, -19.2036,  -2.5457, -24.2670, -22.8753, -17.2121,  -1.7657,
         -16.9953,  -3.6071, -20.4923,  -0.9556,  -7.7561, -17.0529, -17.0617,
           9.1876, -17.7948, -11.0359, -23.7143, -1

tensor([[-2.1703e+01, -6.9458e+00, -6.1780e+00, -1.5551e+01, -1.3367e+01,
         -1.7661e+01, -7.2359e+00, -1.9213e+01,  2.0067e+00, -4.7008e+00,
          3.9498e-01, -9.2940e+00, -1.6540e+01, -2.2835e+01,  3.2599e+00,
         -1.2083e+01, -1.3022e+01, -2.0089e+01, -1.6099e+01,  2.3315e-02,
         -1.9040e+01, -2.6934e+01,  1.0648e+00, -1.7035e+01,  8.4717e+00,
         -9.2541e+00, -1.0951e+01, -2.6872e+01, -4.4268e+00,  1.0220e+00]])
tensor([[ 0.3207, -0.0769,  0.0598,  0.0893,  0.0276,  0.0115, -0.0869, -0.0179,
          0.0877,  0.1078, -0.0267,  0.0263,  0.1044,  0.0737, -0.1720, -0.1548,
          0.0969,  0.3077, -0.0301, -0.2263, -0.1176,  0.1947, -0.0168,  0.0018,
          0.1878, -0.0872,  0.1409,  0.1550, -0.0219,  0.2665]],
       grad_fn=<AddmmBackward0>)
i: 99
Mesh labels: [24]
tensor([[-18.4914,  -2.5141,  -3.0341, -16.2558, -16.3363, -15.5074,  -6.1396,
         -14.6389,   2.9598,  -4.3091,   4.1932,  -7.2936, -17.5361, -23.7909,
           1.3354, -10.9404,  -

tensor([[ -5.6747, -16.5607, -13.8552, -12.4289,  -9.0309,  -9.1177,  -7.3269,
         -13.4645, -19.0084, -16.3229,  -9.7802,  -8.4972,  -6.0034, -17.5821,
          -5.2400, -11.8945,  -9.7701, -10.7945,  -4.4544, -13.8432,  -9.6555,
         -23.1260, -17.5195,  -5.1675, -12.6809, -11.0318, -20.5066, -24.0512,
           4.7974,  -6.1301]])
tensor([[ 0.2909, -0.0324,  0.0754,  0.0910,  0.0623,  0.0371, -0.0520, -0.0464,
          0.0498,  0.1094, -0.0926,  0.0615,  0.0713,  0.0490, -0.1777, -0.1141,
          0.0745,  0.2897,  0.0625, -0.2105, -0.1005,  0.2156, -0.0414,  0.0207,
          0.1570, -0.0582,  0.1430,  0.2053, -0.0210,  0.2629]],
       grad_fn=<AddmmBackward0>)
i: 115
Mesh labels: [28]
tensor([[ -5.5571, -16.3994, -14.1083, -13.3570, -10.1724,  -9.5266,  -7.1264,
         -13.0232, -19.3412, -16.8826,  -8.5119,  -7.4851,  -6.3209, -18.7097,
          -4.8544, -12.0904,  -8.6519, -12.1154,  -5.3973, -13.2534, -10.3211,
         -24.7786, -18.1657,  -5.0330, -12.2443, -

tensor([[-12.6880, -12.8750, -10.0355,   5.0915,  -2.9794,  -7.6716,  -4.5700,
         -18.3993, -15.3633,  -5.6254, -17.1177, -22.0048, -21.5706, -11.0255,
          -8.2964,  -3.0174, -23.5324, -10.5834,  -1.8890, -19.7286, -11.2272,
          -7.6164, -20.7858,  -7.4569, -21.0455, -11.4676, -19.3902, -13.6317,
         -11.7398, -22.7251]])
tensor([[ 0.3095, -0.0367,  0.0817,  0.0851,  0.0182,  0.0201, -0.0908, -0.0457,
          0.0992,  0.1196, -0.0106,  0.0531,  0.1045,  0.0683, -0.1953, -0.1494,
          0.0940,  0.3097, -0.0336, -0.2291, -0.1112,  0.2006, -0.0074,  0.0400,
          0.1901, -0.0567,  0.1493,  0.1676, -0.0216,  0.2693]],
       grad_fn=<AddmmBackward0>)
i: 14
Mesh labels: [3]
tensor([[-13.9660, -12.2713, -12.0443,   5.6351,  -3.6740,  -6.9553,  -4.5959,
         -17.9461, -17.6826,  -5.2133, -19.0052, -23.7066, -23.1402,  -9.8901,
         -10.1013,  -2.3390, -25.3224, -11.6810,  -3.6288, -20.4719, -12.9614,
          -5.8187, -22.8622,  -8.5795, -23.6955, -13

tensor([[ -5.3056,  -3.2552, -24.4040, -15.7908, -21.0671,  -1.8737,  -2.4133,
           5.9620, -26.3756, -11.7919, -10.4324,  -3.8186, -11.6785,  -7.7541,
         -17.2509,  -8.5960,  -5.1452, -24.3250, -22.0715,  -5.9061, -20.2019,
         -13.2944, -26.0743,  -8.6056, -21.3844, -17.4667, -22.8803,  -1.7048,
         -12.7513, -12.7094]])
tensor([[ 0.3112, -0.0162,  0.0861,  0.1108,  0.0424,  0.0401, -0.0553, -0.0549,
          0.0682,  0.1255, -0.0345,  0.0570,  0.0826,  0.0526, -0.1554, -0.1163,
          0.0822,  0.2827, -0.0152, -0.2132, -0.1061,  0.2155, -0.0197,  0.0317,
          0.1777, -0.0843,  0.1358,  0.1688, -0.0077,  0.2624]],
       grad_fn=<AddmmBackward0>)
i: 29
Mesh labels: [7]
tensor([[ -4.8895,  -2.3995, -24.5613, -17.8141, -22.8905,  -1.8075,  -2.1679,
           7.4466, -26.3032, -12.3963,  -8.0546,  -1.4604, -11.1244,  -9.0692,
         -17.2034,  -9.4489,  -1.9529, -25.8494, -23.8965,  -4.3958, -21.3874,
         -15.2626, -26.1622,  -8.3694, -19.8813, -17

tensor([[-10.7335,  -0.9883,  -5.9118, -16.8425, -23.7691, -12.3235,  -3.3852,
          -6.6129, -10.4517,  -9.9265,   6.6998,  -4.5129, -20.9599, -26.4770,
          -3.8285,  -6.6393,  -0.8745, -27.1926, -17.8756,  -4.7551, -24.2907,
         -27.9905, -21.0365,  -4.9740,  -2.2693, -15.9242, -26.1038, -17.7034,
          -3.6896,  -6.1695]])
tensor([[ 0.2883,  0.0056,  0.1028,  0.1059,  0.0545,  0.0511, -0.0582, -0.0623,
          0.0653,  0.1313, -0.0681,  0.0811,  0.0695,  0.0420, -0.1909, -0.1065,
          0.0769,  0.2804,  0.0377, -0.2097, -0.0947,  0.2171, -0.0319,  0.0466,
          0.1538, -0.0510,  0.1395,  0.1933, -0.0141,  0.2640]],
       grad_fn=<AddmmBackward0>)
i: 44
Mesh labels: [11]
tensor([[ -1.8415, -14.3549, -27.4199, -21.6404, -19.2456,  -6.6965,  -1.7176,
          -0.5529, -24.7352, -18.7934,  -4.2435,   6.6159,  -1.9919, -16.5774,
         -12.2038, -16.6825,   0.7559, -27.3295, -22.7109,  -4.0940, -14.1427,
         -30.2774, -20.9690,  -9.5340, -15.8455,  -

tensor([[-25.2615, -12.0304, -10.8018,  -9.0621, -13.4911, -19.4136,  -6.4499,
         -22.1677,  -8.5282,  -3.3381,  -8.4765, -17.5523, -25.4429, -19.2563,
           2.7891,  -5.2515, -25.0346, -24.4857, -14.3460,  -5.8762, -24.1586,
         -23.2186, -11.9233, -15.8933,  -6.0431, -11.1172, -11.0894, -25.4494,
          -9.1776,  -8.7213]])
tensor([[ 0.3087, -0.0114,  0.0993,  0.1055,  0.0349,  0.0429, -0.0669, -0.0516,
          0.0908,  0.1373, -0.0174,  0.0760,  0.0983,  0.0599, -0.1746, -0.1229,
          0.0884,  0.2909, -0.0054, -0.2189, -0.1058,  0.2088, -0.0185,  0.0348,
          0.1776, -0.0647,  0.1460,  0.1696, -0.0147,  0.2666]],
       grad_fn=<AddmmBackward0>)
i: 58
Mesh labels: [14]
tensor([[-20.3809, -13.3521, -10.1346, -11.6553, -13.3656, -19.2275,  -5.9840,
         -20.2482,  -6.5062,  -6.6484,  -4.9090, -11.8888, -19.6884, -20.8907,
           3.5689,  -8.4722, -19.5445, -23.8601, -13.2722,  -4.5353, -19.6709,
         -27.9231, -10.0866, -14.3799,  -2.6616,  -

tensor([[-21.2945,  -7.2062, -17.4864, -14.4381, -18.3967, -14.2245,  -4.0122,
         -11.4920, -13.2905,  -4.4765,  -6.9536, -10.5047, -21.0116, -15.6383,
          -3.6983,  -7.3272, -17.5250, -28.0222, -21.8283,  -0.7592, -25.3609,
         -21.6698, -13.2082, -16.6473,  -8.0752, -13.0814, -13.4338, -18.0431,
         -12.5958,  -6.8639]])
tensor([[ 0.3366, -0.0214,  0.1140,  0.1046,  0.0630,  0.0295, -0.0465, -0.0287,
          0.0849,  0.1199, -0.0559,  0.0730,  0.1036,  0.0751, -0.1606, -0.1227,
          0.0966,  0.3329,  0.0790, -0.2310, -0.1043,  0.2230, -0.0446,  0.0174,
          0.1943, -0.0601,  0.1574,  0.2247,  0.0091,  0.2806]],
       grad_fn=<AddmmBackward0>)
i: 79
Mesh labels: [19]
tensor([[-21.1760,  -7.8229, -17.7055, -15.0796, -17.7104, -14.0810,  -4.4408,
         -11.2904, -11.5622,  -3.9612,  -8.2047, -10.9211, -19.9308, -13.9055,
          -4.2826,  -8.7151, -17.9448, -27.1759, -22.1449,  -0.2300, -23.8653,
         -21.0531, -11.0685, -17.7711,  -7.9201, -1

tensor([[ -3.6909,  -5.9709,   1.0664,  -8.3934, -15.2631,  -6.8052,  -5.2215,
         -10.0951, -18.2684, -11.5242,  -4.3991, -14.3283, -23.7509, -22.8639,
          -8.7133,  -0.1991,  -4.4016, -11.2588,  -0.1566, -20.0863, -20.3451,
         -15.7986, -31.4044,   8.3715, -17.4516, -19.1758, -28.3254, -12.3074,
          -1.5262, -21.3404]])
tensor([[ 0.3328, -0.0363,  0.1251,  0.0942,  0.0159,  0.0158, -0.1231, -0.0358,
          0.1426,  0.1256,  0.0170,  0.0798,  0.1429,  0.0926, -0.2238, -0.1699,
          0.1296,  0.3800,  0.0202, -0.2583, -0.0959,  0.2110, -0.0056,  0.0453,
          0.2167, -0.0246,  0.1623,  0.1920, -0.0192,  0.2881]],
       grad_fn=<AddmmBackward0>)
i: 94
Mesh labels: [23]
tensor([[ -2.9784,  -4.4604,  -1.8961,  -9.3151, -17.1384,  -6.3612,  -4.1701,
          -7.2187, -20.3217, -11.6831,  -3.7824, -12.5407, -23.2622, -21.8246,
         -10.2428,  -0.1535,  -3.3852, -14.7988,  -3.6948, -18.7315, -21.2843,
         -15.8201, -33.0464,   7.7941, -18.8109, -1

tensor([[-20.4858, -14.5195, -17.9894,  -9.6578,  -5.7690, -12.8269,  -5.4880,
         -15.2435,  -5.2535,  -0.3668, -18.8117, -14.1828, -12.4093,   0.9912,
          -3.8652,  -9.0219, -24.8032, -17.0661, -15.1116,  -0.9258, -12.9558,
         -10.5589,  -1.9612, -19.6294, -11.6979,  -1.1449,   8.4558, -15.2649,
         -14.4261,  -5.6530]])
tensor([[ 0.3309, -0.0223,  0.1424,  0.0929,  0.0463,  0.0234, -0.0931, -0.0405,
          0.1261,  0.1151, -0.0341,  0.0866,  0.1236,  0.0818, -0.2145, -0.1514,
          0.1174,  0.3869,  0.1048, -0.2476, -0.0865,  0.2333, -0.0233,  0.0517,
          0.2156, -0.0016,  0.1615,  0.2406, -0.0062,  0.2889]],
       grad_fn=<AddmmBackward0>)
i: 108
Mesh labels: [27]
tensor([[-1.3613e+01,  4.2414e+00, -1.5571e+01, -8.6816e+00, -1.8457e+01,
         -2.1858e+00, -4.5799e+00, -1.5762e-02, -2.0048e+01, -3.5250e+00,
         -1.3950e+01, -1.5606e+01, -2.1535e+01, -5.3531e+00, -1.5352e+01,
         -1.9129e+00, -1.2371e+01, -1.6341e+01, -1.7650e+01, -8.9

epoch: 1, loss: 1397.3737370092422
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[ 0.3598, -0.0381,  0.1263,  0.1026,  0.0243,  0.0191, -0.0893, -0.0298,
          0.1455,  0.1254,  0.0326,  0.0590,  0.1431,  0.0906, -0.1630, -0.1585,
          0.1278,  0.3854,  0.0091, -0.2526, -0.1050,  0.2329,  0.0029,  0.0445,
          0.2544, -0.0469,  0.1632,  0.2007,  0.0072,  0.2810]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.75

i: 15
Mesh labels: [3]
tensor([[-14.2403, -12.7981, -11.2377,   5.2370,  -3.5653,  -7.9844,  -4.7698,
         -18.8413, -16.3065,  -5.1471, -18.1189, -23.2033, -22.8174, -10.6906,
          -8.7109,  -2.6504, -25.2361, -11.8052,  -3.2504, -19.7953, -12.6823,
          -7.1463, -21.5870,  -8.7290, -22.0186, -12.3928, -19.5079, -13.2847,
         -13.2156, -23.7977]])
tensor([[ 0.3970, -0.0300,  0.1577,  0.0971,  0.0577, -0.0016, -0.0534, -0.0037,
          0.1407,  0.0989, -0.0297,  0.0504,  0.1375,  0.1029, -0.1616, -0.1698,
          0.1176,  0.4154,  0.1191, -0.2534, -0.1002,  0.2483, -0.0320,  0.0240,
          0.2671, -0.0260,  0.1796,  0.2812,  0.0468,  0.3059]],
       grad_fn=<AddmmBackward0>)
i: 16
Mesh labels: [4]
tensor([[-14.4666, -25.2881, -23.2693,  -4.2469,   4.1617,  -7.2387,  -6.6712,
         -23.6178, -14.9484,  -9.2918, -26.8329, -19.5727,  -7.9810,  -5.1441,
         -13.2365, -17.1941, -26.8171,  -7.3547,  -8.5970, -17.0876,  -2.1206,
         -11.8050,  -8.0532, 

tensor([[ -5.3056,  -3.2552, -24.4040, -15.7908, -21.0671,  -1.8737,  -2.4133,
           5.9620, -26.3756, -11.7919, -10.4324,  -3.8186, -11.6785,  -7.7541,
         -17.2509,  -8.5960,  -5.1452, -24.3250, -22.0715,  -5.9061, -20.2019,
         -13.2944, -26.0743,  -8.6056, -21.3844, -17.4667, -22.8803,  -1.7048,
         -12.7513, -12.7094]])
tensor([[ 3.3099e-01,  2.8113e-02,  1.4158e-01,  1.3040e-01,  3.0438e-02,
          5.9069e-02, -7.3222e-02, -7.8992e-02,  1.1297e-01,  1.5664e-01,
          2.7360e-02,  1.0426e-01,  1.1444e-01,  6.0434e-02, -1.6238e-01,
         -1.1210e-01,  1.1403e-01,  3.3344e-01, -6.5893e-03, -2.3574e-01,
         -8.9110e-02,  2.4239e-01,  2.2303e-03,  7.5442e-02,  2.1164e-01,
         -5.6895e-02,  1.4647e-01,  1.7622e-01,  1.1030e-04,  2.7066e-01]],
       grad_fn=<AddmmBackward0>)
i: 29
Mesh labels: [7]
tensor([[ -4.8895,  -2.3995, -24.5613, -17.8141, -22.8905,  -1.8075,  -2.1679,
           7.4466, -26.3032, -12.3963,  -8.0546,  -1.4604, -11.1244,  -9

tensor([[-10.7335,  -0.9883,  -5.9118, -16.8425, -23.7691, -12.3235,  -3.3852,
          -6.6129, -10.4517,  -9.9265,   6.6998,  -4.5129, -20.9599, -26.4770,
          -3.8285,  -6.6393,  -0.8745, -27.1926, -17.8756,  -4.7551, -24.2907,
         -27.9905, -21.0365,  -4.9740,  -2.2693, -15.9242, -26.1038, -17.7034,
          -3.6896,  -6.1695]])
tensor([[ 3.6209e-01, -1.0610e-05,  1.6798e-01,  1.1333e-01,  2.1578e-02,
          2.5750e-02, -1.0740e-01, -3.9399e-02,  1.7081e-01,  1.4103e-01,
          4.3769e-02,  8.5759e-02,  1.4533e-01,  9.1961e-02, -2.0262e-01,
         -1.6583e-01,  1.3140e-01,  3.9467e-01,  1.7088e-02, -2.6072e-01,
         -9.4792e-02,  2.3254e-01,  4.4676e-03,  7.3958e-02,  2.5146e-01,
         -1.5735e-02,  1.6913e-01,  2.0923e-01,  9.5783e-03,  2.9271e-01]],
       grad_fn=<AddmmBackward0>)
i: 44
Mesh labels: [11]
tensor([[ -1.8415, -14.3549, -27.4199, -21.6404, -19.2456,  -6.6965,  -1.7176,
          -0.5529, -24.7352, -18.7934,  -4.2435,   6.6159,  -1.9919, -1

i: 70
Mesh labels: [17]
tensor([[-12.2687, -12.3794, -11.0054,  -6.8599,  -1.9677,   1.5837,  -9.4217,
         -18.1577, -15.6965,  -8.2384, -22.2376, -20.2821, -11.4909,  -9.1650,
         -15.4076, -11.0496, -14.1956,   9.7812,  -1.0248, -20.0553,  -9.9837,
          -1.1009, -12.3787,  -8.4523, -18.8392, -18.1488, -17.0252, -10.6071,
         -10.4759, -21.2388]])
tensor([[ 0.3990, -0.0188,  0.1694,  0.1155,  0.0255,  0.0138, -0.0870, -0.0123,
          0.1821,  0.1380,  0.0643,  0.0799,  0.1745,  0.1175, -0.1574, -0.1683,
          0.1429,  0.4149,  0.0253, -0.2696, -0.1052,  0.2365, -0.0022,  0.0452,
          0.2822, -0.0383,  0.1779,  0.2174,  0.0284,  0.2989]],
       grad_fn=<AddmmBackward0>)
i: 71
Mesh labels: [17]
tensor([[-11.8748, -12.4198, -10.1863,  -7.0423,  -2.3060,   0.9893,  -9.2045,
         -18.1749, -14.9915,  -8.3809, -21.1256, -19.9540, -11.8130,  -9.8971,
         -14.5896, -10.9697, -13.8232,   9.1062,  -0.7848, -19.7840,  -9.8210,
          -2.3611, -12.4612

tensor([[-16.9386,  -6.8993, -13.9714,  -2.1039,  -2.3359,   1.2923,  -6.6079,
         -13.9512, -18.7974,  -2.7846, -24.4515, -23.0021, -16.5929,  -2.0839,
         -16.8218,  -4.0640, -20.5056,   0.1491,  -6.9824, -17.5369, -16.2591,
           8.9416, -17.2292, -10.9651, -23.5076, -18.8022, -12.7433,  -1.8087,
         -18.5947, -26.5262]])
tensor([[ 0.3750,  0.0119,  0.1908,  0.1170,  0.0692,  0.0357, -0.0619, -0.0280,
          0.1406,  0.1354, -0.0216,  0.1121,  0.1465,  0.0970, -0.1787, -0.1362,
          0.1399,  0.4279,  0.1710, -0.2574, -0.0828,  0.2579, -0.0391,  0.0476,
          0.2437, -0.0067,  0.1806,  0.2831,  0.0331,  0.3048]],
       grad_fn=<AddmmBackward0>)
i: 85
Mesh labels: [21]
tensor([[-17.0619,  -6.1322, -14.4201,  -2.2379,  -3.1992,   1.1163,  -6.3601,
         -13.0705, -19.2036,  -2.5457, -24.2670, -22.8753, -17.2121,  -1.7657,
         -16.9953,  -3.6071, -20.4923,  -0.9556,  -7.7561, -17.0529, -17.0617,
           9.1876, -17.7948, -11.0359, -23.7143, -1

tensor([[ -7.4048, -22.1733, -15.2929,  -6.4625,  -5.3935, -12.9865,  -5.0201,
         -18.1305, -11.8294, -10.7239, -16.0824, -12.8918, -12.5425, -11.4209,
          -7.5349, -11.3807, -20.0058, -15.6435,  -5.4711, -14.6736,  -5.6768,
         -20.9887, -15.0176,  -9.4945, -18.9987,  -0.6859, -14.4005, -25.4367,
          -7.3166, -11.3289]])
tensor([[ 0.4559, -0.0626,  0.2051,  0.1069,  0.0122, -0.0174, -0.1272,  0.0224,
          0.2490,  0.1130,  0.0972,  0.0564,  0.2243,  0.1552, -0.1778, -0.2284,
          0.1873,  0.5291,  0.0809, -0.2997, -0.0952,  0.2462,  0.0161,  0.0355,
          0.3527, -0.0009,  0.1959,  0.2569,  0.0430,  0.3285]],
       grad_fn=<AddmmBackward0>)
i: 101
Mesh labels: [25]
tensor([[-12.8098, -23.2901, -20.9864,  -9.1904,  -3.2161, -15.2389,  -4.7031,
         -18.8213,  -5.7028,  -6.9229, -17.6228, -10.7221,  -7.1677,  -4.3441,
          -5.7731, -15.3477, -23.2659, -19.0057, -12.8664,  -6.1625,  -3.2857,
         -20.8899,  -3.9397, -19.1224, -13.9923,  

tensor([[-13.3109, -17.6586, -22.6130, -18.1277, -13.3338, -13.9144,  -5.0583,
         -12.6665, -15.2249, -13.3974,  -7.8443,  -2.6484,  -5.6877, -16.2637,
          -2.4342, -15.8707, -13.2478, -23.3710, -17.6797,  -1.9487, -13.5214,
         -30.4678,  -9.6489, -16.5979,  -7.3042,  -5.9155, -14.2448, -29.4232,
          -1.7010,   3.4217]])
tensor([[ 0.4173, -0.0138,  0.2005,  0.1169,  0.0268,  0.0213, -0.0978, -0.0187,
          0.2105,  0.1383,  0.0801,  0.0891,  0.1932,  0.1196, -0.1584, -0.1757,
          0.1703,  0.4824,  0.0808, -0.2812, -0.0888,  0.2679,  0.0139,  0.0656,
          0.3226, -0.0062,  0.1889,  0.2521,  0.0373,  0.3050]],
       grad_fn=<AddmmBackward0>)
i: 118
Mesh labels: [29]
tensor([[-17.6607, -15.2465, -24.5638, -20.3559, -15.6175, -14.5888,  -4.1492,
         -11.7338, -12.3722,  -9.7181,  -6.7731,  -1.8053,  -8.1024, -15.5580,
          -3.1293, -16.6138, -14.1054, -27.8091, -24.2799,   3.3553, -17.3860,
         -30.3973,  -4.9050, -21.1453,  -4.7528,  

tensor([[ -9.1728, -12.1504, -21.6671, -10.1149,  -6.2599,   3.3546,  -5.6768,
          -8.6273, -23.1617, -10.5796, -21.3516, -12.7094,  -6.6412,  -4.6775,
         -18.9983, -12.1906, -11.0990,  -3.2922, -11.6404, -14.7161, -11.6030,
          -3.6861, -17.5273, -10.8596, -23.8591, -16.8262, -18.6928,  -8.1418,
         -13.5632, -18.4154]])
tensor([[ 0.3621,  0.0798,  0.2213,  0.1384,  0.0446,  0.0669, -0.0794, -0.0842,
          0.1578,  0.1743,  0.0364,  0.1632,  0.1481,  0.0793, -0.1929, -0.1203,
          0.1456,  0.4155,  0.1056, -0.2642, -0.0643,  0.2849, -0.0011,  0.1146,
          0.2460,  0.0058,  0.1809,  0.2519,  0.0258,  0.3022]],
       grad_fn=<AddmmBackward0>)
i: 23
Mesh labels: [5]
tensor([[-10.1052, -14.2137, -22.5353, -10.7191,  -5.8350,   2.6554,  -5.7042,
         -10.5656, -23.5730, -11.4148, -21.4100, -12.5334,  -6.3684,  -6.3531,
         -18.2538, -13.3801, -12.0193,  -3.4056, -11.6031, -14.8968, -11.6538,
          -5.9565, -17.2136, -11.8770, -23.4945, -16

tensor([[-29.1347,  -9.4924, -16.0189,  -9.4573, -13.4579, -15.4269,  -6.5397,
         -19.6941,  -8.3137,   2.6010, -17.7947, -23.4021, -28.5215,  -9.8967,
          -7.0387,  -6.5830, -30.2071, -23.8775, -20.4006,  -5.4568, -26.5881,
         -12.0794,  -9.2626, -22.0024, -13.3017, -12.8041,  -6.7129, -15.4340,
         -22.9944, -17.2665]])
tensor([[ 0.4419,  0.0134,  0.2470,  0.1311,  0.0327,  0.0231, -0.1059, -0.0136,
          0.2366,  0.1438,  0.0905,  0.0989,  0.1999,  0.1281, -0.1749, -0.1884,
          0.1772,  0.5022,  0.0972, -0.2866, -0.0841,  0.2724,  0.0140,  0.0816,
          0.3357,  0.0158,  0.1977,  0.2727,  0.0558,  0.3255]],
       grad_fn=<AddmmBackward0>)
i: 38
Mesh labels: [9]
tensor([[-26.9754,  -9.1055, -11.6346,  -6.0669, -11.5090, -14.4946,  -6.7320,
         -20.5614,  -9.8262,   2.1387, -16.3481, -24.1510, -28.9189, -11.5371,
          -5.3347,  -2.8517, -28.9497, -20.0269, -15.0855,  -8.7562, -25.8955,
         -10.0486, -12.0381, -17.0934, -13.8759, -14

tensor([[ -2.8249, -21.0237, -26.2058, -14.5356,  -3.7369,  -3.6951,  -5.4744,
          -9.4119, -18.0851, -15.9133, -16.7078,  -2.3254,   7.9845,  -5.5532,
         -12.3345, -19.4005,  -9.1648,  -9.8226, -12.6477,  -8.8802,   0.1954,
         -18.7192,  -8.4656, -14.1634, -15.8359,  -3.0124, -14.3303, -22.6896,
          -2.6641,  -1.4315]])
tensor([[ 0.4438,  0.0299,  0.2617,  0.1304,  0.0668,  0.0275, -0.0704, -0.0020,
          0.2207,  0.1432,  0.0391,  0.1140,  0.1850,  0.1217, -0.1698, -0.1752,
          0.1659,  0.5035,  0.1880, -0.2818, -0.0768,  0.2905, -0.0174,  0.0692,
          0.3245,  0.0257,  0.2047,  0.3230,  0.0745,  0.3312]],
       grad_fn=<AddmmBackward0>)
i: 51
Mesh labels: [12]
tensor([[ -2.0639, -21.0047, -26.3009, -14.3487,  -3.9949,  -3.9108,  -4.9434,
          -8.5752, -18.5038, -16.3379, -15.8188,  -1.3279,   7.9913,  -5.9573,
         -11.9771, -19.0526,  -8.7847, -10.9553, -12.6672,  -8.5991,   0.3197,
         -19.4793,  -9.0652, -13.5403, -15.8815,  -

tensor([[ -0.6301,  -3.0935, -14.3209, -18.2206, -19.0372,  -1.2869,  -3.4087,
           2.1668, -19.6392, -13.7200,  -0.9969,   1.3437,  -6.4698, -15.2497,
         -13.4620, -10.3176,   8.8543, -16.4211, -17.0402,  -6.8362, -16.0685,
         -18.2201, -22.2330,  -1.6641, -12.3931, -15.6912, -25.3726,  -8.1036,
          -3.8286,  -7.1003]])
tensor([[ 0.4824,  0.0072,  0.2772,  0.1222,  0.0624,  0.0009, -0.0773,  0.0285,
          0.2565,  0.1311,  0.0647,  0.1041,  0.2301,  0.1625, -0.1642, -0.2077,
          0.1796,  0.5530,  0.2065, -0.3014, -0.0863,  0.2897, -0.0189,  0.0540,
          0.3662,  0.0375,  0.2215,  0.3468,  0.0906,  0.3465]],
       grad_fn=<AddmmBackward0>)
i: 66
Mesh labels: [16]
tensor([[ -2.8135,  -2.5225, -11.0385, -16.2794, -16.3138,  -0.9228,  -4.0625,
          -1.3574, -16.6767, -11.8002,  -1.6141,  -1.7518,  -7.9940, -15.4949,
         -12.6014,  -9.4635,   7.6904, -11.7732, -14.5769,  -8.0263, -15.7957,
         -15.6577, -19.7226,  -1.5672, -10.5490, -1

tensor([[ -0.9398, -22.5821, -21.4887,  -6.3153,  -1.1521,  -5.7509,  -5.5441,
         -14.0662, -13.7762, -13.5974, -19.4549, -10.3509,  -1.6610,  -4.9267,
         -12.9887, -17.4118, -15.5724,  -6.1549,  -5.9195, -14.7092,   7.1912,
         -16.9145,  -9.2198, -13.0749, -19.5612,  -0.7572, -15.3230, -21.6191,
          -6.6983,  -9.1885]])
tensor([[ 0.4313,  0.0433,  0.2643,  0.1366,  0.0462,  0.0466, -0.0928, -0.0264,
          0.2296,  0.1721,  0.0844,  0.1528,  0.2131,  0.1313, -0.1762, -0.1589,
          0.1939,  0.5158,  0.1633, -0.2928, -0.0757,  0.2855, -0.0025,  0.0861,
          0.3178,  0.0249,  0.2089,  0.2904,  0.0541,  0.3288]],
       grad_fn=<AddmmBackward0>)
i: 81
Mesh labels: [20]
tensor([[ -0.6630, -25.3520, -25.4249,  -7.2448,  -1.0887,  -5.9956,  -5.7658,
         -14.7797, -15.9355, -15.4019, -21.8196, -10.4475,  -0.5207,  -4.7572,
         -14.8713, -19.8283, -16.9259,  -7.4369,  -7.5848, -15.6882,   8.5823,
         -18.7633,  -9.7143, -15.1403, -22.0597,  -

tensor([[ -2.9784,  -4.4604,  -1.8961,  -9.3151, -17.1384,  -6.3612,  -4.1701,
          -7.2187, -20.3217, -11.6831,  -3.7824, -12.5407, -23.2622, -21.8246,
         -10.2428,  -0.1535,  -3.3852, -14.7988,  -3.6948, -18.7315, -21.2843,
         -15.8201, -33.0464,   7.7941, -18.8109, -19.5735, -29.5446, -10.3507,
          -2.9813, -21.2939]])
tensor([[ 0.4308,  0.0533,  0.2583,  0.1503,  0.0696,  0.0670, -0.0545, -0.0297,
          0.1965,  0.1701,  0.0426,  0.1552,  0.1896,  0.1096, -0.1393, -0.1293,
          0.1857,  0.5000,  0.2064, -0.2758, -0.0538,  0.3129, -0.0127,  0.0682,
          0.3041,  0.0007,  0.1954,  0.2997,  0.0662,  0.3225]],
       grad_fn=<AddmmBackward0>)
i: 95
Mesh labels: [23]
tensor([[ -2.1636,  -5.2587,  -0.9725,  -8.3864, -15.1310,  -5.6785,  -4.3806,
          -7.5165, -18.6564, -11.3702,  -4.0861, -11.9357, -21.2485, -20.6205,
          -9.2940,  -0.4356,  -3.2191, -11.8320,  -1.3545, -18.3466, -18.7689,
         -14.9522, -30.3434,   7.8995, -17.5406, -1

tensor([[-11.6697,   3.3960, -17.8481,  -8.1336, -17.2165,  -0.0482,  -4.2415,
           1.5721, -22.6619,  -4.5480, -16.2465, -14.9818, -19.1218,  -3.0476,
         -17.8416,  -2.4885, -12.0148, -15.0151, -17.3778,  -9.8734, -23.5431,
           2.3325, -24.6308,  -8.5641, -22.1637, -22.3186, -17.2165,   9.9351,
         -18.2942, -22.0609]])
tensor([[ 0.4909,  0.0113,  0.3013,  0.1323,  0.0408,  0.0242, -0.1053,  0.0085,
          0.2922,  0.1525,  0.1186,  0.1320,  0.2507,  0.1582, -0.1616, -0.2019,
          0.2266,  0.6022,  0.2051, -0.3159, -0.0613,  0.3105,  0.0178,  0.0833,
          0.3966,  0.0523,  0.2270,  0.3238,  0.0798,  0.3493]],
       grad_fn=<AddmmBackward0>)
i: 110
Mesh labels: [27]
tensor([[-12.4871,   3.5003, -15.7322,  -7.8045, -17.2077,  -1.7667,  -4.4863,
           0.1399, -20.3842,  -4.1573, -14.3297, -15.1766, -19.9680,  -4.5139,
         -15.0436,  -1.9137, -12.2881, -15.4717, -16.3506,  -9.3267, -23.3840,
           0.3507, -23.5111,  -8.2575, -19.5659, -

tensor([[-11.5600, -12.2807,  -8.4907,   4.3490,  -3.9629,  -6.6956,  -5.1210,
         -17.6667, -16.9735,  -6.5677, -17.3407, -22.6724, -22.5112, -12.0273,
          -9.3018,  -2.4722, -22.2240,  -8.2088,   0.6924, -21.5803, -12.2139,
          -6.7683, -23.1302,  -5.0496, -22.1565, -13.7152, -21.1941, -12.2661,
         -10.6854, -24.5271]])
tensor([[ 0.4819,  0.0656,  0.3222,  0.1326,  0.0382,  0.0364, -0.1133, -0.0229,
          0.2936,  0.1715,  0.1236,  0.1631,  0.2505,  0.1529, -0.1933, -0.1975,
          0.2232,  0.6035,  0.2093, -0.3160, -0.0583,  0.3247,  0.0229,  0.1213,
          0.3876,  0.0787,  0.2388,  0.3460,  0.0873,  0.3568]],
       grad_fn=<AddmmBackward0>)
i: 13
Mesh labels: [3]
tensor([[-12.6880, -12.8750, -10.0355,   5.0915,  -2.9794,  -7.6716,  -4.5700,
         -18.3993, -15.3633,  -5.6254, -17.1177, -22.0048, -21.5706, -11.0255,
          -8.2964,  -3.0174, -23.5324, -10.5834,  -1.8890, -19.7286, -11.2272,
          -7.6164, -20.7858,  -7.4569, -21.0455, -11

tensor([[-14.5027, -13.2319, -21.4615, -12.8570, -17.1793, -11.6074,  -2.7180,
         -12.7763, -23.4383, -11.8774, -11.1201, -11.7537, -21.2265, -19.1802,
         -10.7729,  -9.0745, -16.8068, -27.7212, -18.5842, -12.0273, -22.8469,
         -23.7130, -26.2228, -11.3570, -20.5803, -15.3374, -26.3384, -21.8032,
         -11.9231, -15.5972]])
tensor([[ 0.5218,  0.0474,  0.3389,  0.1532,  0.0314,  0.0223, -0.1243, -0.0020,
          0.3228,  0.1688,  0.1693,  0.1311,  0.2717,  0.1688, -0.1667, -0.2196,
          0.2402,  0.6308,  0.1692, -0.3225, -0.0706,  0.3247,  0.0373,  0.1124,
          0.4310,  0.0594,  0.2324,  0.3292,  0.1042,  0.3578]],
       grad_fn=<AddmmBackward0>)
i: 26
Mesh labels: [6]
tensor([[-14.8296, -18.9902, -28.8402, -15.5756, -15.2484, -11.4294,  -2.6644,
         -13.2581, -24.5787, -13.1838, -15.5056,  -8.6107, -15.0708, -15.5415,
         -12.3020, -13.9708, -18.9744, -28.3200, -21.5157,  -9.3443, -19.8563,
         -25.5049, -21.4479, -16.4845, -22.2518, -11

tensor([[-28.4242,  -8.2474, -13.6672,  -8.3598, -13.4178, -15.0705,  -6.6848,
         -19.5868,  -9.2745,   2.4944, -16.3123, -23.3888, -29.2222, -11.4324,
          -6.3626,  -4.3604, -29.0648, -22.5601, -18.4032,  -6.6493, -27.5186,
         -11.1720, -10.5156, -19.5232, -12.9198, -14.4201,  -8.5507, -14.5739,
         -21.4568, -18.2314]])
tensor([[ 0.5075,  0.0800,  0.3606,  0.1531,  0.0810,  0.0436, -0.0780,  0.0099,
          0.2923,  0.1629,  0.0810,  0.1553,  0.2378,  0.1500, -0.1685, -0.1897,
          0.2192,  0.6141,  0.2874, -0.3082, -0.0510,  0.3423, -0.0037,  0.1067,
          0.3961,  0.0819,  0.2385,  0.3905,  0.1204,  0.3652]],
       grad_fn=<AddmmBackward0>)
i: 40
Mesh labels: [10]
tensor([[ -9.8054,  -3.0362,  -7.7672, -16.0421, -22.0341, -12.0270,  -2.7380,
          -6.8935, -11.8634, -10.3999,   5.5222,  -3.5391, -19.0065, -24.9962,
          -3.9015,  -6.5952,  -1.8166, -26.7677, -17.2053,  -4.8793, -22.5182,
         -27.6809, -20.6622,  -4.9033,  -3.8696, -1

i: 54
Mesh labels: [13]
tensor([[-13.8156, -12.8400, -23.8924,  -9.2676,  -7.2072,  -5.5136,  -4.7157,
          -7.4916, -14.0714,  -3.9144, -22.4206, -13.1019,  -8.7493,   5.0935,
         -12.8874, -10.2377, -20.8854, -15.0960, -16.5194,  -4.8228, -10.2136,
          -5.1903,  -9.4925, -18.2005, -20.1399,  -5.3534,  -0.6626,  -6.9383,
         -17.4111, -10.8901]])
tensor([[ 0.5108,  0.0802,  0.3522,  0.1591,  0.0553,  0.0509, -0.0925,  0.0020,
          0.3143,  0.1915,  0.1450,  0.1739,  0.2601,  0.1535, -0.1601, -0.1913,
          0.2278,  0.6038,  0.2115, -0.3172, -0.0579,  0.3326,  0.0172,  0.1125,
          0.4042,  0.0604,  0.2396,  0.3427,  0.1072,  0.3592]],
       grad_fn=<AddmmBackward0>)
i: 55
Mesh labels: [13]
tensor([[-14.7091, -18.4965, -29.1599, -10.0573,  -4.9917,  -5.9170,  -5.3289,
         -10.4114, -17.2106,  -6.2029, -27.3137, -14.5589,  -6.6187,   6.1483,
         -15.1838, -13.4674, -24.3929, -15.6845, -17.5054,  -7.2159,  -8.2009,
          -7.0815, -10.0279

i: 69
Mesh labels: [17]
tensor([[-12.6438, -13.2250, -12.0964,  -7.2383,  -1.8626,   1.8031,  -9.3824,
         -18.5628, -16.4985,  -8.6381, -22.9652, -20.3323, -11.1498,  -9.1867,
         -15.8007, -11.6935, -14.6234,   9.7318,  -1.4018, -20.2794, -10.1510,
          -1.4459, -12.6446,  -9.0394, -19.4796, -18.3401, -17.4143, -11.3812,
         -10.8086, -21.3691]])
tensor([[ 0.4741,  0.1139,  0.3539,  0.1605,  0.0515,  0.0711, -0.1051, -0.0343,
          0.3006,  0.2128,  0.1445,  0.2224,  0.2611,  0.1561, -0.1854, -0.1650,
          0.2270,  0.5841,  0.2093, -0.3198, -0.0494,  0.3331,  0.0177,  0.1409,
          0.3702,  0.0768,  0.2412,  0.3336,  0.0841,  0.3567]],
       grad_fn=<AddmmBackward0>)
i: 70
Mesh labels: [17]
tensor([[-12.2687, -12.3794, -11.0054,  -6.8599,  -1.9677,   1.5837,  -9.4217,
         -18.1577, -15.6965,  -8.2384, -22.2376, -20.2821, -11.4909,  -9.1650,
         -15.4076, -11.0496, -14.1956,   9.7812,  -1.0248, -20.0553,  -9.9837,
          -1.1009, -12.3787

tensor([[ -1.4082, -28.8877, -28.5914,  -8.7979,  -0.5778,  -6.2760,  -6.5575,
         -17.1247, -18.6616, -17.6456, -24.6916, -11.3942,   0.3745,  -5.6796,
         -16.3208, -22.4247, -18.7492,  -7.5498,  -8.1130, -17.7063,   8.6472,
         -20.7969, -10.7878, -16.7375, -24.6021,  -1.1031, -18.7841, -27.7896,
          -7.6476, -10.3044]])
tensor([[ 0.5489,  0.0608,  0.3912,  0.1549,  0.0403,  0.0388, -0.1296,  0.0231,
          0.3713,  0.1965,  0.1948,  0.1857,  0.3192,  0.1997, -0.1726, -0.2161,
          0.2854,  0.7005,  0.2582, -0.3443, -0.0567,  0.3298,  0.0270,  0.1116,
          0.4517,  0.0942,  0.2641,  0.3645,  0.1135,  0.3834]],
       grad_fn=<AddmmBackward0>)
i: 84
Mesh labels: [21]
tensor([[-16.9386,  -6.8993, -13.9714,  -2.1039,  -2.3359,   1.2923,  -6.6079,
         -13.9512, -18.7974,  -2.7846, -24.4515, -23.0021, -16.5929,  -2.0839,
         -16.8218,  -4.0640, -20.5056,   0.1491,  -6.9824, -17.5369, -16.2591,
           8.9416, -17.2292, -10.9651, -23.5076, -1

tensor([[-21.1276, -13.8278, -17.8025,  -9.8308,  -6.5154, -12.9167,  -5.6215,
         -15.2185,  -5.4175,  -0.1052, -18.7047, -14.6672, -13.5262,   0.5832,
          -4.0985,  -8.7271, -24.9130, -17.5451, -15.6229,  -0.9495, -14.1109,
         -10.3972,  -2.3298, -19.7104, -11.7172,  -2.0794,   8.0094, -14.7358,
         -15.0662,  -6.3268]])
tensor([[ 5.6017e-01,  5.5858e-02,  3.9710e-01,  1.6676e-01,  3.2445e-03,
          5.1612e-02, -1.6804e-01, -3.4992e-05,  4.1683e-01,  2.1394e-01,
          2.7516e-01,  1.9413e-01,  3.4106e-01,  2.0060e-01, -1.6346e-01,
         -2.2725e-01,  3.0788e-01,  7.2351e-01,  1.7180e-01, -3.5735e-01,
         -4.2920e-02,  3.4972e-01,  8.2591e-02,  1.4560e-01,  4.9346e-01,
          9.0986e-02,  2.5490e-01,  3.1253e-01,  9.8470e-02,  3.7900e-01]],
       grad_fn=<AddmmBackward0>)
i: 106
Mesh labels: [26]
tensor([[-22.2103, -14.2283, -17.4416, -10.3296,  -7.0518, -14.0602,  -6.0426,
         -16.4692,  -4.8842,  -0.1681, -18.6683, -15.5927, -14.7723,  

epoch: 4, loss: 1294.3429422862828
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822, -22.9073,  -3.3643, -25.6530,  -7.8275, -25.9369, -18.4495,
          -3.2837, -13.6820]])
tensor([[ 0.5744,  0.0653,  0.4064,  0.1608,  0.0283,  0.0560, -0.1263,  0.0189,
          0.4077,  0.2094,  0.2507,  0.1819,  0.3374,  0.1985, -0.1264, -0.2152,
          0.3034,  0.7317,  0.2277, -0.3460, -0.0485,  0.3679,  0.0674,  0.1340,
          0.5088,  0.0944,  0.2760,  0.3635,  0.1309,  0.3823]],
       grad_fn=<AddmmBackward0>)
i: 1
Mesh labels: [0]
tensor([[  6.3456, -20.1829, -23.7263, -11.1970, -10.4479,  -3.5765,  -4.1582,
          -5.3284, -26.1639, -20.5226, -15.8104,  -4.7861,  -4.6728, -11.7994,
         -17.7693, -14.5876,  -7.8231, -13.3061,  -7.3532, -18.4909,  -1.75

i: 12
Mesh labels: [3]
tensor([[-11.5600, -12.2807,  -8.4907,   4.3490,  -3.9629,  -6.6956,  -5.1210,
         -17.6667, -16.9735,  -6.5677, -17.3407, -22.6724, -22.5112, -12.0273,
          -9.3018,  -2.4722, -22.2240,  -8.2088,   0.6924, -21.5803, -12.2139,
          -6.7683, -23.1302,  -5.0496, -22.1565, -13.7152, -21.1941, -12.2661,
         -10.6854, -24.5271]])
tensor([[ 0.5940,  0.1050,  0.4443,  0.1601,  0.0193,  0.0507, -0.1510,  0.0039,
          0.4387,  0.2192,  0.2650,  0.2173,  0.3518,  0.2139, -0.1756, -0.2391,
          0.3108,  0.7601,  0.2445, -0.3666, -0.0359,  0.3740,  0.0728,  0.1644,
          0.5172,  0.1326,  0.2985,  0.3891,  0.1399,  0.4111]],
       grad_fn=<AddmmBackward0>)
i: 13
Mesh labels: [3]
tensor([[-12.6880, -12.8750, -10.0355,   5.0915,  -2.9794,  -7.6716,  -4.5700,
         -18.3993, -15.3633,  -5.6254, -17.1177, -22.0048, -21.5706, -11.0255,
          -8.2964,  -3.0174, -23.5324, -10.5834,  -1.8890, -19.7286, -11.2272,
          -7.6164, -20.7858, 

tensor([[ -5.3056,  -3.2552, -24.4040, -15.7908, -21.0671,  -1.8737,  -2.4133,
           5.9620, -26.3756, -11.7919, -10.4324,  -3.8186, -11.6785,  -7.7541,
         -17.2509,  -8.5960,  -5.1452, -24.3250, -22.0715,  -5.9061, -20.2019,
         -13.2944, -26.0743,  -8.6056, -21.3844, -17.4667, -22.8803,  -1.7048,
         -12.7513, -12.7094]])
tensor([[ 0.6088,  0.1157,  0.4577,  0.1866,  0.0559,  0.0665, -0.1063,  0.0193,
          0.4080,  0.2136,  0.2316,  0.2022,  0.3299,  0.2012, -0.1246, -0.2129,
          0.2995,  0.7377,  0.2800, -0.3455, -0.0330,  0.3812,  0.0520,  0.1417,
          0.5107,  0.1041,  0.2853,  0.4013,  0.1617,  0.4079]],
       grad_fn=<AddmmBackward0>)
i: 29
Mesh labels: [7]
tensor([[ -4.8895,  -2.3995, -24.5613, -17.8141, -22.8905,  -1.8075,  -2.1679,
           7.4466, -26.3032, -12.3963,  -8.0546,  -1.4604, -11.1244,  -9.0692,
         -17.2034,  -9.4489,  -1.9529, -25.8494, -23.8965,  -4.3958, -21.3874,
         -15.2626, -26.1622,  -8.3694, -19.8813, -17

tensor([[-11.6718,  -2.5958,  -7.4301, -17.4365, -22.3056, -12.8318,  -3.5272,
          -7.7282,  -8.9709,  -9.8538,   6.2881,  -3.5478, -18.7555, -25.7640,
          -2.9329,  -8.6665,  -1.8150, -26.8913, -18.5183,  -3.0664, -22.5987,
         -29.0522, -17.2185,  -7.3923,  -0.4747, -14.0919, -24.0024, -20.0172,
          -3.5677,  -3.6322]])
tensor([[ 0.5349,  0.1719,  0.4417,  0.1966,  0.0871,  0.1157, -0.0766, -0.0189,
          0.3462,  0.2392,  0.1609,  0.2391,  0.2758,  0.1492, -0.1376, -0.1502,
          0.2660,  0.6634,  0.3118, -0.3122, -0.0198,  0.3946,  0.0308,  0.1649,
          0.4317,  0.1033,  0.2588,  0.3943,  0.1414,  0.3771]],
       grad_fn=<AddmmBackward0>)
i: 43
Mesh labels: [10]
tensor([[-10.7335,  -0.9883,  -5.9118, -16.8425, -23.7691, -12.3235,  -3.3852,
          -6.6129, -10.4517,  -9.9265,   6.6998,  -4.5129, -20.9599, -26.4770,
          -3.8285,  -6.6393,  -0.8745, -27.1926, -17.8756,  -4.7551, -24.2907,
         -27.9905, -21.0365,  -4.9740,  -2.2693, -1

tensor([[-21.4707, -13.9661, -16.1697, -14.6637, -16.3941, -18.7427,  -4.9147,
         -18.6840, -11.5659,  -7.9881,  -5.5664, -10.4812, -20.3619, -21.8610,
           0.5679, -10.2627, -19.5201, -28.6709, -18.7085,  -3.4616, -22.6568,
         -30.3811, -12.7136, -16.7934,  -5.8713,  -9.9556, -15.9495, -29.8133,
          -7.3802,  -3.8246]])
tensor([[ 0.5548,  0.1614,  0.4336,  0.2033,  0.0531,  0.1151, -0.0930, -0.0187,
          0.3797,  0.2650,  0.2472,  0.2540,  0.3119,  0.1659, -0.1183, -0.1610,
          0.2788,  0.6614,  0.2143, -0.3290, -0.0307,  0.3812,  0.0568,  0.1660,
          0.4556,  0.0730,  0.2645,  0.3392,  0.1321,  0.3752]],
       grad_fn=<AddmmBackward0>)
i: 57
Mesh labels: [14]
tensor([[-25.2615, -12.0304, -10.8018,  -9.0621, -13.4911, -19.4136,  -6.4499,
         -22.1677,  -8.5282,  -3.3381,  -8.4765, -17.5523, -25.4429, -19.2563,
           2.7891,  -5.2515, -25.0346, -24.4857, -14.3460,  -5.8762, -24.1586,
         -23.2186, -11.9233, -15.8933,  -6.0431, -1

tensor([[-6.2986e+00, -1.4855e+01, -3.5309e+00, -8.1529e-01, -4.1161e+00,
         -6.1413e+00, -6.8259e+00, -1.7979e+01, -1.5671e+01, -1.0479e+01,
         -1.5762e+01, -2.0051e+01, -1.9114e+01, -1.5945e+01, -8.6165e+00,
         -4.9670e+00, -1.6503e+01,  1.3988e-02,  8.8768e+00, -2.3821e+01,
         -9.2150e+00, -1.0617e+01, -2.1571e+01,  8.9185e-01, -1.9702e+01,
         -1.3353e+01, -2.1542e+01, -1.5760e+01, -3.3180e+00, -2.1598e+01]])
tensor([[ 0.5658,  0.1791,  0.4927,  0.1916,  0.0628,  0.1060, -0.1312, -0.0131,
          0.4257,  0.2662,  0.2444,  0.2954,  0.3561,  0.2069, -0.1785, -0.1844,
          0.3172,  0.7519,  0.3233, -0.3565, -0.0199,  0.3973,  0.0487,  0.1911,
          0.4789,  0.1553,  0.2956,  0.4111,  0.1388,  0.4064]],
       grad_fn=<AddmmBackward0>)
i: 73
Mesh labels: [18]
tensor([[ -6.4295, -14.6801,  -4.1200,  -0.1680,  -4.3292,  -6.5845,  -6.2795,
         -17.6786, -15.8085, -10.2893, -15.0795, -19.4315, -19.0610, -15.7840,
          -7.7838,  -4.5055, -1

tensor([[-17.0619,  -6.1322, -14.4201,  -2.2379,  -3.1992,   1.1163,  -6.3601,
         -13.0705, -19.2036,  -2.5457, -24.2670, -22.8753, -17.2121,  -1.7657,
         -16.9953,  -3.6071, -20.4923,  -0.9556,  -7.7561, -17.0529, -17.0617,
           9.1876, -17.7948, -11.0359, -23.7143, -19.0768, -12.6307,  -0.7818,
         -19.1150, -26.6659]])
tensor([[ 0.6283,  0.1422,  0.5065,  0.1931,  0.0878,  0.0973, -0.0813,  0.0506,
          0.4347,  0.2436,  0.2268,  0.2537,  0.3704,  0.2193, -0.1085, -0.1875,
          0.3426,  0.8086,  0.4217, -0.3483, -0.0091,  0.4014,  0.0267,  0.1307,
          0.5220,  0.1329,  0.3040,  0.4520,  0.1840,  0.4194]],
       grad_fn=<AddmmBackward0>)
i: 86
Mesh labels: [21]
tensor([[-16.7548,  -8.9297, -16.2944,  -1.9696,  -1.4119,   2.3184,  -6.9051,
         -14.3801, -21.2906,  -4.0274, -27.1826, -23.5177, -15.4157,  -1.2381,
         -18.4288,  -5.0259, -21.6452,   0.9273,  -6.7008, -19.1735, -15.5576,
           9.5294, -18.1917, -11.5982, -26.3427, -1

tensor([[-18.4914,  -2.5141,  -3.0341, -16.2558, -16.3363, -15.5074,  -6.1396,
         -14.6389,   2.9598,  -4.3091,   4.1932,  -7.2936, -17.5361, -23.7909,
           1.3354, -10.9404,  -7.1928, -21.2081, -16.6639,   0.3837, -20.1071,
         -25.7336,  -1.9913, -13.5198,   9.2745, -10.4970, -13.5939, -22.3916,
          -4.7737,   0.1360]])
tensor([[ 0.6636,  0.1331,  0.5390,  0.2007,  0.0702,  0.0923, -0.1221,  0.0566,
          0.4925,  0.2489,  0.2804,  0.2566,  0.4078,  0.2387, -0.1225, -0.2246,
          0.3770,  0.8814,  0.4122, -0.3736,  0.0045,  0.4376,  0.0655,  0.1591,
          0.5783,  0.1532,  0.3114,  0.4536,  0.1923,  0.4313]],
       grad_fn=<AddmmBackward0>)
i: 100
Mesh labels: [25]
tensor([[ -7.4048, -22.1733, -15.2929,  -6.4625,  -5.3935, -12.9865,  -5.0201,
         -18.1305, -11.8294, -10.7239, -16.0824, -12.8918, -12.5425, -11.4209,
          -7.5349, -11.3807, -20.0058, -15.6435,  -5.4711, -14.6736,  -5.6768,
         -20.9887, -15.0176,  -9.4945, -18.9987,  

i: 112
Mesh labels: [28]
tensor([[ -5.8569, -17.1732, -16.0355, -13.5276, -10.2626,  -9.1844,  -7.3393,
         -12.9768, -21.0234, -17.2835, -10.6263,  -8.2262,  -6.1174, -17.7692,
          -6.0121, -12.6738, -10.1427, -12.3989,  -5.9187, -13.9268, -10.6636,
         -24.2125, -19.0938,  -5.8990, -14.1034, -11.9026, -21.6151, -24.4874,
           4.5554,  -6.2897]])
tensor([[ 0.6344,  0.1678,  0.5486,  0.1976,  0.0632,  0.1183, -0.1330,  0.0169,
          0.4995,  0.2698,  0.2983,  0.2953,  0.4013,  0.2275, -0.1369, -0.2055,
          0.3728,  0.8655,  0.4005, -0.3722,  0.0132,  0.4413,  0.0825,  0.1999,
          0.5708,  0.1873,  0.3278,  0.4496,  0.1703,  0.4289]],
       grad_fn=<AddmmBackward0>)
i: 113
Mesh labels: [28]
tensor([[ -4.8389, -13.3492, -11.8402, -10.3433,  -8.1231,  -7.8504,  -5.8732,
         -10.6877, -16.1425, -13.5259,  -7.8879,  -6.8806,  -5.6496, -14.6860,
          -4.1500,  -9.5984,  -8.2781, -10.0454,  -4.2218, -11.1815,  -8.6002,
         -19.4825, -15.17

tensor([[-11.5600, -12.2807,  -8.4907,   4.3490,  -3.9629,  -6.6956,  -5.1210,
         -17.6667, -16.9735,  -6.5677, -17.3407, -22.6724, -22.5112, -12.0273,
          -9.3018,  -2.4722, -22.2240,  -8.2088,   0.6924, -21.5803, -12.2139,
          -6.7683, -23.1302,  -5.0496, -22.1565, -13.7152, -21.1941, -12.2661,
         -10.6854, -24.5271]])
tensor([[ 0.6100,  0.2402,  0.5475,  0.2054,  0.0807,  0.1471, -0.0992, -0.0202,
          0.4509,  0.2885,  0.2605,  0.3290,  0.3650,  0.1974, -0.1337, -0.1623,
          0.3441,  0.8077,  0.4073, -0.3512,  0.0226,  0.4557,  0.0700,  0.2232,
          0.5252,  0.1766,  0.3237,  0.4642,  0.1870,  0.4295]],
       grad_fn=<AddmmBackward0>)
i: 13
Mesh labels: [3]
tensor([[-12.6880, -12.8750, -10.0355,   5.0915,  -2.9794,  -7.6716,  -4.5700,
         -18.3993, -15.3633,  -5.6254, -17.1177, -22.0048, -21.5706, -11.0255,
          -8.2964,  -3.0174, -23.5324, -10.5834,  -1.8890, -19.7286, -11.2272,
          -7.6164, -20.7858,  -7.4569, -21.0455, -11

tensor([[-19.2015,  -7.6961,   1.6663,  -8.8975, -10.2675, -17.7330,  -7.1715,
         -21.1468,   8.0029,  -0.9143,  -2.3878, -15.6646, -21.4830, -19.1768,
           1.4798,  -8.8586, -16.8805, -17.7200,  -9.9703,  -4.9373, -16.2723,
         -20.4854,  -1.9121, -13.1078,   3.5726,  -5.5224,  -8.5240, -22.3871,
          -8.0703,  -6.2767]])
tensor([[ 0.7264,  0.2308,  0.6602,  0.2331,  0.0722,  0.1154, -0.1742,  0.0435,
          0.5895,  0.2893,  0.3682,  0.3244,  0.4568,  0.2740, -0.1669, -0.2605,
          0.4136,  0.9707,  0.4279, -0.4098,  0.0229,  0.4711,  0.1018,  0.2475,
          0.6526,  0.2387,  0.3740,  0.5122,  0.2323,  0.4895]],
       grad_fn=<AddmmBackward0>)
i: 34
Mesh labels: [8]
tensor([[-19.5553,  -9.0141,   0.4047,  -7.3339,  -8.1700, -16.3926,  -7.2686,
         -21.7274,   6.5232,  -0.0488,  -5.9658, -17.7499, -21.4305, -16.0496,
          -0.1440,  -8.5923, -19.3170, -15.4958,  -9.0545,  -6.1904, -15.2726,
         -17.1233,  -1.7141, -13.4231,   0.0432,  -5

tensor([[ -2.5661, -21.2394, -26.3129, -14.7674,  -3.7861,  -3.7560,  -5.4643,
          -9.4294, -18.3040, -16.3390, -16.4038,  -1.9755,   8.2599,  -6.0303,
         -12.2086, -19.6346,  -8.9211,  -9.9889, -12.6845,  -8.9282,   0.3199,
         -19.3350,  -8.5402, -14.0364, -15.6637,  -3.0256, -14.8129, -23.2933,
          -2.2081,  -1.1620]])
tensor([[ 0.7577,  0.2052,  0.6510,  0.2345,  0.0765,  0.1172, -0.1319,  0.0932,
          0.6096,  0.3021,  0.3965,  0.2897,  0.4590,  0.2701, -0.0934, -0.2490,
          0.4153,  0.9593,  0.4030, -0.3961,  0.0096,  0.4642,  0.0984,  0.2069,
          0.6794,  0.1919,  0.3672,  0.4923,  0.2549,  0.4745]],
       grad_fn=<AddmmBackward0>)
i: 49
Mesh labels: [12]
tensor([[ -3.2944, -21.3041, -26.1382, -13.8697,  -3.2115,  -3.7217,  -5.3201,
          -9.9961, -18.0025, -15.4822, -17.2332,  -2.9626,   7.4967,  -5.2281,
         -12.2308, -19.1271, -10.1265,  -9.5373, -12.3120,  -9.0514,   0.3120,
         -18.1385,  -8.3750, -14.4281, -16.2261,  -

tensor([[-19.9811,  -3.2688,  -9.8115,  -5.4409, -17.3085, -11.4882,  -4.0934,
         -12.9378, -18.6973,  -2.0675, -10.4864, -20.3790, -31.4290, -15.7766,
          -7.7291,   3.1661, -21.0931, -23.4110, -14.0149, -12.3903, -29.9898,
         -10.2178, -26.6320,  -7.5362, -18.3749, -20.0576, -20.0128,  -8.6369,
         -16.0728, -22.9694]])
tensor([[ 0.7353,  0.2335,  0.6525,  0.2391,  0.0640,  0.1325, -0.1486,  0.0596,
          0.6127,  0.3295,  0.4228,  0.3447,  0.4861,  0.2851, -0.1165, -0.2431,
          0.4134,  0.9474,  0.3826, -0.4049,  0.0115,  0.4645,  0.1051,  0.2299,
          0.6597,  0.2032,  0.3726,  0.4732,  0.2337,  0.4740]],
       grad_fn=<AddmmBackward0>)
i: 62
Mesh labels: [15]
tensor([[-13.5558,  -5.7115,  -8.9670,  -4.8370, -14.3079, -10.1167,  -3.0017,
         -10.8677, -17.7850,  -5.0375,  -7.2967, -14.0767, -23.6237, -15.2642,
          -5.4349,   2.0814, -15.8247, -20.4009, -10.2259, -11.5918, -22.9732,
         -12.6988, -24.7677,  -4.2275, -16.1622, -1

tensor([[ -6.2519, -15.5311,  -4.6246,   0.0701,  -3.5657,  -6.7552,  -6.3899,
         -18.1952, -15.8199, -10.5677, -15.7134, -19.7100, -18.7206, -15.6698,
          -8.1301,  -5.1543, -17.3226,  -1.5431,   8.1775, -23.3953,  -8.3856,
         -11.3226, -21.4789,   0.1169, -19.7186, -12.2818, -21.5529, -16.7451,
          -3.3739, -20.9313]])
tensor([[ 0.7056,  0.2839,  0.6976,  0.2368,  0.0991,  0.1581, -0.1571,  0.0375,
          0.6045,  0.3392,  0.3634,  0.4118,  0.4862,  0.2849, -0.1710, -0.2126,
          0.4398,  0.9961,  0.5276, -0.4129,  0.0419,  0.4904,  0.0808,  0.2615,
          0.6304,  0.2733,  0.3857,  0.5446,  0.2334,  0.4909]],
       grad_fn=<AddmmBackward0>)
i: 76
Mesh labels: [19]
tensor([[-24.1717, -11.1630, -23.9647, -18.4104, -16.9953, -15.0570,  -4.8745,
         -12.1350, -11.8412,  -4.0405, -11.2920,  -9.0411, -16.1607, -11.2677,
          -4.5028, -12.6259, -20.6682, -29.0327, -26.2487,   4.0097, -23.4977,
         -23.0184,  -5.2591, -23.6639,  -7.2481,  -

tensor([[-21.8248, -15.1292, -15.4215, -13.5570,  -6.3741, -14.9675,  -7.6623,
         -21.0492,  -0.1989,  -2.2009, -12.4088, -11.9550, -11.2910, -10.2320,
          -2.9593, -15.5360, -20.9877, -16.1200, -17.2124,  -0.5606, -12.3409,
         -19.7366,   8.4618, -23.1250,  -2.1550,  -3.5720,  -2.3702, -25.6527,
         -12.1592,  -2.6778]])
tensor([[ 0.7511,  0.2418,  0.6920,  0.2450,  0.0863,  0.1633, -0.1378,  0.0733,
          0.6217,  0.3372,  0.4072,  0.3707,  0.5071,  0.2916, -0.0965, -0.2094,
          0.4692,  1.0276,  0.5164, -0.3992,  0.0521,  0.4892,  0.0920,  0.2166,
          0.6705,  0.2283,  0.3809,  0.5163,  0.2492,  0.4890]],
       grad_fn=<AddmmBackward0>)
i: 90
Mesh labels: [22]
tensor([[-21.2384, -18.9784, -18.9435, -14.0430,  -5.6121, -15.6072,  -7.5156,
         -21.7006,  -2.0901,  -3.5385, -15.3556, -11.6082,  -9.1916,  -8.4153,
          -3.5637, -17.0077, -23.0643, -17.1053, -17.4319,  -1.0247, -10.6441,
         -21.1512,   7.3846, -24.3821,  -5.0300,  -

i: 105
Mesh labels: [26]
tensor([[-21.1276, -13.8278, -17.8025,  -9.8308,  -6.5154, -12.9167,  -5.6215,
         -15.2185,  -5.4175,  -0.1052, -18.7047, -14.6672, -13.5262,   0.5832,
          -4.0985,  -8.7271, -24.9130, -17.5451, -15.6229,  -0.9495, -14.1109,
         -10.3972,  -2.3298, -19.7104, -11.7172,  -2.0794,   8.0094, -14.7358,
         -15.0662,  -6.3268]])
tensor([[ 0.8668,  0.2405,  0.8133,  0.2513,  0.0683,  0.1396, -0.2152,  0.1173,
          0.7952,  0.3433,  0.5293,  0.3930,  0.6170,  0.3664, -0.1275, -0.3071,
          0.5580,  1.2431,  0.5937, -0.4652,  0.0788,  0.5514,  0.1579,  0.2787,
          0.8400,  0.3313,  0.4334,  0.5891,  0.2973,  0.5451]],
       grad_fn=<AddmmBackward0>)
i: 106
Mesh labels: [26]
tensor([[-22.2103, -14.2283, -17.4416, -10.3296,  -7.0518, -14.0602,  -6.0426,
         -16.4692,  -4.8842,  -0.1681, -18.6683, -15.5927, -14.7723,  -0.5350,
          -3.7112,  -9.0139, -25.7566, -18.5038, -15.9934,  -1.2614, -14.9617,
         -11.6368,  -2.33

tensor([[-18.8807, -12.3198, -21.9328, -17.8029, -16.0201, -14.3143,  -4.0312,
         -10.8912, -11.3684,  -6.8313,  -7.8095,  -4.8690, -11.8939, -12.9485,
          -2.8966, -13.0286, -15.8504, -27.3249, -22.9779,   3.0996, -19.1669,
         -25.8141,  -6.5076, -19.8380,  -5.8325,  -7.0266,  -8.9947, -23.0040,
          -9.8068,   1.2095]])
tensor([[ 0.7242,  0.2957,  0.7072,  0.2439,  0.1074,  0.2061, -0.1074,  0.0450,
          0.6137,  0.3548,  0.3953,  0.4014,  0.4859,  0.2629, -0.0709, -0.1713,
          0.4581,  1.0109,  0.5545, -0.3837,  0.0722,  0.5352,  0.1162,  0.2675,
          0.6752,  0.2564,  0.3986,  0.5521,  0.2651,  0.4820]],
       grad_fn=<AddmmBackward0>)
epoch: 6, loss: 1155.4194442480803
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.8722,
         -19.7822,

tensor([[-12.6880, -12.8750, -10.0355,   5.0915,  -2.9794,  -7.6716,  -4.5700,
         -18.3993, -15.3633,  -5.6254, -17.1177, -22.0048, -21.5706, -11.0255,
          -8.2964,  -3.0174, -23.5324, -10.5834,  -1.8890, -19.7286, -11.2272,
          -7.6164, -20.7858,  -7.4569, -21.0455, -11.4676, -19.3902, -13.6317,
         -11.7398, -22.7251]])
tensor([[ 0.7741,  0.3389,  0.7592,  0.2515,  0.1057,  0.2039, -0.1226,  0.0474,
          0.6541,  0.3674,  0.4221,  0.4197,  0.5123,  0.2808, -0.0873, -0.1933,
          0.4780,  1.0619,  0.5823, -0.3909,  0.0791,  0.5544,  0.1255,  0.2912,
          0.7111,  0.2866,  0.4181,  0.5863,  0.2967,  0.5136]],
       grad_fn=<AddmmBackward0>)
i: 14
Mesh labels: [3]
tensor([[-13.9660, -12.2713, -12.0443,   5.6351,  -3.6740,  -6.9553,  -4.5959,
         -17.9461, -17.6826,  -5.2133, -19.0052, -23.7066, -23.1402,  -9.8901,
         -10.1013,  -2.3390, -25.3224, -11.6810,  -3.6288, -20.4719, -12.9614,
          -5.8187, -22.8622,  -8.5795, -23.6955, -13

tensor([[ -5.3056,  -3.2552, -24.4040, -15.7908, -21.0671,  -1.8737,  -2.4133,
           5.9620, -26.3756, -11.7919, -10.4324,  -3.8186, -11.6785,  -7.7541,
         -17.2509,  -8.5960,  -5.1452, -24.3250, -22.0715,  -5.9061, -20.2019,
         -13.2944, -26.0743,  -8.6056, -21.3844, -17.4667, -22.8803,  -1.7048,
         -12.7513, -12.7094]])
tensor([[ 0.9178,  0.3425,  0.9032,  0.2882,  0.1129,  0.1796, -0.1888,  0.1158,
          0.8152,  0.3728,  0.5406,  0.4224,  0.6215,  0.3690, -0.1026, -0.2924,
          0.5628,  1.2646,  0.6548, -0.4502,  0.0900,  0.5860,  0.1579,  0.3140,
          0.8680,  0.3641,  0.4800,  0.6653,  0.3632,  0.5841]],
       grad_fn=<AddmmBackward0>)
i: 29
Mesh labels: [7]
tensor([[ -4.8895,  -2.3995, -24.5613, -17.8141, -22.8905,  -1.8075,  -2.1679,
           7.4466, -26.3032, -12.3963,  -8.0546,  -1.4604, -11.1244,  -9.0692,
         -17.2034,  -9.4489,  -1.9529, -25.8494, -23.8965,  -4.3958, -21.3874,
         -15.2626, -26.1622,  -8.3694, -19.8813, -17

tensor([[-10.7335,  -0.9883,  -5.9118, -16.8425, -23.7691, -12.3235,  -3.3852,
          -6.6129, -10.4517,  -9.9265,   6.6998,  -4.5129, -20.9599, -26.4770,
          -3.8285,  -6.6393,  -0.8745, -27.1926, -17.8756,  -4.7551, -24.2907,
         -27.9905, -21.0365,  -4.9740,  -2.2693, -15.9242, -26.1038, -17.7034,
          -3.6896,  -6.1695]])
tensor([[ 0.8601,  0.3596,  0.8660,  0.2871,  0.1458,  0.2162, -0.1276,  0.1263,
          0.7563,  0.3859,  0.4682,  0.4160,  0.5603,  0.3181, -0.0723, -0.2311,
          0.5193,  1.1633,  0.6610, -0.4092,  0.0923,  0.5755,  0.1283,  0.2931,
          0.7939,  0.3275,  0.4495,  0.6453,  0.3545,  0.5506]],
       grad_fn=<AddmmBackward0>)
i: 44
Mesh labels: [11]
tensor([[ -1.8415, -14.3549, -27.4199, -21.6404, -19.2456,  -6.6965,  -1.7176,
          -0.5529, -24.7352, -18.7934,  -4.2435,   6.6159,  -1.9919, -16.5774,
         -12.2038, -16.6825,   0.7559, -27.3295, -22.7109,  -4.0940, -14.1427,
         -30.2774, -20.9690,  -9.5340, -15.8455,  -

tensor([[-20.3809, -13.3521, -10.1346, -11.6553, -13.3656, -19.2275,  -5.9840,
         -20.2482,  -6.5062,  -6.6484,  -4.9090, -11.8888, -19.6884, -20.8907,
           3.5689,  -8.4722, -19.5445, -23.8601, -13.2722,  -4.5353, -19.6709,
         -27.9231, -10.0866, -14.3799,  -2.6616,  -7.7665, -12.2356, -28.6508,
          -4.5376,  -3.2128]])
tensor([[ 0.9255,  0.3661,  0.9178,  0.3018,  0.1009,  0.2092, -0.1920,  0.1347,
          0.8687,  0.4360,  0.6249,  0.4803,  0.6649,  0.3857, -0.0895, -0.2844,
          0.5710,  1.2530,  0.5865, -0.4637,  0.0874,  0.5784,  0.1736,  0.3283,
          0.8753,  0.3472,  0.4932,  0.6189,  0.3563,  0.5810]],
       grad_fn=<AddmmBackward0>)
i: 59
Mesh labels: [14]
tensor([[-20.5121, -10.8599,  -7.5975, -11.9631, -13.1542, -18.6488,  -6.4280,
         -20.0937,  -4.2401,  -6.0960,  -2.7362, -11.5782, -19.2985, -22.1444,
           4.0644,  -8.5918, -17.2663, -21.8911, -12.9144,  -3.9298, -19.6721,
         -27.1996,  -7.6258, -14.0386,   0.8437,  -

tensor([[ -6.4295, -14.6801,  -4.1200,  -0.1680,  -4.3292,  -6.5845,  -6.2795,
         -17.6786, -15.8085, -10.2893, -15.0795, -19.4315, -19.0610, -15.7840,
          -7.7838,  -4.5055, -16.7387,  -1.5443,   8.1127, -22.9785,  -9.2824,
         -11.0889, -21.8150,   0.4739, -19.2742, -12.8191, -21.3896, -15.9492,
          -3.1681, -20.7893]])
tensor([[ 0.9028,  0.3754,  0.9119,  0.3035,  0.0932,  0.2361, -0.1946,  0.1124,
          0.8550,  0.4581,  0.6371,  0.5178,  0.6696,  0.3924, -0.0671, -0.2321,
          0.5947,  1.2403,  0.5653, -0.4619,  0.0909,  0.5674,  0.1780,  0.3351,
          0.8495,  0.3389,  0.4950,  0.5945,  0.3353,  0.5798]],
       grad_fn=<AddmmBackward0>)
i: 74
Mesh labels: [18]
tensor([[ -6.8667, -15.2529,  -4.2042,   0.6357,  -4.3796,  -7.5659,  -6.3964,
         -18.6289, -16.0172, -10.4212, -15.2902, -20.4248, -20.2556, -16.4315,
          -7.5203,  -4.4047, -18.0207,  -2.8373,   7.9993, -23.6170,  -9.4781,
         -11.8062, -22.7356,   0.1718, -19.7938, -1

tensor([[-17.1850,  -7.1073, -14.7938,  -1.7395,  -2.3789,   1.4221,  -6.6295,
         -13.9747, -20.0892,  -2.9650, -25.4700, -23.6302, -17.1402,  -1.8111,
         -17.4176,  -3.7117, -21.3280,  -0.1791,  -7.0395, -18.3350, -16.8462,
           9.6003, -18.4236, -11.0242, -24.9167, -19.4055, -13.2250,  -1.3964,
         -19.1988, -27.6331]])
tensor([[ 0.8723,  0.3856,  0.9063,  0.2974,  0.1484,  0.2677, -0.1269,  0.1271,
          0.7901,  0.4366,  0.5288,  0.4990,  0.6338,  0.3543, -0.0397, -0.1835,
          0.5903,  1.2444,  0.7482, -0.4077,  0.1279,  0.5829,  0.1315,  0.2908,
          0.8039,  0.3465,  0.4680,  0.6505,  0.3539,  0.5634]],
       grad_fn=<AddmmBackward0>)
i: 88
Mesh labels: [22]
tensor([[-24.1869, -16.2579, -18.5360, -14.4957,  -6.7891, -15.6602,  -7.5203,
         -21.3831,  -1.1955,  -1.4690, -14.5474, -12.5893, -12.0231,  -8.8962,
          -3.5067, -15.8422, -23.6550, -18.1094, -19.6146,   0.5762, -14.0230,
         -19.8573,   9.2143, -25.6817,  -3.6654,  -

tensor([[ 0.9190,  0.3969,  0.9578,  0.3083,  0.1512,  0.2818, -0.1404,  0.1434,
          0.8523,  0.4463,  0.5733,  0.5157,  0.6711,  0.3717, -0.0265, -0.2050,
          0.6275,  1.3274,  0.7903, -0.4256,  0.1572,  0.6395,  0.1760,  0.3276,
          0.8745,  0.3710,  0.4832,  0.6772,  0.3812,  0.5807]],
       grad_fn=<AddmmBackward0>)
i: 102
Mesh labels: [25]
tensor([[-11.3650, -25.5086, -23.8257,  -9.8779,  -2.8680, -14.9700,  -4.6951,
         -18.6867,  -7.7704,  -8.8725, -18.9919,  -9.7815,  -5.2168,  -4.0773,
          -7.1178, -16.8865, -23.2980, -19.4247, -13.4267,  -7.0261,  -1.6310,
         -22.3703,  -4.7941, -19.6495, -16.0471,   7.0702,  -4.1602, -28.6626,
         -10.3997,  -2.9798]])
tensor([[ 1.0125,  0.3833,  1.0318,  0.3177,  0.1205,  0.2623, -0.2055,  0.1793,
          0.9806,  0.4636,  0.6986,  0.5297,  0.7588,  0.4369, -0.0350, -0.2707,
          0.6955,  1.4646,  0.7751, -0.4771,  0.1645,  0.6497,  0.2230,  0.3559,
          0.9896,  0.4139,  0.5306,  0.6933,

tensor([[-13.3109, -17.6586, -22.6130, -18.1277, -13.3338, -13.9144,  -5.0583,
         -12.6665, -15.2249, -13.3974,  -7.8443,  -2.6484,  -5.6877, -16.2637,
          -2.4342, -15.8707, -13.2478, -23.3710, -17.6797,  -1.9487, -13.5214,
         -30.4678,  -9.6489, -16.5979,  -7.3042,  -5.9155, -14.2448, -29.4232,
          -1.7010,   3.4217]])
tensor([[ 1.0510,  0.4223,  1.0968,  0.3158,  0.1160,  0.2770, -0.2325,  0.1847,
          1.0660,  0.4928,  0.7768,  0.5616,  0.8100,  0.4676, -0.0359, -0.2910,
          0.7338,  1.5493,  0.8011, -0.5000,  0.1720,  0.6793,  0.2586,  0.4079,
          1.0665,  0.4909,  0.5996,  0.7506,  0.4382,  0.6475]],
       grad_fn=<AddmmBackward0>)
i: 118
Mesh labels: [29]
tensor([[-17.6607, -15.2465, -24.5638, -20.3559, -15.6175, -14.5888,  -4.1492,
         -11.7338, -12.3722,  -9.7181,  -6.7731,  -1.8053,  -8.1024, -15.5580,
          -3.1293, -16.6138, -14.1054, -27.8091, -24.2799,   3.3553, -17.3860,
         -30.3973,  -4.9050, -21.1453,  -4.7528,  

tensor([[-13.9660, -12.2713, -12.0443,   5.6351,  -3.6740,  -6.9553,  -4.5959,
         -17.9461, -17.6826,  -5.2133, -19.0052, -23.7066, -23.1402,  -9.8901,
         -10.1013,  -2.3390, -25.3224, -11.6810,  -3.6288, -20.4719, -12.9614,
          -5.8187, -22.8622,  -8.5795, -23.6955, -13.3311, -20.4259, -11.6520,
         -14.3199, -25.3500]])
tensor([[ 1.1401,  0.5019,  1.1986,  0.3290,  0.1227,  0.2811, -0.2402,  0.2047,
          1.1375,  0.5138,  0.8171,  0.5996,  0.8537,  0.5029, -0.0460, -0.3165,
          0.7677,  1.6332,  0.8744, -0.5076,  0.1937,  0.7096,  0.2693,  0.4393,
          1.1272,  0.5444,  0.6463,  0.8269,  0.5078,  0.7172]],
       grad_fn=<AddmmBackward0>)
i: 15
Mesh labels: [3]
tensor([[-14.2403, -12.7981, -11.2377,   5.2370,  -3.5653,  -7.9844,  -4.7698,
         -18.8413, -16.3065,  -5.1471, -18.1189, -23.2033, -22.8174, -10.6906,
          -8.7109,  -2.6504, -25.2361, -11.8052,  -3.2504, -19.7953, -12.6823,
          -7.1463, -21.5870,  -8.7290, -22.0186, -12

tensor([[ -5.3056,  -3.2552, -24.4040, -15.7908, -21.0671,  -1.8737,  -2.4133,
           5.9620, -26.3756, -11.7919, -10.4324,  -3.8186, -11.6785,  -7.7541,
         -17.2509,  -8.5960,  -5.1452, -24.3250, -22.0715,  -5.9061, -20.2019,
         -13.2944, -26.0743,  -8.6056, -21.3844, -17.4667, -22.8803,  -1.7048,
         -12.7513, -12.7094]])
tensor([[ 1.2007,  0.5148,  1.2641,  0.3739,  0.1607,  0.2967, -0.2377,  0.2439,
          1.1756,  0.5158,  0.8542,  0.5848,  0.8799,  0.5254, -0.0090, -0.3297,
          0.7890,  1.6828,  0.8952, -0.5088,  0.1986,  0.7155,  0.2749,  0.4359,
          1.1783,  0.5440,  0.6564,  0.8481,  0.5452,  0.7375]],
       grad_fn=<AddmmBackward0>)
i: 29
Mesh labels: [7]
tensor([[ -4.8895,  -2.3995, -24.5613, -17.8141, -22.8905,  -1.8075,  -2.1679,
           7.4466, -26.3032, -12.3963,  -8.0546,  -1.4604, -11.1244,  -9.0692,
         -17.2034,  -9.4489,  -1.9529, -25.8494, -23.8965,  -4.3958, -21.3874,
         -15.2626, -26.1622,  -8.3694, -19.8813, -17

tensor([[-11.6718,  -2.5958,  -7.4301, -17.4365, -22.3056, -12.8318,  -3.5272,
          -7.7282,  -8.9709,  -9.8538,   6.2881,  -3.5478, -18.7555, -25.7640,
          -2.9329,  -8.6665,  -1.8150, -26.8913, -18.5183,  -3.0664, -22.5987,
         -29.0522, -17.2185,  -7.3923,  -0.4747, -14.0919, -24.0024, -20.0172,
          -3.5677,  -3.6322]])
tensor([[ 1.2756,  0.5535,  1.3816,  0.3972,  0.1607,  0.3219, -0.3002,  0.2974,
          1.3352,  0.5762,  0.9605,  0.6360,  0.9560,  0.5760, -0.0430, -0.3748,
          0.8555,  1.8134,  0.9254, -0.5515,  0.2205,  0.7389,  0.3148,  0.4892,
          1.2692,  0.6223,  0.7119,  0.8838,  0.5781,  0.7858]],
       grad_fn=<AddmmBackward0>)
i: 43
Mesh labels: [10]
tensor([[-10.7335,  -0.9883,  -5.9118, -16.8425, -23.7691, -12.3235,  -3.3852,
          -6.6129, -10.4517,  -9.9265,   6.6998,  -4.5129, -20.9599, -26.4770,
          -3.8285,  -6.6393,  -0.8745, -27.1926, -17.8756,  -4.7551, -24.2907,
         -27.9905, -21.0365,  -4.9740,  -2.2693, -1

tensor([[-20.3809, -13.3521, -10.1346, -11.6553, -13.3656, -19.2275,  -5.9840,
         -20.2482,  -6.5062,  -6.6484,  -4.9090, -11.8888, -19.6884, -20.8907,
           3.5689,  -8.4722, -19.5445, -23.8601, -13.2722,  -4.5353, -19.6709,
         -27.9231, -10.0866, -14.3799,  -2.6616,  -7.7665, -12.2356, -28.6508,
          -4.5376,  -3.2128]])
tensor([[ 1.2263,  0.5669,  1.3284,  0.3885,  0.1703,  0.3418, -0.2440,  0.2856,
          1.2776,  0.6003,  0.9533,  0.6753,  0.9595,  0.5611, -0.0138, -0.3327,
          0.8156,  1.7259,  0.9055, -0.5270,  0.2106,  0.7240,  0.2889,  0.4617,
          1.2081,  0.5761,  0.6883,  0.8468,  0.5585,  0.7504]],
       grad_fn=<AddmmBackward0>)
i: 59
Mesh labels: [14]
tensor([[-20.5121, -10.8599,  -7.5975, -11.9631, -13.1542, -18.6488,  -6.4280,
         -20.0937,  -4.2401,  -6.0960,  -2.7362, -11.5782, -19.2985, -22.1444,
           4.0644,  -8.5918, -17.2663, -21.8911, -12.9144,  -3.9298, -19.6721,
         -27.1996,  -7.6258, -14.0386,   0.8437,  -

tensor([[ -6.4295, -14.6801,  -4.1200,  -0.1680,  -4.3292,  -6.5845,  -6.2795,
         -17.6786, -15.8085, -10.2893, -15.0795, -19.4315, -19.0610, -15.7840,
          -7.7838,  -4.5055, -16.7387,  -1.5443,   8.1127, -22.9785,  -9.2824,
         -11.0889, -21.8150,   0.4739, -19.2742, -12.8191, -21.3896, -15.9492,
          -3.1681, -20.7893]])
tensor([[ 1.2765,  0.5842,  1.4021,  0.3974,  0.1638,  0.3641, -0.2840,  0.3036,
          1.3653,  0.6399,  1.0418,  0.7319,  1.0439,  0.6249,  0.0073, -0.3142,
          0.9083,  1.8504,  0.9431, -0.5574,  0.2242,  0.7381,  0.3160,  0.4906,
          1.2734,  0.6248,  0.7289,  0.8725,  0.5764,  0.7822]],
       grad_fn=<AddmmBackward0>)
i: 74
Mesh labels: [18]
tensor([[ -6.8667, -15.2529,  -4.2042,   0.6357,  -4.3796,  -7.5659,  -6.3964,
         -18.6289, -16.0172, -10.4212, -15.2902, -20.4248, -20.2556, -16.4315,
          -7.5203,  -4.4047, -18.0207,  -2.8373,   7.9993, -23.6170,  -9.4781,
         -11.8062, -22.7356,   0.1718, -19.7938, -1

tensor([[-21.8248, -15.1292, -15.4215, -13.5570,  -6.3741, -14.9675,  -7.6623,
         -21.0492,  -0.1989,  -2.2009, -12.4088, -11.9550, -11.2910, -10.2320,
          -2.9593, -15.5360, -20.9877, -16.1200, -17.2124,  -0.5606, -12.3409,
         -19.7366,   8.4618, -23.1250,  -2.1550,  -3.5720,  -2.3702, -25.6527,
         -12.1592,  -2.6778]])
tensor([[ 1.2553,  0.5858,  1.3903,  0.4059,  0.1884,  0.4092, -0.2471,  0.3035,
          1.3232,  0.6380,  0.9935,  0.7280,  1.0207,  0.5936,  0.0432, -0.2656,
          0.9233,  1.8678,  1.0526, -0.5148,  0.2798,  0.7563,  0.2987,  0.4574,
          1.2407,  0.6079,  0.7044,  0.8753,  0.5803,  0.7702]],
       grad_fn=<AddmmBackward0>)
i: 90
Mesh labels: [22]
tensor([[-21.2384, -18.9784, -18.9435, -14.0430,  -5.6121, -15.6072,  -7.5156,
         -21.7006,  -2.0901,  -3.5385, -15.3556, -11.6082,  -9.1916,  -8.4153,
          -3.5637, -17.0077, -23.0643, -17.1053, -17.4319,  -1.0247, -10.6441,
         -21.1512,   7.3846, -24.3821,  -5.0300,  -

tensor([[-21.0036, -13.9684, -17.1631,  -9.6451,  -6.3213, -13.1229,  -5.6522,
         -15.5990,  -4.9357,  -0.1590, -18.4234, -14.7758, -13.5731,   0.1302,
          -3.6450,  -8.6923, -24.8018, -17.2795, -15.0606,  -1.1901, -13.8472,
         -10.6494,  -2.2905, -19.3923, -11.3450,  -1.8677,   7.9157, -15.1493,
         -14.5005,  -6.1887]])
tensor([[ 1.3197,  0.6160,  1.4748,  0.4283,  0.1736,  0.4478, -0.2891,  0.3037,
          1.4404,  0.6774,  1.1142,  0.7775,  1.0835,  0.6234,  0.0707, -0.2831,
          0.9855,  1.9795,  1.0563, -0.5413,  0.3230,  0.8201,  0.3956,  0.5435,
          1.3547,  0.6568,  0.7347,  0.8813,  0.6037,  0.8004]],
       grad_fn=<AddmmBackward0>)
i: 105
Mesh labels: [26]
tensor([[-21.1276, -13.8278, -17.8025,  -9.8308,  -6.5154, -12.9167,  -5.6215,
         -15.2185,  -5.4175,  -0.1052, -18.7047, -14.6672, -13.5262,   0.5832,
          -4.0985,  -8.7271, -24.9130, -17.5451, -15.6229,  -0.9495, -14.1109,
         -10.3972,  -2.3298, -19.7104, -11.7172,  

i: 119
Mesh labels: [29]
tensor([[-18.8807, -12.3198, -21.9328, -17.8029, -16.0201, -14.3143,  -4.0312,
         -10.8912, -11.3684,  -6.8313,  -7.8095,  -4.8690, -11.8939, -12.9485,
          -2.8966, -13.0286, -15.8504, -27.3249, -22.9779,   3.0996, -19.1669,
         -25.8141,  -6.5076, -19.8380,  -5.8325,  -7.0266,  -8.9947, -23.0040,
          -9.8068,   1.2095]])
tensor([[ 1.3367,  0.6457,  1.4962,  0.3987,  0.2200,  0.4592, -0.2186,  0.3635,
          1.4524,  0.6647,  1.0858,  0.7490,  1.0894,  0.6245,  0.1277, -0.2698,
          0.9788,  2.0056,  1.1692, -0.5143,  0.3261,  0.8430,  0.3805,  0.5297,
          1.3964,  0.7042,  0.7973,  0.9941,  0.6778,  0.8096]],
       grad_fn=<AddmmBackward0>)
epoch: 8, loss: 879.8328861296177
i: 0
Mesh labels: [0]
tensor([[  5.4885, -19.8533, -21.4682,  -9.6839,  -8.4958,  -3.6247,  -4.4009,
          -6.7783, -23.9704, -19.1216, -15.8959,  -6.0566,  -4.8584, -11.2263,
         -16.3660, -13.7719,  -8.6655, -10.7375,  -5.2502, -18.5240,  -0.

tensor([[-12.6880, -12.8750, -10.0355,   5.0915,  -2.9794,  -7.6716,  -4.5700,
         -18.3993, -15.3633,  -5.6254, -17.1177, -22.0048, -21.5706, -11.0255,
          -8.2964,  -3.0174, -23.5324, -10.5834,  -1.8890, -19.7286, -11.2272,
          -7.6164, -20.7858,  -7.4569, -21.0455, -11.4676, -19.3902, -13.6317,
         -11.7398, -22.7251]])
tensor([[ 1.5034,  0.7590,  1.6801,  0.4314,  0.2144,  0.4791, -0.2867,  0.3916,
          1.6313,  0.7267,  1.2314,  0.8264,  1.2070,  0.7068,  0.1037, -0.3280,
          1.0769,  2.2089,  1.2562, -0.5463,  0.3643,  0.9002,  0.4385,  0.6082,
          1.5411,  0.8137,  0.8867,  1.0929,  0.7699,  0.9195]],
       grad_fn=<AddmmBackward0>)
i: 14
Mesh labels: [3]
tensor([[-13.9660, -12.2713, -12.0443,   5.6351,  -3.6740,  -6.9553,  -4.5959,
         -17.9461, -17.6826,  -5.2133, -19.0052, -23.7066, -23.1402,  -9.8901,
         -10.1013,  -2.3390, -25.3224, -11.6810,  -3.6288, -20.4719, -12.9614,
          -5.8187, -22.8622,  -8.5795, -23.6955, -13

tensor([[-14.8296, -18.9902, -28.8402, -15.5756, -15.2484, -11.4294,  -2.6644,
         -13.2581, -24.5787, -13.1838, -15.5056,  -8.6107, -15.0708, -15.5415,
         -12.3020, -13.9708, -18.9744, -28.3200, -21.5157,  -9.3443, -19.8563,
         -25.5049, -21.4479, -16.4845, -22.2518, -11.6252, -22.7750, -25.7483,
         -13.4401, -11.7617]])
tensor([[ 1.5547,  0.8183,  1.7818,  0.5023,  0.2630,  0.5148, -0.3005,  0.4026,
          1.6735,  0.7493,  1.2663,  0.8575,  1.2293,  0.7290,  0.1108, -0.3322,
          1.1012,  2.2595,  1.2998, -0.5517,  0.3858,  0.9199,  0.4469,  0.6369,
          1.5761,  0.8397,  0.9055,  1.1240,  0.8025,  0.9558]],
       grad_fn=<AddmmBackward0>)
i: 27
Mesh labels: [6]
tensor([[-13.9090, -10.3987, -20.2173, -14.5899, -18.8993, -11.2420,  -2.4455,
          -9.3584, -21.5918, -10.7604,  -7.8127,  -8.2261, -19.0516, -18.0673,
          -8.9307,  -8.0612, -13.4881, -28.0867, -19.7504,  -7.6784, -23.4785,
         -23.5480, -23.4252, -10.9774, -16.5897, -14

tensor([[ -9.8054,  -3.0362,  -7.7672, -16.0421, -22.0341, -12.0270,  -2.7380,
          -6.8935, -11.8634, -10.3999,   5.5222,  -3.5391, -19.0065, -24.9962,
          -3.9015,  -6.5952,  -1.8166, -26.7677, -17.2053,  -4.8793, -22.5182,
         -27.6809, -20.6622,  -4.9033,  -3.8696, -14.3837, -25.3255, -18.7351,
          -3.4505,  -5.7859]])
tensor([[ 1.5119,  0.8019,  1.7345,  0.4937,  0.3038,  0.5411, -0.2349,  0.4672,
          1.6348,  0.7423,  1.1965,  0.7997,  1.1759,  0.6808,  0.1563, -0.2931,
          1.0551,  2.1703,  1.2840, -0.5074,  0.3720,  0.8964,  0.4161,  0.5913,
          1.5271,  0.7894,  0.8646,  1.0961,  0.8073,  0.9097]],
       grad_fn=<AddmmBackward0>)
i: 41
Mesh labels: [10]
tensor([[-11.2173,  -6.1620, -11.1898, -17.2096, -22.5225, -13.7300,  -3.1268,
          -8.5890, -14.1684, -11.9777,   3.7165,  -3.9115, -19.1191, -25.7827,
          -3.5140,  -8.1554,  -4.8522, -29.2217, -18.6284,  -5.1977, -23.2068,
         -30.7806, -21.5459,  -7.0243,  -5.5154, -1

tensor([[-13.8156, -12.8400, -23.8924,  -9.2676,  -7.2072,  -5.5136,  -4.7157,
          -7.4916, -14.0714,  -3.9144, -22.4206, -13.1019,  -8.7493,   5.0935,
         -12.8874, -10.2377, -20.8854, -15.0960, -16.5194,  -4.8228, -10.2136,
          -5.1903,  -9.4925, -18.2005, -20.1399,  -5.3534,  -0.6626,  -6.9383,
         -17.4111, -10.8901]])
tensor([[ 1.5809,  0.8590,  1.8392,  0.5070,  0.3053,  0.5762, -0.2666,  0.4997,
          1.7751,  0.8305,  1.3500,  0.9155,  1.2937,  0.7356,  0.1438, -0.3184,
          1.1155,  2.2883,  1.3316, -0.5428,  0.3988,  0.9145,  0.4494,  0.6314,
          1.6038,  0.8572,  0.9281,  1.1318,  0.8361,  0.9565]],
       grad_fn=<AddmmBackward0>)
i: 55
Mesh labels: [13]
tensor([[-14.7091, -18.4965, -29.1599, -10.0573,  -4.9917,  -5.9170,  -5.3289,
         -10.4114, -17.2106,  -6.2029, -27.3137, -14.5589,  -6.6187,   6.1483,
         -15.1838, -13.4674, -24.3929, -15.6845, -17.5054,  -7.2159,  -8.2009,
          -7.0815, -10.0279, -21.1741, -24.5894,  -

tensor([[ -6.8667, -15.2529,  -4.2042,   0.6357,  -4.3796,  -7.5659,  -6.3964,
         -18.6289, -16.0172, -10.4212, -15.2902, -20.4248, -20.2556, -16.4315,
          -7.5203,  -4.4047, -18.0207,  -2.8373,   7.9993, -23.6170,  -9.4781,
         -11.8062, -22.7356,   0.1718, -19.7938, -12.7229, -22.2121, -16.9140,
          -3.4312, -21.4502]])
tensor([[ 1.4331,  0.8932,  1.7413,  0.5133,  0.2952,  0.6310, -0.2613,  0.3729,
          1.6282,  0.8666,  1.2664,  1.0105,  1.2345,  0.7123,  0.1382, -0.1850,
          1.0941,  2.1405,  1.2634, -0.5241,  0.3910,  0.8990,  0.4218,  0.6510,
          1.4389,  0.8088,  0.8786,  1.0423,  0.7397,  0.9110]],
       grad_fn=<AddmmBackward0>)
i: 75
Mesh labels: [18]
tensor([[ -6.2519, -15.5311,  -4.6246,   0.0701,  -3.5657,  -6.7552,  -6.3899,
         -18.1952, -15.8199, -10.5677, -15.7134, -19.7100, -18.7206, -15.6698,
          -8.1301,  -5.1543, -17.3226,  -1.5431,   8.1775, -23.3953,  -8.3856,
         -11.3226, -21.4789,   0.1169, -19.7186, -1

tensor([[-17.1850,  -7.1073, -14.7938,  -1.7395,  -2.3789,   1.4221,  -6.6295,
         -13.9747, -20.0892,  -2.9650, -25.4700, -23.6302, -17.1402,  -1.8111,
         -17.4176,  -3.7117, -21.3280,  -0.1791,  -7.0395, -18.3350, -16.8462,
           9.6003, -18.4236, -11.0242, -24.9167, -19.4055, -13.2250,  -1.3964,
         -19.1988, -27.6331]])
tensor([[ 1.6419,  0.9456,  1.9901,  0.5458,  0.3282,  0.6878, -0.3218,  0.5054,
          1.9116,  0.9305,  1.4745,  1.0765,  1.4451,  0.8439,  0.1706, -0.2438,
          1.2924,  2.5480,  1.5530, -0.5548,  0.5040,  0.9641,  0.4882,  0.6881,
          1.6754,  0.9707,  0.9933,  1.1959,  0.8686,  1.0211]],
       grad_fn=<AddmmBackward0>)
i: 88
Mesh labels: [22]
tensor([[-24.1869, -16.2579, -18.5360, -14.4957,  -6.7891, -15.6602,  -7.5203,
         -21.3831,  -1.1955,  -1.4690, -14.5474, -12.5893, -12.0231,  -8.8962,
          -3.5067, -15.8422, -23.6550, -18.1094, -19.6146,   0.5762, -14.0230,
         -19.8573,   9.2143, -25.6817,  -3.6654,  -

tensor([[-11.3650, -25.5086, -23.8257,  -9.8779,  -2.8680, -14.9700,  -4.6951,
         -18.6867,  -7.7704,  -8.8725, -18.9919,  -9.7815,  -5.2168,  -4.0773,
          -7.1178, -16.8865, -23.2980, -19.4247, -13.4267,  -7.0261,  -1.6310,
         -22.3703,  -4.7941, -19.6495, -16.0471,   7.0702,  -4.1602, -28.6626,
         -10.3997,  -2.9798]])
tensor([[ 1.6818,  0.9390,  2.0181,  0.5443,  0.3458,  0.7279, -0.2829,  0.5516,
          1.9606,  0.9260,  1.5087,  1.0474,  1.4659,  0.8393,  0.2599, -0.2348,
          1.3164,  2.6045,  1.6041, -0.5272,  0.5464,  1.0390,  0.5636,  0.7122,
          1.7637,  0.9667,  0.9883,  1.2121,  0.9130,  1.0155]],
       grad_fn=<AddmmBackward0>)
i: 103
Mesh labels: [25]
tensor([[-14.3204, -22.8477, -19.3216,  -8.9437,  -4.2516, -16.6635,  -5.2487,
         -20.2665,  -4.2940,  -5.9561, -17.7130, -13.0189, -10.2812,  -5.3670,
          -5.5154, -14.8676, -24.8720, -20.1338, -12.8372,  -6.9348,  -4.8901,
         -21.1873,  -4.6956, -19.3544, -13.7973,  

tensor([[-14.9681, -21.4830, -27.5907, -20.2782, -12.7485, -15.4414,  -4.5263,
         -14.4074, -14.7664, -13.7452,  -9.4865,  -0.9243,  -3.6304, -15.9467,
          -3.5095, -19.6070, -15.4743, -26.7960, -21.8208,   0.1929, -12.7745,
         -33.8928,  -6.2963, -21.3034,  -7.6566,  -2.9492, -13.2439, -34.3099,
          -4.4751,   5.7164]])
tensor([[ 1.6898,  1.0193,  2.0805,  0.5355,  0.3747,  0.7732, -0.2685,  0.5569,
          2.0199,  0.9597,  1.5404,  1.0991,  1.4886,  0.8497,  0.2816, -0.2156,
          1.3316,  2.6513,  1.6907, -0.5241,  0.5726,  1.0811,  0.5862,  0.7709,
          1.8183,  1.0756,  1.0828,  1.3111,  0.9537,  1.0367]],
       grad_fn=<AddmmBackward0>)
i: 117
Mesh labels: [29]
tensor([[-13.3109, -17.6586, -22.6130, -18.1277, -13.3338, -13.9144,  -5.0583,
         -12.6665, -15.2249, -13.3974,  -7.8443,  -2.6484,  -5.6877, -16.2637,
          -2.4342, -15.8707, -13.2478, -23.3710, -17.6797,  -1.9487, -13.5214,
         -30.4678,  -9.6489, -16.5979,  -7.3042,  

In [10]:
# Random Pertubation Attack
dataloader = DataLoader(testing_opt)
overridden_meshes = []
for i, data in enumerate(dataloader):
    
    mesh = data["mesh"][0]
    num_random_changes = 0
    
    while(num_random_changes < 10):
        
        random_vertex_index = random.randint(0, len(mesh.vs)-1)  
        random_coordinate_index = random.randint(0, 2)  
        mesh.vs[random_vertex_index][random_coordinate_index] += random.uniform(-0.2, 0.2)
        mesh.features = extract_features(mesh)
        num_random_changes += 1
    
    overridden_meshes.append(mesh)

dataloader.dataloader.dataset.override_meshes(overridden_meshes) 

loaded mean / std from cache


In [11]:
# Record testing accuracy after attack
attacked_model_outputs = test_attacked_model(mesh_cnn, dataloader, opt_writer)

epoch: -1, TEST ACC: [95.0 %]

